### ISSUE TITLE
大佬,请教一下,抖音直播页面的cookie,怎么能直接获取

### ISSUE THREAD

**Issue by ooiooiooi** [ihmily/DouyinLiveRecorder#1]
我是用request获取不到

**Comment by ihmily** [comment]
刚上传了一个Selenium自动化获取直播间cookie的代码，详情请看：https://github.com/ihmily/DouyinLiveRecorder/blob/main/cookies.py

直播间页面的cookie有效期貌似挺长的，在浏览器手动获取也无伤大雅

**Comment by ihmily** [comment]
有问题欢迎提问~

**Comment by 1068093640** [comment]
> 有问题欢迎提问~

**Comment by 1068093640** [comment]
> 有问题欢迎提问~

有群吗。可以建个群方便交流
