### ISSUE TITLE
朋友推荐过来看看..

### ISSUE THREAD

**Issue by onlyclxy** [ihmily/DouyinLiveRecorder#102]
话说备份配置文件当时的目的是因为中途出现了个配置清空的bug
导致当时有人手搓五六百条链接的文档付之一炬..
然后因为没改好又给他搞没一次..他一晚上得手搓了快一千条才弄回来..
后来这个bug解决了.其实感觉这个备份有点多于..并且来回会增加文件不是..
还打印出来..这样显得多呆嘛
2333

**Comment by menheng** [comment]
这位是python的开源原作者吾爱大佬，竟然没人回复，很稀奇呢。

**Comment by onlyclxy** [comment]
> 这位是python的开源原作者吾爱大佬，竟然没人回复，很稀奇呢。

哈哈 又不是啥bug问题.   这种东西应该多多益善..  我最近老想录twitch.. github找了一圈也不知道哪个能用... 尬住了..
