### ISSUE TITLE
如何结束录播

### ISSUE THREAD

**Issue by 1583298606** [ihmily/DouyinLiveRecorder#103]
主播没下播，我想停止录制，直接关闭导致文件损坏，断网操作有点麻烦，还有简单的方法么

**Comment by Hertz221** [comment]
是Windows吗，直接Ctrl+C结束啊

**Comment by steven11304** [comment]
看到文檔說"2.当前暂无关闭直播录制选项，直接关掉软件即可中途停止录制。"
沒想到關閉後檔案直接壞了打不開
錄了很久，卻沒辦法開啟，讓我感覺很真的很差

**Comment by 1583298606** [comment]
> 看到文档说“2.当前暂无关闭直播录制选项，直接关掉软件即可中途停止录制。”自动 关闭后文件直接坏了打不开 录了，却没办法开启，让我感觉很爽真的很差

对的，直接关闭导致文件损坏。我是断网，他会自动慢慢结束完，你可以试一下

**Comment by Hertz221** [comment]
> 看到文檔說"2.当前暂无关闭直播录制选项，直接关掉软件即可中途停止录制。" 沒想到關閉後檔案直接壞了打不開 錄了很久，卻沒辦法開啟，讓我感覺很真的很差

我是一直Ctrl+C结束的，没遇到过损坏
