### ISSUE TITLE
AfreecaTV的Url格式和Cookie格式错误

### ISSUE THREAD

**Issue by daxiaamo** [ihmily/DouyinLiveRecorder#106]
AfreecaTV的Url格式是否只能是 
https://play.afreecatv.com/sw7love/249471484
这种格式的后几数字每次直播都会改变并不是固定的，没法长时间的自动化录制，是否可以直接通过
https://play.afreecatv.com/sw7love
这种格式来获取视频流？
还有就是能否给个AfreecaTV的Cookie的例子全部复制上去提示格式有问题。

**Comment by ihmily** [comment]
>这种格式的后几数字每次直播都会改变并不是固定的，没法长时间的自动化录制，是否可以直接通过
https://play.afreecatv.com/sw7love
这种格式来获取视频流？

之前没注意，下个版本更新成这种格式

**Comment by wangzaicake** [comment]
@daxiaamo cookie填写看我这个issues的反馈。https://github.com/ihmily/DouyinLiveRecorder/issues/137
