### ISSUE TITLE
虎牙最近无法录制

### ISSUE THREAD

**Issue by whnyn** [ihmily/DouyinLiveRecorder#107]
录制下来都是几百kb大小

**Comment by zhangyupy** [comment]
具体报错都没有，人家又不是神仙

**Comment by cjdgyyy** [comment]
![bandicam 2024-01-05 00-49-35-518](https://github.com/ihmily/DouyinLiveRecorder/assets/59786361/85da3455-5931-4aac-9953-f3368365317f)
说是网络错误

**Comment by cjdgyyy** [comment]
[错误日志文件.log](https://github.com/ihmily/DouyinLiveRecorder/files/13837219/default.log)
找到了

**Comment by 18202821297** [comment]
虎牙最近我找了很多类似的东西，都不行了，只有几秒的时间，不知道虎牙怎么搞的，好像是一次一个链接只给你3秒的时间，然后你看直播时也是一次3秒这样给了播放的，我从正常直播卡顿就是那个频率 几秒钟就给你卡一下

**Comment by ihmily** [comment]
> 虎牙最近我找了很多类似的东西，都不行了，只有几秒的时间，不知道虎牙怎么搞的，好像是一次一个链接只给你3秒的时间，然后你看直播时也是一次3秒这样给了播放的，我从正常直播卡顿就是那个频率 几秒钟就给你卡一下

1、虎牙官方更新了，新增了参数。所以原来的直播流地址现在只能录制几秒钟，或者直接403无法访问。

2、虽然更新了，但我修改了原来的直播流地址使用的cdn host后，可以在我项目中那个在线观看m3u8页面正常观看，不会断流。但问题是用ffmpeg下载就会403禁止访问，所以我一直没把它更新上去。

.

**Comment by 18202821297** [comment]
> > 虎牙最近我发现了很多类似的东西，都行了，只有几秒的时间，不知道虎牙怎么搞的，希望是一次一个链接只给你3秒的时间，然后你看直播时也是一次3秒这样给播放的，我从正常直播卡顿就是频率几秒就给你卡一下
> 
> 1、虎牙官方更新了，新增了参数。所以原来的直播流地址现在只能录制几个摄像头，或者直接403无法访问。
> 
> 2、虽然更新了，但我修改了原来的直播流地址使用的cdn主机后，可以在我项目中那个在线观看m3u8页面正常观看，不会断流。但问题是用ffmpeg下载就会403禁止访问，所以我一直没有把它更新上去。
> 
> 。

streamlink录制这个行不行呢，原来的地址是啥

**Comment by ihmily** [comment]
@18202821297 

![image](https://github.com/ihmily/DouyinLiveRecorder/assets/114978440/2b973404-033b-4ca0-9e30-2c3af9bc91e0)

你获取了直播源地址后，将其host地址修改为

`hw.flv.huya.com` 就可以正常观看了。

**Comment by 18202821297** [comment]
试了一下可以播放，但是用ffmpeg搞一下报错403然后你播放不了了，估计是不是搞了风控识别到了直接给你封ip

**Comment by 18202821297** [comment]
有个想法，既然flv.js可行播放，那么使用代码执行html然后把获取到的资源没内容进行录制是否可行，可以让gpt写

**Comment by 18202821297** [comment]
我看了是一段一段持续在下载，好像只有浏览器才可以

**Comment by ihmily** [comment]
最新版本3.0.2已修复虎牙直播录制 https://github.com/ihmily/DouyinLiveRecorder/releases/tag/v3.0.2
