### ISSUE TITLE
纯纯纯小白

### ISSUE THREAD

**Issue by LeslieCHENCHEN** [ihmily/DouyinLiveRecorder#109]
大佬，连安装都完全不会，能有个白痴版的教程吗？我按步骤没反应，哭了

**Comment by ihmily** [comment]
**纯纯纯小白版教程：**

1、下载 https://github.com/ihmily/DouyinLiveRecorder/releases/download/v2.0.7/DouyinLiveRecorder.v2.0.7.zip 这个压缩包

2、解压文件

3、打开解压后的文件夹，找到config文件夹，打开里面的 URL_config.ini 文件，在文件中添加要录制的直播间地址，一行一个，添加完后记得保存。

4、找到 DouyinLiveRecorder.v2.0.7.exe 文件，双击打开，等待加载即可。
