### ISSUE TITLE
b站录制报错

### ISSUE THREAD

**Issue by Timidwei** [ihmily/DouyinLiveRecorder#119]
错误信息: Command '['ffmpeg', '-y', '-v', 'verbose', '-rw_timeout', '15000000', '-loglevel', 'error', '-hide_banner', '-user_agent', 'Mozilla/5.0 (Linux; Android 11; SAMSUNG SM-G973U) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/14.2 Chrome/87.0.4280.141 Mobile Safari/537.36', '-protocol_whitelist', 'rtmp,crypto,file,http,https,tcp,tls,udp,rtp', '-thread_queue_size', '1024', '-analyzeduration', '2147483647', '-probesize', '2147483647', '-fflags', '+discardcorrupt', '-i', 'https://d1--cn-gotcha101.bilivideo.com/live-bvc/240723/live_384929788.m3u8?expires=1704658353&len=0&oi=245096067&pt=web&qn=10000&trid=10033f1663825eff4865b86333a0044ad192&sigparams=cdn,expires,len,oi,pt,qn,trid&cdn=cn-gotcha01&sign=e4371e60b996018085f99840684a6b8b&sk=322f2091d6bc8bf74d4dfc7898b7ff04&p2p_type=1&sl=1&free_type=0&mid=0&source=onetier&trace=10&site=1515fcbc6416a39f5c12bd004fb06b83&zoneid_l=151371777&sid_l=live_384929788_36590308&order=1', '-bufsize', '5000k', '-sn', '-dn', '-reconnect_delay_max', '30', '-reconnect_streamed', '-reconnect_at_eof', '-max_muxing_queue_size', '64', '-correct_ts_overflow', '1', '-map', '0', '-c:v', 'copy', '-c:a', 'copy', '-f', 'mp4', '../DouyinLiveRecorder/星星欣欣zzx/星星欣欣zzx_2024-01-08_03-11-36.mp4']' returned non-zero exit status 1. 发生错误的行数: 837

**Comment by ihmily** [comment]
下次报错，可以试试复制这个错误信息中的直播流链接，到 [m3u8在线播放器](https://jx.hmily.vip/play)  这个页面中播放，如果页面上能播放，但不能录制，可以反馈给我。

**Comment by Timidwei** [comment]
无法播放，任意直播间均报错
