### ISSUE TITLE
录制不了afreecatv，代理已开

### ISSUE THREAD

**Issue by menheng** [ihmily/DouyinLiveRecorder#120]
![%}IPIN)6H0A3C_6~G9`PX@1](https://github.com/ihmily/DouyinLiveRecorder/assets/109516293/acd5d7de-d16a-49eb-9ead-781327124dab)

**Comment by ihmily** [comment]
1、貌似你代理地址填写的有问题，请修改配置文件中的代理地址或者直接去掉

![image](https://github.com/ihmily/DouyinLiveRecorder/assets/114978440/cd886527-0803-4ce7-8ad5-f37827d3dead)

2、虽然仓库代码中已经更新，但目前发布的2.0.7版本只能输入 `https://play.afreecatv.com/ahrum0912/251207117` 这种带房间号的地址。

另外说明：
目前afreecatv 录制暂时只支持原画（最高）画质，对网络带宽要求**非常高**，请求速率几乎在每秒2M/s左右，录制出的视频比特率都在8000kbps以上，录制1个小时大概是4g文件大小，所以录制时请考虑代理网络是否能达到要求。

**Comment by menheng** [comment]
我先回答另外的，后面有空再回复你的第一点。1个小时4G算啥。我之前录制1h15G，总大小将近100G左右。

**Comment by xueli12** [comment]
> 1、貌似你代理地址填写的有问题，请修改配置文件中的代理地址或者直接去掉
> 
> ![image](https://private-user-images.githubusercontent.com/114978440/294830337-cd886527-0803-4ce7-8ad5-f37827d3dead.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2NzkxMDgsIm5iZiI6MTcwNTY3ODgwOCwicGF0aCI6Ii8xMTQ5Nzg0NDAvMjk0ODMwMzM3LWNkODg2NTI3LTA4MDMtNGNlNy04YWQ1LWYzNzgyN2QzZGVhZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExOVQxNTQwMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NjkyOTJiNjNmMjg2YmQ3OThkNjM2ZDUyMTMzZTdhMTc1NjNkMzY2M2ZjNGY1YzNiNmY4YzM5ZjFjMDZkMDZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5Enyq5vML5a9g1Z8c4JOLFOl6Grw1BlznY4jUum25_8)
> 
> 2、虽然仓库代码中已经更新，但目前发布的2.0.7版本只能输入 `https://play.afreecatv.com/ahrum0912/251207117` 这种带房间号的地址。
> 
> 另外说明： 目前afreecatv 录制暂时只支持原画（最高）画质，对网络带宽要求**非常高**，请求速率几乎在每秒2M/s左右，录制出的视频比特率都在8000kbps以上，录制1个小时大概是4g文件大小，所以录制时请考虑代理网络是否能达到要求。

作者大大你好！我这里下载的时候出现如下报错：好像代码在引用cookie时出现了问题：
2024-01-19 23:31:14.822 | WARNING  | utils:wrapper:17 - 错误信息: type: ConnectionError, ('Connection aborted.', InvalidURL("URL can't contain control characters. '_au=2c1e18937xxxxxxxxx此处省略xxxxxxxxxxxxxxxxx' (found at least ' ')")) in function get_afreecatv_stream_url at line: 501

**Comment by ihmily** [comment]
@xueli12 不加cookie呢？不加cookie能录的话，就别加了，你这个应该是有特殊字符串

**Comment by xueli12** [comment]
> @xueli12 不加cookie呢？不加cookie能录的话，就别加了，你这个应该是有特殊字符串

不加cookie不行，因为这个主播要登录才能看

**Comment by ihmily** [comment]
> 不加cookie不行，因为这个主播要登录才能看

该主播直播间地址发一下

**Comment by xueli12** [comment]
> > 不加cookie不行，因为这个主播要登录才能看
> 
> 该主播直播间地址发一下

https://play.afreecatv.com/famouskys/251962141

**Comment by a1122335** [comment]
我想问下 这个 代理怎么看   有人教下吗
