### ISSUE TITLE
软件无法运行

### ISSUE THREAD

**Issue by hellotyj** [ihmily/DouyinLiveRecorder#121]
大佬好啊  我解压压缩包后，一开始运行录制提示计算机丢失api-ms-win-core-path-|1-1-0.dll无法运行，后来我网上下载这个文件后。再运行录制应用，打开窗口后就闪退了，请问怎样可以解决呢？

**Comment by ihmily** [comment]
你是Windows7系统吗？因为python3.7以上pyinstaller就不支持win7了，我这是3.11下打包的，**版本不兼容**所以会闪退。

你可以试试下载 [DouyinLiveRecorder.v1.0.9](https://github.com/ihmily/DouyinLiveRecorder/releases/download/v1.0.9/DouyinLiveRecorder.v1.0.9_win7_x86.zip) 这个版本，如果没用，就没法了（如果会的话，可以自己在win7 python 3.7以下打包软件）。
