### ISSUE TITLE
请问生成的时间文件在哪，看直播录像时，怎么看见直播的实时时间呢？

### ISSUE THREAD

**Issue by YOLO-bai** [ihmily/DouyinLiveRecorder#133]
无

**Comment by ihmily** [comment]
要开启保存时间文件，需要关闭分段录制，保存在视频同目录下

![image](https://github.com/ihmily/DouyinLiveRecorder/assets/114978440/f4c82ad7-bd5d-4710-87ce-482e3e3d1a62)
