### ISSUE TITLE
快手报错

### ISSUE THREAD

**Issue by wwkk2580** [ihmily/DouyinLiveRecorder#135]
**版本**2.0.7
**环境**docker
**JSON 解码错误**
`type: JSONDecodeError, Expecting value: line 1 column 2848 (char 2847) in function get_kuaishou_stream_data at line: 355
`
 API 响应没有按预期返回 JSON 数据，或者返回的 JSON 数据格式不正确。
**列表索引错误和属性错误**
`type: TypeError, list indices must be integers or slices, not str in function get_kuaishou_stream_url at line: 339
`

**Comment by ihmily** [comment]
有时候会遇到json字符串中有不合法的undefined，导致json解析错误，最新2.0.8版本已修复这个问题。2.0.8版本的Docker镜像的话我还没更新没上传，你可以自己构建一下。

**Comment by wwkk2580** [comment]
好的，我本地打一下吧，有时间了我写个GitHub Actions
