### ISSUE TITLE
【反馈】软件很好用，AfreecaTV的Cookie格式获取出来了，貌似自动化提取的cookies不可用，开发大大可以看看如何优化

### ISSUE THREAD

**Issue by Joftal** [ihmily/DouyinLiveRecorder#137]
![bc891744-7563-4dc0-a9fb-11e8eb1235a3](https://github.com/ihmily/DouyinLiveRecorder/assets/42807405/bc0b6a43-bf8d-4c32-9629-9f3567ec5460)

**Comment by wangzaicake** [comment]
另一个软件里面保留的cookie是这样的，但是我没有找到有关联的内容，可能格式不一样
![image](https://github.com/ihmily/DouyinLiveRecorder/assets/42807405/c6710cbe-8899-40f8-8c64-fc4fd63aa90c)

**Comment by wangzaicake** [comment]
![61dc63d4-be2b-4ece-9a4e-3bba34320e44](https://github.com/ihmily/DouyinLiveRecorder/assets/42807405/6ab48e14-04ba-43c0-889e-05aa8afe56ae)
![c09cd3f8-9736-4f12-b2cf-44d2c630b253](https://github.com/ihmily/DouyinLiveRecorder/assets/42807405/ffff66eb-5117-45c1-9864-0d6163a7680d)
经过实验，cookie是从这个地方获取部分数据填入即可，作者可以做个正则啥的从配置中读取这几个项，方便使用

**Comment by Joftal** [comment]
# -*- encoding: utf-8 -*-

import time
from telnetlib import EC

from selenium import webdriver
from collections import OrderedDict
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC


def get_cookies(driver, url):
    driver.get(url)
    time.sleep(20)  # 等待页面加载
    # 获取 Cookie
    cookies = driver.get_cookies()
    return cookies

# 将 extract_specific_cookies 函数修改为使用 OrderedDict
def extract_specific_cookies(cookies_list):
    specific_cookies = OrderedDict()
    target_fields = ["NextChangePwd", "PdboxBbs", "PdboxTicket", "PdboxUser", "RDB", "_au", "_au3rd", "_ausa", "_ausb",
                     "isBbs"]

    for cookie in cookies_list:
        if cookie['name'] in target_fields:
            specific_cookies[cookie['name']] = cookie['value']

    return specific_cookies


# 将字典转换为适用于 requests 请求头的字符串
def dict_to_cookie_str(cookies_dict):
    cookie_str = '; '.join([f"{key}={value}" for key, value in cookies_dict.items()])
    return cookie_str


if __name__ == '__main__':
    login_url = "https://login.afreecatv.com/afreeca/login.php?szFrom=full&request_uri=https%3A%2F%2Fwww.afreecatv.com%2F"

    # 使用webdriver.ChromeOptions()来配置ChromeDriver的路径
    chrome_options = Options()
    chrome_options.add_argument('--disable-gpu')
    chrome_options.add_argument('--disable-extensions')
    chrome_options.add_argument('--disable-popup-blocking')
    chrome_options.add_argument('--disable-infobars')
    chrome_options.add_argument('--disable-extensions')
    chrome_options.add_argument('--disable-blink-features=AutomationControlled')
    chrome_options.add_argument('--disable-save-password-bubble')
    chrome_options.add_argument('--start-maximized')
    chrome_options.add_argument('--disable-autofill')

    # 禁用自动填充--浏览器打开了自动填充账号/密码貌似会影响运行，整个保底
    prefs = {"profile.autocomplete": "off"}
    chrome_options.add_experimental_option("prefs", prefs)

    driver = webdriver.Chrome(options=chrome_options)

    try:
        # 打开登录页面
        driver.get(login_url)

        # 定位账号输入框并输入账号
        account_input = driver.find_element(By.ID, "uid")
        account_input.send_keys("登录账号")  # 替换为你的账号

        # 定位密码输入框并输入密码
        password_input = driver.find_element(By.ID, "password")
        password_input.send_keys("登录账号密码")  # 替换为你的密码

        # 定位登录按钮并点击
        login_button = driver.find_element(By.CLASS_NAME, "btn_st1")
        login_button.click()

        # 使用显式等待等待 "下次更改" 元素出现--长时间未修改密码登录后会出现这个界面
        wait = WebDriverWait(driver, 10)
        next_time_change = wait.until(EC.visibility_of_element_located((By.XPATH, "//span[text()='下次更改']")))
        next_time_change.click()

        # 获取登录后的Cookies
        cookies_list = get_cookies(driver, login_url)
        specific_cookies = extract_specific_cookies(cookies_list)

        # 打印需要的cookie字段，每个字段占一行
        for key, value in specific_cookies.items():
            print(f"{key}:{value};")

    finally:
        # 关闭浏览器
        driver.quit()

**Comment by Joftal** [comment]
貌似用python自动化测试提取出的cookies信息是一次性的，和正常浏览器登陆获取到的cookies值不一样，导致没办法使用，作者大大可以看看我的代码中有什么可以改进的地方，让提取的cookies可以使用
代码地址：https://github.com/Joftal/-get-AfreecaTVCookies/blob/master/AfCookies.py @ihmily

**Comment by ihmily** [comment]
最新v3.0.1-beta 已使用请求登录接口获取Cookie

**Comment by ihmily** [comment]
感谢反馈!
