### ISSUE TITLE
【提问】监控录制的时候出现的问题。

### ISSUE THREAD

**Issue by QIQIlr** [ihmily/DouyinLiveRecorder#140]
1.最近在监控录制的时候，总是出现问题。
首先我设置的1小时分段。录制的时候，最开始会生成30分钟的正常录制的mp4视频，然后就是20多个2秒钟的视频，最后会生成一个很大的文件，3-5GB左右，（根据主播直播时间）。最后的大文件音画不同步，3-5个GB 却只有3-5分钟左右，视频后面部分会疯狂加速。从24号开始发现这个问题。不知道怎么解决。
![1706194687475](https://github.com/ihmily/DouyinLiveRecorder/assets/126252892/d43ac082-ea3e-4949-aa53-cdeda0b22456)

2.还有就是如何获取抖音的Cookie ？ 我在网上搜的教程获取的Cookie 很长很长。但是你默认给的Cookie是很短的，不知道怎么获取呢？
![1706194493956](https://github.com/ihmily/DouyinLiveRecorder/assets/126252892/a36538a4-63af-4e5d-ac5e-83d2d03319f5)

**Comment by ihmily** [comment]
1.尝试缩短分段时长 和 使用ts格式录制

2. cookie获取方式与你图中类似，只要正确就行，长短不重要。至于为什么长度不一样，这跟浏览器也有关系，cookie中有大部分参数是无用的，你可以试试换个浏览器获取。

**Comment by daraker** [comment]
你好，请问你的问题解决了吗，我的就是只有几分钟，然后后面的内容疯狂快进
