### ISSUE TITLE
反馈

### ISSUE THREAD

**Issue by EchoZkk** [ihmily/DouyinLiveRecorder#141]
你好大哥  抖音直播录制   在抖音网页直播间有原画  蓝光  超清  高清  标清  五个画质   可是软件只有除了蓝光之外的四个画质   如果抖音直播间有蓝光画质的话   在软件录制原画  会录制成蓝光画质 而不是原画  请问这个可以修改一下嘛  谢谢大哥 
![screenshot-1706208575048](https://github.com/ihmily/DouyinLiveRecorder/assets/157740517/ed424bb2-6d09-41ca-90d6-a75c0c14c82e)

**Comment by ihmily** [comment]
蓝光(原画)>超清>高清>标清

抖音一般蓝光画质和原画是一样的。而且录制软件内的画质设置也是相对的，画质按照直播间画质从高到低。原画（蓝光）代表的就是最高画质，有时候直播间里最高只有超清画质，那么此时录制软件里的原画和蓝光就是超清画质。

而如果直播间最高清晰度只有超清和高清，那么录制时，配置里的原画对应的就是超清画质，而超清画质就是高清画质。

如果直播间只有标清画质，那么此时原画、超清、高清和标清等配置，录制的都是一样的，都是标清画质。

总之，你只需要确定，如果要录制最高画质，那配置为原画即可，如果要录制最低画质，那填写标清即可。不用管直播间里的最高画质具体是什么。
