### ISSUE TITLE
panda TV能添加吗？可以提供账号

### ISSUE THREAD

**Issue by a186232641** [ihmily/DouyinLiveRecorder#143]

**Comment by ihmily** [comment]
好的，这两天更新

**Comment by ihmily** [comment]
最新2.0.9版本已新增该直播录制

**Comment by a186232641** [comment]
> 最新2.0.9版本已新增该直播录制

这个可以录制19+吗？因为看19+需要账号的

**Comment by ihmily** [comment]
我翻了几页没看到需要19+观看的，你可以测试一下。大概率需要登录后的cookie

**Comment by xueli12** [comment]
> 我翻了几页没看到需要19+观看的，你可以测试一下。大概率需要登录后的cookie

大大，我在配置文件填了代理，小猫咪也运行了（但没开系统代理），但运行程序录制pandalive时，没有使用代理。然后我看源代码，发现main.py中 need_proxy_url中只有下面两个平台，是否是因为这里没有pandalive而导致没有使用代理。                                # 添加代理参数
                                need_proxy_url = ['tiktok', 'afreecatv']
                                for i in need_proxy_url:
                                    if i in real_url:
                                        if use_proxy and proxy_addr != '':
                                            # os.environ["http_proxy"] = proxy_addr
                                            ffmpeg_command.insert(1, "-http_proxy")
                                            ffmpeg_command.insert(2, proxy_addr)
                                            break

**Comment by ihmily** [comment]
> > 我翻了几页没看到需要19+观看的，你可以测试一下。大概率需要登录后的cookie
> 
> 大大，我在配置文件填了代理，小猫咪也运行了（但没开系统代理），但运行程序录制pandalive时，没有使用代理。然后我看源代码，发现main.py中 need_proxy_url中只有下面两个平台，是否是因为这里没有pandalive而导致没有使用代理。 # 添加代理参数 need_proxy_url = ['tiktok', 'afreecatv'] for i in need_proxy_url: if i in real_url: if use_proxy and proxy_addr != '': # os.environ["http_proxy"] = proxy_addr ffmpeg_command.insert(1, "-http_proxy") ffmpeg_command.insert(2, proxy_addr) break

感谢提醒，已修复

**Comment by xueli12** [comment]
> > > 我翻了几页没看到需要19+观看的，你可以测试一下。大概率需要登录后的cookie
> > 
> > 
> > 大大，我在配置文件填了代理，小猫咪也运行了（但没开系统代理），但运行程序录制pandalive时，没有使用代理。然后我看源代码，发现main.py中 need_proxy_url中只有下面两个平台，是否是因为这里没有pandalive而导致没有使用代理。 # 添加代理参数 need_proxy_url = ['tiktok', 'afreecatv'] for i in need_proxy_url: if i in real_url: if use_proxy and proxy_addr != '': # os.environ["http_proxy"] = proxy_addr ffmpeg_command.insert(1, "-http_proxy") ffmpeg_command.insert(2, proxy_addr) break
> 
> 感谢提醒，已修复

如果配置文件中能加多一个参数，以后如果还有其他需要代理的平台加入的话这部分代码就可以不用修改了，也方便用户选择哪些平台开启代理。比如：
配置文件：开启代理的平台=['tiktok', 'afreecatv']
main.py：need_proxy_url 读取配置文件的上面这个参数的值
