### ISSUE TITLE
telegram notifications when launching the application

### ISSUE THREAD

**Issue by AvrilL161** [ihmily/DouyinLiveRecorder#148]
If I launch the application and the broadcast is already in progress, recording begins, should I receive a notification in Telegram?
or does the notification only come if the broadcast started while monitoring?

This config correct?
[推送配置]
直播状态通知(可选微信|钉钉或者两个都填) = 
钉钉推送接口链接 = 
微信推送接口链接 = 
钉钉通知@对象(填手机号) = 
直播状态通知(可选微信|钉钉|tg或者都填) = tg
tgapi令牌 = 6XXXXXXXXX:AAE9XXXXXXxxxxxXXXXXXXXXxxxxXXXXX
tg聊天id(个人或者群组id) = XXXXXXXXX

**Comment by ihmily** [comment]
It may be the first, To be precise, it is to send notifications when a live broadcast is detected to be in progress. where as long as the recording software detects that the live broadcast is in progress, a notification will be sent when the recording starts. Please pay attention to setting your detection frequency (time interval)

`直播状态通知(可选微信|钉钉|tg或者都填) = tg`  => `直播状态通知(可选微信|钉钉|tg或者都填) = TG`

It should be  uppercase letter `TG` , and other configurations are correct.

**Comment by AvrilL161** [comment]
Thank you so match! works with "TG"

**Comment by ihmily** [comment]
No tkinks. In fact, this was my mistake. I mistakenly wrote `直播状态通知(可选微信|钉钉|TG或者都填) =` as `直播状态通知(可选微信|钉钉|tg或者都填) =` , it causes users to fill in errors. But it has been fixed in the latest version, maybe you could update to [Releases v2.0.9](https://github.com/ihmily/DouyinLiveRecorder/releases/tag/v2.0.9)

**Comment by AvrilL161** [comment]
I updated the application version, but left the old config. Everything is clearly described in the new config file, thank you
