### ISSUE TITLE
大佬，问下docker容器起来的报这个错是什么原因，试了同样的地址，用release的windows的包可以正常录制的

### ISSUE THREAD

**Issue by chenqifeng6** [ihmily/DouyinLiveRecorder#151]
2024-01-30 02:33:24,322 - 错误信息: type: JSONDecodeError, Expecting value: line 1 column 3898 (char 3897) in function get_kuaishou_stream_data at line: 355
2024-01-30 02:33:24,323 - 错误信息: type: TypeError, list indices must be integers or slices, not str in function get_kuaishou_stream_url at line: 339
2024-01-30 02:33:24,323 - 错误信息: 'list' object has no attribute 'get' 发生错误的行数: 635

**Comment by chenqifeng6** [comment]
![1706554770173](https://github.com/ihmily/DouyinLiveRecorder/assets/154393700/5c8108bb-1ed2-40c6-9de8-f0812f5310ab)

**Comment by chenqifeng6** [comment]
![1706554988007](https://github.com/ihmily/DouyinLiveRecorder/assets/154393700/8e2b3e3e-8a1d-43a6-a94c-d6912f0f3986)

**Comment by chenqifeng6** [comment]
> ![1706554988007](https://private-user-images.githubusercontent.com/154393700/300575419-8e2b3e3e-8a1d-43a6-a94c-d6912f0f3986.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1NTUzNjcsIm5iZiI6MTcwNjU1NTA2NywicGF0aCI6Ii8xNTQzOTM3MDAvMzAwNTc1NDE5LThlMmIzZTNlLThhMWQtNDNhNi1hOTRjLWQ2OTEyZjBmMzk4Ni5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyOVQxOTA0MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMWQ3NTA2NTgzZDUxYzIyMzA5ZWE3NDQxYzZmNDk5YmJlN2NmODljZTMxYTNkMWU1OTc1YzA5NTg1N2ExMTFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ECzocN2hNZpsbffKJwEo-WDad8zw4Oi5uofxZLw4gNU)

windows运行结果正常

**Comment by chenqifeng6** [comment]
> ![1706554988007](https://private-user-images.githubusercontent.com/154393700/300575419-8e2b3e3e-8a1d-43a6-a94c-d6912f0f3986.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1NTUzNjcsIm5iZiI6MTcwNjU1NTA2NywicGF0aCI6Ii8xNTQzOTM3MDAvMzAwNTc1NDE5LThlMmIzZTNlLThhMWQtNDNhNi1hOTRjLWQ2OTEyZjBmMzk4Ni5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyOVQxOTA0MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMWQ3NTA2NTgzZDUxYzIyMzA5ZWE3NDQxYzZmNDk5YmJlN2NmODljZTMxYTNkMWU1OTc1YzA5NTg1N2ExMTFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ECzocN2hNZpsbffKJwEo-WDad8zw4Oi5uofxZLw4gNU)

docker容器报错了

**Comment by ihmily** [comment]
拉取最新的镜像试试，最新的2.0.9

**Comment by chenqifeng6** [comment]
> 拉取最新的镜像试试，最新的2.0.9

![image](https://github.com/ihmily/DouyinLiveRecorder/assets/154393700/fe7b3bd6-14ec-45dc-9b4a-c283d3fda6f6)
用最新版的2.0.9 OK 啦，感谢大佬！
