### ISSUE TITLE
如何在未开播前，得知直播间号码

### ISSUE THREAD

**Issue by shimiaoyerin** [ihmily/DouyinLiveRecorder#157]
因为抖音有时候有些直播非常的随缘，一直蹲不到，或者有很多个都要蹲，能不能在未开播的情况下知道直播间号码？或者，做成监测首页有没有在直播是不是更好的思路？我不太清楚这其中有什么技术难题，我感觉这或许是最好的方法

**Comment by shimiaoyerin** [comment]
> 因为抖音有时候有些直播非常的随缘，一直蹲不到，或者有很多个都要蹲，能不能在未开播的情况下知道直播间号码？或者，做成监测首页有没有在直播是不是更好的思路？我不太清楚这其中有什么技术难题，我感觉这或许是最好的方法

**Comment by ilikeulinux** [comment]
兄弟，您找到方法了吗？我也为这事苦恼。

**Comment by a809472324** [comment]
蹲后续,目前的确没有优雅的解决方案

**Comment by shimiaoyerin** [comment]
> 兄弟，您找到方法了吗？我也为这事苦恼。

有一个方法，但是并不是万能的，只适合有点粉丝量的主播，就是用“飞瓜数据”，它会抓取到主播近一个月开播的直播间数据，可以通过它来找到直播间房间号码，但是如果没开播过就不能得知直播间

**Comment by ihmily** [comment]
1、嗯，据我所知，主播在未开播前是无法获取直播间ID的

2、如果不想通过直播间地址录制，其实通过作者主页地址也是可以获取到直播间房间号的，不过前提也是要主播正在直播时才可以通过作者主页地址获取房间号，但是可以在程序内进行循环监测，这样就可以不用在主播开播才能录制了，只需要输入作者主页地址就可以开启监测并录制。

**Comment by bitA23187** [comment]
抖音直播的链接，形如：https://live.douyin.com/67471834975，最后的为直播room_id，其实就是该主播的**抖音号**，可以在该主播的主页获取

**Comment by a809472324** [comment]
> 抖音直播的链接，形如：https://live.douyin.com/67471834975 ，最后的为直播room_id，其实就是该主播的**抖音号**，可以在该主播的主页获取

原来就是主播的short_id啊,了解了
