### ISSUE TITLE
关于为不同平台配置是否启用代理，以及对不同代理配置不同代理地址的建议

### ISSUE THREAD

**Issue by xueli12** [ihmily/DouyinLiveRecorder#162]
如果程序能够针对每个平台是否启用代理以及自己定义代理地址对用户更为友好。建议在配置文件中可以让用户自己填每个平台的代理设置，而不是全局设置。
对于墙内用户：
比如pandalive用代理http://127.0.0.1：7890 
非洲台用http://127.0.0.1:10809
虎牙不开启代理。

对于身在墙外的用户:
虎牙：开启代理http://127.0.0.1：7890 
非洲台和pandalive不开启代理

**Comment by ihmily** [comment]
现在只针对tiktok、afreecatv、pandatv这些需要翻墙访问的平台开启代理，因此配置的代理地址只对这些平台生效，至于其他平台，考虑到使用人员几乎都在国内，也无需设置代理。
