### ISSUE TITLE
Afreeca平台的cookie有有效期，建议增加通过账号密码登录获取cookie以作备用

### ISSUE THREAD

**Issue by xueli12** [ihmily/DouyinLiveRecorder#163]
AfreecaTV在录制时，有个问题就是从网页获取的cookie可能过几天就会失效了，导致无法使用。
但是我发现这个平台在登录时没有验证码，也没有其他检测。

因此感觉可能可以用登录的方式直接获取cookie，然后用这个cookie来获取直播流。
因此建议增加上述获取cookie的方式以作备用，我看到已经有人在前面提过自动化登录获取cookie并已经写了脚本

https://github.com/ihmily/DouyinLiveRecorder/issues/137

**Comment by ihmily** [comment]
不太想使用selenium、playwright等自动化框架，使用还必须要安装相应浏览器和对应版本浏览器驱动，使程序显得非常臃肿。对于普通用户的话，一般也不会去安装对应浏览器和找相应版本的浏览器驱动。

**Comment by xueli12** [comment]
> 不太想使用selenium、playwright等自动化框架，使用还必须要安装相应浏览器和对应版本浏览器驱动，使程序显得非常臃肿。对于普通用户的话，一般也不会去安装对应浏览器和找相应版本的浏览器驱动。

selenium确实麻烦，那直接用request.post的方法呢？

**Comment by xueli12** [comment]
> 不太想使用selenium、playwright等自动化框架，使用还必须要安装相应浏览器和对应版本浏览器驱动，使程序显得非常臃肿。对于普通用户的话，一般也不会去安装对应浏览器和找相应版本的浏览器驱动。

biliup的方法：https://github.com/biliup/biliup/blob/master/biliup/plugins/afreecaTV.py

**Comment by ihmily** [comment]
已新增账号登录
