### ISSUE TITLE
pandatv录制结束，download找不到视频文件，或者乱码视频文件，非常卡顿，并且不完整，

### ISSUE THREAD

**Issue by hsvshxjs** [ihmily/DouyinLiveRecorder#166]
pandatv录制结束，download找不到视频文件，或者乱码视频文件，非常卡顿，并且不完整，

**Comment by hsvshxjs** [comment]
> pandatv19+录制结束，download找不到视频文件，或者乱码视频文件，非常卡顿，并且不完整，自己已经添加cookie，本地开启代理

**Comment by ihmily** [comment]
网络问题，请更换网速快的代理。

**Comment by hsvshxjs** [comment]
> 网络问题，请更换网速快的代理。

但是我观看直播没一点卡顿啊，录制就特别卡，是不是要在副本里添加本地代理？

**Comment by hsvshxjs** [comment]
我录的是panda19+频道，登录账号也添加cookie，现在能录制了，但是很不稳定，我的网络正常观看直播没一点卡顿，但是就是录制的视频很卡，那种快进的卡，文件很小，有的直接找不到文件



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年2月9日(周五) 凌晨5:18
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ihmily/DouyinLiveRecorder] pandatv录制结束，download找不到视频文件，或者乱码视频文件，非常卡顿，并且不完整， (Issue #166)




 
网络问题，请更换网速快的代理。

**Comment by N83R7** [comment]
同样的问题。
查看了录制出来的视频信息，是这样的：

General
ID                             : 1 (0x1)
Complete name                  : 안나ღANNAღ_2024-02-16_11-23-03.ts
Format                         : MPEG-TS
File size                      : 3.91 MiB
Duration                       : 7 s 849 ms
Overall bit rate mode          : Variable
Overall bit rate               : 3 254 kb/s

Video #1
ID                             : 257 (0x101)
Menu ID                        : 1 (0x1)
Format                         : AVC
Format/Info                    : Advanced Video Codec
Format profile                 : Main@L3.1
Format settings                : CABAC / 2 Ref Frames
Format settings, CABAC         : Yes
Format settings, Reference fra : 2 frames
Codec ID                       : 27
Duration                       : 7 s 866 ms
Bit rate mode                  : Constant
Nominal bit rate               : 2 099 kb/s
Width                          : 720 pixels
Height                         : 1 280 pixels
Display aspect ratio           : 0.563
Frame rate                     : 30.000 FPS
Standard                       : NTSC
Color space                    : YUV
Chroma subsampling             : 4:2:0
Bit depth                      : 8 bits
Scan type                      : Progressive
Bits/(Pixel*Frame)             : 0.076
Color range                    : Limited
Color primaries                : BT.601 PAL
Transfer characteristics       : BT.601
Matrix coefficients            : BT.601

Video #2
ID                             : 259 (0x103)
Menu ID                        : 1 (0x1)
Format                         : AVC
Format/Info                    : Advanced Video Codec
Format profile                 : Main@L3.1
Format settings                : CABAC / 2 Ref Frames
Format settings, CABAC         : Yes
Format settings, Reference fra : 2 frames
Codec ID                       : 27
Duration                       : 12 s 905 ms
Bit rate mode                  : Constant
Nominal bit rate               : 1 199 kb/s
Width                          : 480 pixels
Height                         : 852 pixels
Display aspect ratio           : 0.563
Frame rate                     : 30.000 FPS
Standard                       : NTSC
Color space                    : YUV
Chroma subsampling             : 4:2:0
Bit depth                      : 8 bits
Scan type                      : Progressive
Bits/(Pixel*Frame)             : 0.098
Color range                    : Limited
Color primaries                : BT.601 PAL
Transfer characteristics       : BT.601
Matrix coefficients            : BT.601

Video #3
ID                             : 261 (0x105)
Menu ID                        : 1 (0x1)
Format                         : AVC
Format/Info                    : Advanced Video Codec
Format profile                 : Main@L3
Format settings                : CABAC / 2 Ref Frames
Format settings, CABAC         : Yes
Format settings, Reference fra : 2 frames
Codec ID                       : 27
Duration                       : 12 s 863 ms
Bit rate mode                  : Constant
Nominal bit rate               : 565 kb/s
Width                          : 360 pixels
Height                         : 640 pixels
Display aspect ratio           : 0.563
Frame rate                     : 30.000 FPS
Standard                       : NTSC
Color space                    : YUV
Chroma subsampling             : 4:2:0
Bit depth                      : 8 bits
Scan type                      : Progressive
Bits/(Pixel*Frame)             : 0.082
Color range                    : Limited
Color primaries                : BT.601 PAL
Transfer characteristics       : BT.601
Matrix coefficients            : BT.601

Video #4
ID                             : 263 (0x107)
Menu ID                        : 1 (0x1)
Format                         : AVC
Format/Info                    : Advanced Video Codec
Format profile                 : Main@L1.2
Format settings                : CABAC / 2 Ref Frames
Format settings, CABAC         : Yes
Format settings, Reference fra : 2 frames
Codec ID                       : 27
Duration                       : 6 s 892 ms
Bit rate mode                  : Constant
Nominal bit rate               : 181 kb/s
Width                          : 160 pixels
Height                         : 284 pixels
Display aspect ratio           : 0.563
Frame rate                     : 30.000 FPS
Standard                       : NTSC
Color space                    : YUV
Chroma subsampling             : 4:2:0
Bit depth                      : 8 bits
Scan type                      : Progressive
Bits/(Pixel*Frame)             : 0.133
Color range                    : Limited
Color primaries                : BT.601 PAL
Transfer characteristics       : BT.601
Matrix coefficients            : BT.601

Audio #1
ID                             : 256 (0x100)
Menu ID                        : 1 (0x1)
Format                         : AAC LC
Format/Info                    : Advanced Audio Codec Low Complexity
Format version                 : Version 4
Muxing mode                    : ADTS
Codec ID                       : 15-2
Duration                       : 7 s 825 ms
Bit rate mode                  : Variable
Channel(s)                     : 2 channels
Channel layout                 : L R
Sampling rate                  : 44.1 kHz
Frame rate                     : 43.066 FPS (1024 SPF)
Compression mode               : Lossy
Delay relative to video        : 17 ms

Audio #2
ID                             : 258 (0x102)
Menu ID                        : 1 (0x1)
Format                         : AAC LC
Format/Info                    : Advanced Audio Codec Low Complexity
Format version                 : Version 4
Muxing mode                    : ADTS
Codec ID                       : 15-2
Duration                       : 12 s 910 ms
Bit rate mode                  : Variable
Channel(s)                     : 2 channels
Channel layout                 : L R
Sampling rate                  : 44.1 kHz
Frame rate                     : 43.066 FPS (1024 SPF)
Compression mode               : Lossy
Delay relative to video        : 1 s 990 ms

Audio #3
ID                             : 260 (0x104)
Menu ID                        : 1 (0x1)
Format                         : AAC LC
Format/Info                    : Advanced Audio Codec Low Complexity
Format version                 : Version 4
Muxing mode                    : ADTS
Codec ID                       : 15-2
Duration                       : 12 s 724 ms
Bit rate mode                  : Variable
Channel(s)                     : 2 channels
Channel layout                 : L R
Sampling rate                  : 44.1 kHz
Frame rate                     : 43.066 FPS (1024 SPF)
Compression mode               : Lossy
Delay relative to video        : 9 s 26 ms

Audio #4
ID                             : 262 (0x106)
Menu ID                        : 1 (0x1)
Format                         : AAC LC
Format/Info                    : Advanced Audio Codec Low Complexity
Format version                 : Version 4
Muxing mode                    : ADTS
Codec ID                       : 15-2
Duration                       : 6 s 687 ms
Bit rate mode                  : Variable
Channel(s)                     : 2 channels
Channel layout                 : L R
Sampling rate                  : 44.1 kHz
Frame rate                     : 43.066 FPS (1024 SPF)
Compression mode               : Lossy
Delay relative to video        : 20 s 55 ms

Menu
ID                             : 4096 (0x1000)
Menu ID                        : 1 (0x1)
Duration                       : 7 s 849 ms
List                           : 256 (0x100) (AAC) / 257 (0x101) (AVC) / 258 (0x102) (AAC) / 259 (0x103) (AVC) / 260 (0x104) (AAC) / 261 (0x105) (AVC) / 262 (0x106) (AAC) / 263 (0x107) (AVC)
Service name                   : Service01
Service provider               : FFmpeg
Service type                   : digital television
