### ISSUE TITLE
如果能尽快支持录制flextv（韩国)）直播录制就太好了

### ISSUE THREAD

**Issue by 1959094954** [ihmily/DouyinLiveRecorder#167]

**Comment by ilikeulinux** [comment]
是https://www.flextv.co.kr/这个平台吗？

**Comment by xueli12** [comment]
> 是https://www.flextv.co.kr/ 这个平台吗？

对

**Comment by 1959094954** [comment]
> 是https://www.flextv.co.kr/ 这个平台吗？

是的

**Comment by hsvshxjs** [comment]
> 是https://www.flextv.co.kr/ 这个平台吗？

期待这个平台！

**Comment by ihmily** [comment]
@1959094954 已支持flextv https://github.com/ihmily/DouyinLiveRecorder/releases/tag/v3.0.2

**Comment by 1959094954** [comment]
> @1959094954已支持flextv https://github.com/ihmily/DouyinLiveRecorder/releases/tag/v3.0.2

大佬666，非常感谢！
