### ISSUE TITLE
Afreecatv录制不了，求解决。

### ISSUE THREAD

**Issue by clarewz** [ihmily/DouyinLiveRecorder#169]
用的梯子是白鲸，代理地址应该没填错吧。
![JN1`Y%RMECX_{4E{3S1%X L](https://github.com/ihmily/DouyinLiveRecorder/assets/39951412/1f5257b0-830c-4240-b5c2-f8b8537d93aa)

![C@$DX7G}NAC`R%%5CM { 3X](https://github.com/ihmily/DouyinLiveRecorder/assets/39951412/b0dea0d1-cf13-482c-a297-c07b25461858)
但是报错了，求大佬看看是什么问题
![U`N%P{M$JJ5)VMFNL7ECZK4](https://github.com/ihmily/DouyinLiveRecorder/assets/39951412/1668646c-a7db-447e-aa9d-3e0e2a09b784)

**Comment by clarewz** [comment]
报错信息在上面，求大佬看看什么问题

**Comment by ilikeulinux** [comment]
代理地址的前面少了一个空格，也就是说=后面差一个空格

**Comment by ihmily** [comment]
@clarewz 请求超时了，代理网络的问题，检查一下该软件监听的端口是否正确，不然就是代理网速过慢
