### ISSUE TITLE
您好。winktv直播平台可以考虑加入支持吗？

### ISSUE THREAD

**Issue by c5110** [ihmily/DouyinLiveRecorder#177]
请问大佬有空添加一个新的支持吗？主播质量比较高，可以提供认证账号用于测试使用。
https://www.winktv.co.kr/

**Comment by ihmily** [comment]
最新版 [v3.0.2](https://github.com/ihmily/DouyinLiveRecorder/releases/tag/v3.0.2) 已新增winktv录制
