### ISSUE TITLE
不在main.py所在目录运行就无法获取内容

### ISSUE THREAD

**Issue by Karmylr** [ihmily/DouyinLiveRecorder#178]
在main.py所在目录里运行：
> ![image](https://github.com/ihmily/DouyinLiveRecorder/assets/69903376/8da17b15-b790-49d3-a46f-3dd6180f22cf)

不在main.py所在目录里运行：
> ![image](https://github.com/ihmily/DouyinLiveRecorder/assets/69903376/4dc0805f-e8cb-4128-b66a-6df9a77a2ef2)

**Comment by ihmily** [comment]
其他直播间也会这样吗？我用CentOS测试是正常的
![image](https://github.com/ihmily/DouyinLiveRecorder/assets/114978440/db384264-4743-4c62-a27a-a71c5890bd03)

**Comment by Karmylr** [comment]
> 其他直播间也会这样吗？我用CentOS测试是正常的 ![image](https://private-user-images.githubusercontent.com/114978440/305684401-db384264-4743-4c62-a27a-a71c5890bd03.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMjUzODgsIm5iZiI6MTcwOTEyNTA4OCwicGF0aCI6Ii8xMTQ5Nzg0NDAvMzA1Njg0NDAxLWRiMzg0MjY0LTQ3NDMtNGM2Mi1hMjdhLWE3MWM1ODkwYmQwMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyOFQxMjU4MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wM2Q5NDkyZjI3NzVjMWEyMjFlY2QxZTk3MWY2NGNkOTgyYTY2YWU3NzQ2NmZkZjJhZDE4OWE4NmYwN2IxZjNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.69qMEV6DiRw9OnWicemlwnvo5vWlMmgkPr2Py6wKRLU)

其他直播间也会这样
