### ISSUE TITLE
Tiktok好像录不了，链接导入后刷一下就没了

### ISSUE THREAD

**Issue by ohiu** [ihmily/DouyinLiveRecorder#179]

**Comment by ihmily** [comment]
有报错信息吗？是否是网络问题呢？我测试是正常录制的。

如下图：
![image](https://github.com/ihmily/DouyinLiveRecorder/assets/114978440/04d72bb7-6296-49ac-8053-6b805aa09405)

注： 香港网络无法访问Tiktok

**Comment by ohiu** [comment]
<img width="1157" alt="Screenshot 2024-02-19 at 19 44 02" src="https://github.com/ihmily/DouyinLiveRecorder/assets/38372917/807ae76a-b424-435b-b057-38ef5e059720">

**Comment by ihmily** [comment]
你截图中的地址，在我这是正常录制的。
https://www.tiktok.com/@9th12n02/live

![image](https://github.com/ihmily/DouyinLiveRecorder/assets/114978440/1f2d3a39-16a9-4e84-8693-d61d88c18043)

你大概是是代理网络的问题

**Comment by ihmily** [comment]
B站录制出错的原因有可能是 **内置的B站默认cookie失效**，你可以在config配置文件中给B站配一个cookie，如填写 `bilibili.com`就不会用到内置cookie了，这样可以正常录制（下次更新我会将其内置cookie去除）

如下图
![1708343134609](https://github.com/ihmily/DouyinLiveRecorder/assets/114978440/68a1387a-be42-426b-a1d4-a350ac10e2a7)

![image](https://github.com/ihmily/DouyinLiveRecorder/assets/114978440/04682093-717c-4e43-be48-9532d6328ee2)

**Comment by ohiu** [comment]
> 你截图中的地址，在我这是正常录制的。 https://www.tiktok.com/@9th12n02/live
> 
> ![image](https://private-user-images.githubusercontent.com/114978440/305935093-1f2d3a39-16a9-4e84-8693-d61d88c18043.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzNDY5NzUsIm5iZiI6MTcwODM0NjY3NSwicGF0aCI6Ii8xMTQ5Nzg0NDAvMzA1OTM1MDkzLTFmMmQzYTM5LTE2YTktNGU4NC04NjkzLWQ2MWQ4OGMxODA0My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxOVQxMjQ0MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jOWFmZDU3ZmU2N2RlNDVjNzJjNmFmMDIyZWY0MzQ0OTYzNmFkNDNmY2UyMjU0MjI3OWNkYzVjY2MxOGViNWZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nhBReKnCa4qi7RbNm9I9ciGxQWPP-5s9i5l37Bp-X0I)
> 
> 你大概是是代理网络的问题

tiktok的问题确实启用代理IP就解决了，但是是什么原理呢，我只是把否改成了是，并没有添加任何其他的东西

**Comment by ihmily** [comment]
> tiktok的问题确实启用代理IP就解决了，但是是什么原理呢，我只是把否改成了是，并没有添加任何其他的东西

你能访问tiktok说明使用了代理，至于你开启后什么也没设置就能录制，是因为你的代理支持自动分流，对于需要翻墙的网站会主动通过你使用的代理去访问，但是如果你把配置文件中的代理开启设置为否，代码内部逻辑严格不会通过你的代理去请求tiktok，因此之前你无法访问tiktok导致无法获取内容。

![image](https://github.com/ihmily/DouyinLiveRecorder/assets/114978440/03656425-7ed0-413b-bbb9-6b575c98e55c)

**1这里要显示已开启代理，2代理配置为启用，这两个是国内录制海外平台的前置条件。**

**Comment by ohiu** [comment]
> > tiktok的问题确实启用代理IP就解决了，但是是什么原理呢，我只是把否改成了是，并没有添加任何其他的东西
> 
> 你能访问tiktok说明使用了代理，至于你开启后什么也没设置就能录制，是因为你的代理支持自动分流，对于需要翻墙的网站会主动通过你使用的代理去访问，但是如果你把配置文件中的代理开启设置为否，代码内部逻辑严格不会通过你的代理去请求tiktok，因此之前你无法访问tiktok导致无法获取内容。
> 
> ![image](https://private-user-images.githubusercontent.com/114978440/305958290-03656425-7ed0-413b-bbb9-6b575c98e55c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzNDkxOTgsIm5iZiI6MTcwODM0ODg5OCwicGF0aCI6Ii8xMTQ5Nzg0NDAvMzA1OTU4MjkwLTAzNjU2NDI1LTdlZDAtNDEzYi1iYmI5LTZiNTc1Yzk4ZTU1Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxOVQxMzIxMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01M2VmOGE5MTFkMWNiZjI1MzZjNzIyNTdiNDkyZjRiZDEzZDY4ZjdkNDZhNWZhM2EzNmIzOThiZTRkN2VlMTE1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.eMVlR6hESE62Or9geb32VkL7UqzSE6CiqtO1asBjiaw)
> 
> **1这里要显示已开启代理，2代理配置为启用，这两个是国内录制海外平台的前置条件。**

1这里是自动监测能否访问外网的吗，因为我直接挂在境外服务器上的，所以默认它就显示全局/规则网络代理已开启，然而如果此时配置文件设置代理IP为否的话，就不能录制tiktok,如果两个都是是的话，在境外服务器上才能录制tiktok。

**Comment by ihmily** [comment]
>1这里是自动监测能否访问外网的吗，因为我直接挂在境外服务器上的，所以默认它就显示全局/规则网络代理已开启，然而如果此时配置文件设置代理IP为否的话，就不能录制tiktok,如果两个都是是的话，在境外服务器上才能录制tiktok。

对的，不过现在感觉那个开关有些多余，下个版本准备取消这个开关选项。

**Comment by xueli12** [comment]
> > 1这里是自动监测能否访问外网的吗，因为我直接挂在境外服务器上的，所以默认它就显示全局/规则网络代理已开启，然而如果此时配置文件设置代理IP为否的话，就不能录制tiktok,如果两个都是是的话，在境外服务器上才能录制tiktok。
> 
> 对的，不过现在感觉那个开关有些多余，下个版本准备取消这个开关选项。

大大，不建议取消哇，对于我们国内用户来说，如果取消的话我们就必须开启系统代理才能下载了
