### ISSUE TITLE
你好表哥，可以加一个检测到开播然后钉钉通知吗

### ISSUE THREAD

**Issue by Philae994** [ihmily/DouyinLiveRecorder#18]
非常感谢

**Comment by ihmily** [comment]
表弟已经给你加上了
![image](https://github.com/ihmily/DouyinLiveRecorder/assets/114978440/0a0fe029-9790-4c13-9f6e-25f5d5057f97)

**Comment by Philae994** [comment]
> 表弟已经给你加上了 ![image](https://user-images.githubusercontent.com/114978440/265267305-0a0fe029-9790-4c13-9f6e-25f5d5057f97.png)

非常感谢
