### ISSUE TITLE
录制失败

### ISSUE THREAD

**Issue by Rookie-2333** [ihmily/DouyinLiveRecorder#180]
1. 主播名称中含有“.”会导致录制失败，应该是由于Windows下文件夹命名失败的原因。
2. 主播名称中含有“u”会被替换为“_”。
3. 自定义（重命名）主播名有时候会失效，这个貌似是在第二次录制同一个主播时出现。

**Comment by ihmily** [comment]
2确实是这样，被过滤字符替换掉了
至于1和3，1经测试能正常录制，3未能重现

**Comment by ihmily** [comment]
原：`https://live.douyin.com/199472281167,主播: UU`

修改后：`https://live.douyin.com/199472281167,主播: 修改后UU`

显示名称：修改后UU

注意：修改名字的时候 `主播: ` 这个不能去除，要保留
