### ISSUE TITLE
希望能够支持录制popkontv（韩国)直播录制

### ISSUE THREAD

**Issue by xueli12** [ihmily/DouyinLiveRecorder#183]
大大，希望可以将这个直播网站加入录制列表https://www.popkontv.com/
如需账号我可以提供
辛苦大大

**Comment by xueli12** [comment]
https://www.popkontv.com/ 作者大大和各位开发大佬好，ponkontv在获取直播流时的请求头中需要加入authorization，好像是要在用账户密码登录后才会发放这个获取直播流的authorization，我用cookie方式登录不知道如何获取。

但是我在登录时遇到一个问题，在登录时会有如下面的一个base 开头的授权头，这个授权头貌似是js生成的，我换了几个浏览器和换了不同电脑 这个base开头的授权头都是一样，不知道是如何生成的，虽说现在可以用这个base开头的授权头来登录，因此想请教各位。
![image](https://github.com/ihmily/DouyinLiveRecorder/assets/51438016/5654e256-0a50-4fdf-939a-04ab0c6bbc2d)

**Comment by ihmily** [comment]
最新版 [v3.0.2](https://github.com/ihmily/DouyinLiveRecorder/releases/tag/v3.0.2) 已新增popkontv录制
