### ISSUE TITLE
希望能够对海外直播pandalive、afreeca等直播的文件名中加入主播id

### ISSUE THREAD

**Issue by xueli12** [ihmily/DouyinLiveRecorder#185]
大大，现在录制afreeca的直播（https://play.afreecatv.com/alswl2208）
时，文件名的保存是韩文主播名称+时间，韩文主播名称可能随时都会变化，而且在google检索时也一般用主播id来检索，希望录制pandalive、afreeca等直播时能够在文件名中加入主播id，比如：alswl2208，或者让用户在填写配置文件名时可以自定义主播名称
再次感谢大大的无私奉献

**Comment by ihmily** [comment]
3.0.2版本已添加
