### ISSUE TITLE
小红书换了新的域名,录制失败

### ISSUE THREAD

**Issue by vipzrx** [ihmily/DouyinLiveRecorder#190]
使用最新版本 v3.0.1-beta
测试连接:

按照指导说明,先分享到微信,在微信打开,复制地址
https://www.xiaohongshu.com/hina/livestream/569097167492211122/1708580340730?share_source=liveRoom&share_source_id=&source=share_out_of_app&host_id=602f427300000000010003af&xhsshare=WeixinSession&appuid=65b5e292000000000d01c8c0&apptime=1708580341

启动软件,复制地址,提示:
```
-----------------------------------------------------
|                DouyinLiveRecorder                 |
-----------------------------------------------------
版本号：v3.0.1-beta
Github：https://github.com/ihmily/DouyinLiveRecorder
支持平台：抖音|TikTok|快手|虎牙|斗鱼|YY|B站|小红书|bigo直播|blued直播|AfreecaTV|网易CC|千度热播|pandaTV|猫耳FM
.....................................................
系统代理检测中，请耐心等待...
INFO：未检测到全局/规则网络代理，请检查代理配置（若无需录制TikTok/AfreecaTV直播请忽略此条提示）
请输入要录制的主播直播间网址（尽量使用PC网页端的直播间地址）:
https://www.xiaohongshu.com/hina/livestream/569097167492211122/1708580340730?share_source=liveRoom&share_source_id=&source=share_out_of_app&host_id=602f427300000000010003af&xhsshare=WeixinSession&appuid=65b5e292000000000d01c8c0&apptime=1708580341
https://www.xiaohongshu.com/hina/livestream/569097167492211122/1708580340730?share_source=liveRoom&share_source_id=&source=share_out_of_app&host_id=602f427300000000010003af&xhsshare=WeixinSession&appuid=65b5e292000000000d01c8c0&apptime=1708580341 未知链接.此条跳过
```

共监测0个直播中 | 同一时间访问网络的线程数: 3 | 是否开启代理录制: 是 | 是否生成时间文件: 否 | 录制视频质量为: 原画 | 录 制视频格式为: MP4 | 目前瞬时错误数为: 0 | 当前时间: 2024-02-22 13:42:10

**Comment by ihmily** [comment]
额，上次换了域名现在又换回来原来的域名了。下个版本修复

**Comment by vipzrx** [comment]
哪个历史版本可以用？
发自我的 iPhone

在 2024年2月22日，14:11，Hmily ***@***.***> 写道：

﻿

额，上次换了域名现在又换回来原来的域名了。下个版本修复

**Comment by ihmily** [comment]
虽然域名改为原来的了，但因为和之前地址新增了一串数字，所以需要修改一下输入的直播间地址才能使用旧版本录制。

你上面的小红书地址
```
https://www.xiaohongshu.com/hina/livestream/569097167492211122/1708580340730?share_source=liveRoom&share_source_id=&source=share_out_of_app&host_id=602f427300000000010003af&xhsshare=WeixinSession&appuid=65b5e292000000000d01c8c0&apptime=1708580341
```
把链接中 `?` 前面的`/1708580340730` 斜杠和这段数字去掉，如下
```
https://www.xiaohongshu.com/hina/livestream/569097167492211122?share_source=liveRoom&share_source_id=&source=share_out_of_app&host_id=602f427300000000010003af&xhsshare=WeixinSession&appuid=65b5e292000000000d01c8c0&apptime=1708580341
```
这样修改地址后，使用上个版本2.0.9 就可以正常录制。

**Comment by vipzrx** [comment]
按照提示修改可以正常录制.感谢

发自我的 iPhone

在 2024年2月22日，18:01，Hmily ***@***.***> 写道：

﻿

虽然域名改为原来的了，但因为和之前地址新增了一串数字，所以需要修改一下输入的直播间地址才能使用旧版本录制。

你上面的小红书地址

https://www.xiaohongshu.com/hina/livestream/569097167492211122/1708580340730?share_source=liveRoom&share_source_id=&source=share_out_of_app&host_id=602f427300000000010003af&xhsshare=WeixinSession&appuid=65b5e292000000000d01c8c0&apptime=1708580341


把链接中 ? 前面的/1708580340730 斜杠和这段数字去掉，如下

https://www.xiaohongshu.com/hina/livestream/569097167492211122?share_source=liveRoom&share_source_id=&source=share_out_of_app&host_id=602f427300000000010003af&xhsshare=WeixinSession&appuid=65b5e292000000000d01c8c0&apptime=1708580341


这样修改地址后，使用上个版本2.0.9 就可以正常录制。

**Comment by ihmily** [comment]
其实3.0.1版本的也可以录制，而且更简单，只需要把直播间地址中的 www.xiaohongshu.com 替换成 www.redelight.cn 即可

**Comment by ihmily** [comment]
最新版 [v3.0.2](https://github.com/ihmily/DouyinLiveRecorder/releases/tag/v3.0.2) 已修复以上问题
