### ISSUE TITLE
popkontv如何根据主播id获取正确的直播间地址

### ISSUE THREAD

**Issue by xueli12** [ihmily/DouyinLiveRecorder#194]
### 直播平台

popkontv

### 需求描述

作者大大好，

我刚开始学python，有些地方不是很明白。

最近在研究popkontv，有个问题一直困扰我，就是没法直接通过主播的id找到直播间地址：
popkontv的直播间地址是类似这样的，大多数partnerCode是P-00001，少部分是P-00074、P-00117这样的，同一个主播的partnerCode可能还会变化，如果这个partnerCode填写不正确无法观看直播，直接请求包含错误的partnerCode的地址或者不填写partnerCode将不会重定向正确的直播间也没法通过源代码看到正确的partnerCode：
https://www.popkontv.com/live/view?castId=162cm&partnerCode=P-00074
https://www.popkontv.com/live/view?castId=epne22&partnerCode=P-00001

如果大大有空的话，可否帮忙看看是否有API可以直接请求主播id获取这个partnerCode，感激不尽
可以提供popkontv账号

**Comment by ihmily** [comment]
麻烦提供一个账号，发至邮箱：ihmily123@iubridge.com

**Comment by xueli12** [comment]
> 麻烦提供一个账号，发至邮箱：[ihmily123@iubridge.com](mailto:ihmily123@iubridge.com)

想到方法了，忘记关issue了，感谢大大

**Comment by xueli12** [comment]
> 麻烦提供一个账号，发至邮箱：[ihmily123@iubridge.com](mailto:ihmily123@iubridge.com)

```python
import json
import requests

# 首先，我们以utf-8的方式从配置文件中获取必要的信息
with open('config3.json', 'r', encoding='utf-8') as f:
    config = json.load(f)

# 将cookie和authorization从配置文件中读取
cookie = config['user'][0]['cookies']
authorization = config['popkontv_authorization']

# 将代理从配置文件中读取
proxy_http = config['proxy']
proxy_https = config['proxy']

# 然后我们设置请求头
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36',
    'Cookie': cookie,
    'Content-Type': 'application/json',
    'Authorization': authorization,
    'ClientKey': 'Client FpAhe6mh8Qtz116OENBmRddbYVirNKasktdXQiuHfm88zRaFydTsFy63tzkdZY0u'}
# 设置提交的参数
payload = json.dumps({
  "partnerCode": "P-00001",
  "searchKeyword": "11",
  "signId": "ghostoppa105"
})
# 设置代理地址
proxies = {
  "http": proxy_http,
  "https": proxy_https,
}
# 发送请求
response = requests.post("https://www.popkontv.com/api/proxy/broadcast/v1/search/all", headers=headers, data=payload, proxies=proxies)

# 打印响应
print("Response body: \n", response.text)

# 打印服务器响应请求头
print("\nServer response headers: \n", response.headers)
```
配置文件格式：
```
{
    "proxy": "http://127.0.0.1:7897",
    "output": "output",
    "popkontv_authorization": "从浏览器中获取",
    "user": [

        {
            "platform": "Popkontv",
            "id": "162cm",
            "name": "162cm",
            "cookies": "从浏览器中获取",
            "username": "",
            "password": "",
            "output": "G:/KBJ/popkontv/162cm",
            "interval": 30
        }
    ]
}
```

**Comment by ihmily** [comment]
请求头用下面这个
```
headers = {
        'Accept': 'application/json, text/plain, */*',
        'Accept-Language': 'zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6',
        'Content-Type': 'application/json',
        'Origin': 'https://www.popkontv.com',
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0',
}
```

获取到的直播源地址无法播放和录制是一个问题，报403应该是有其他鉴权，暂时无法解决。

**Comment by xueli12** [comment]
> 请求头用下面这个
> 
> ```
> headers = {
>         'Accept': 'application/json, text/plain, */*',
>         'Accept-Language': 'zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6',
>         'Content-Type': 'application/json',
>         'Origin': 'https://www.popkontv.com',
>         'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0',
> }
> ```
> 
> 获取到的直播源地址无法播放和录制是一个问题，报403应该是有其他鉴权，暂时无法解决。

哇，大佬！你这个请求头可以

**Comment by xueli12** [comment]
> > 获取到的直播源地址无法播放和录制是一个问题，报403应该是有其他鉴权，暂时无法解决。
> 
> 已解决该问题

大佬，我获取到的直播流还有个问题就是有的流很容易断流，大概下个几十M或者几百M就断了，有的又比较稳定

**Comment by xueli12** [comment]
> 麻烦提供一个账号，发至邮箱：[ihmily123@iubridge.com](mailto:ihmily123@iubridge.com)

大佬我更改了密码，请查收下邮件，新的密码我给你发过去了，以防号商把我的号回收了
