### ISSUE TITLE
求支持 flextv

### ISSUE THREAD

**Issue by Nzybwzy** [ihmily/DouyinLiveRecorder#195]
求支持 flextv

**Comment by ihmily** [comment]
最新版 [v3.0.2](https://github.com/ihmily/DouyinLiveRecorder/releases/tag/v3.0.2) 已新增flextv录制

**Comment by Nzybwzy** [comment]
大佬 录个两分钟左右就会停止不动了 是因为账号没实名的问题吗 没有任何错误日志 是通过twitch登录后 只填写了cookie信息这种方式的

**Comment by ihmily** [comment]
@Nzybwzy 

我是通过配置账号和密码进行录制的，测试了3个直播间录制了一个小时暂未出现你的情况，更有可能是网络的问题。
