### ISSUE TITLE
關於設定檔內幾個設定的一些問題

### ISSUE THREAD

**Issue by Bill-tw** [ihmily/DouyinLiveRecorder#202]
Hi 各位，

對於下面兩個設項不知背後的意思為何想請教一下
﻿謝謝

>[录制设置]
> 同一时间访问网络的线程数 = 3

請問錄製線程數預設是 3, 這個調整為 1 有什麼風險嗎？設定為 3 的好處為何？

> 排队读取网址时间(秒) = 0

請問這個設定該怎麼解讀及有需要調整嗎？

**Comment by ihmily** [comment]
`同一时间访问网络的线程数` 意为 同时发起多少个网络请求，更改为1应该没什么影响。
`排队读取网址时间(秒)`  意为 添加的多个直播间地址时开始加入录制的时间间隔

这两个选项非必要不更改，不需要调整
