### ISSUE TITLE
3.0.1版本录制tiktok直播提示报错717

### ISSUE THREAD

**Issue by wuxiongxiong805** [ihmily/DouyinLiveRecorder#216]
3.0.1版本录制tiktok直播提示报错717

![1709817565647](https://github.com/ihmily/DouyinLiveRecorder/assets/141489071/4915b814-ae29-4500-8cd2-d83d33a87477)

**Comment by ihmily** [comment]
网络连接不正常，提示无法连接到代理网络，请你检查一下代理设置
