### ISSUE TITLE
3.0.2版本虎牙检测不到

### ISSUE THREAD

**Issue by aYu-asd** [ihmily/DouyinLiveRecorder#219]

**Comment by ihmily** [comment]
运行界面能截一下图吗？或者直播间地址发一下

**Comment by aYu-asd** [comment]
https://www.huya.com/16922642
https://www.huya.com/584260
试了两个都不行
![image](https://github.com/ihmily/DouyinLiveRecorder/assets/112919747/ff6f783e-8db0-472a-a47f-d8917e0d3aaa)

**Comment by ihmily** [comment]
**运行的时候有报错吗？我这能正常检测到和录制的**

![image](https://github.com/ihmily/DouyinLiveRecorder/assets/114978440/8ac12fe7-9507-41ef-b86d-dde33b9ccd44)

**Comment by aYu-asd** [comment]
没报错，log文件0字节，上个版本会报错

**Comment by aYu-asd** [comment]
重启了一下，现在报错了
2024-03-11 05:02:18.201 | WARNING  | utils:wrapper:18 - 错误信息: type: KeyError, 'sphdcdn' in function get_huya_stream_url at line: 447
2024-03-11 05:02:18.201 | WARNING  | __main__:start_record:1284 - 错误信息: 'list' object has no attribute 'get' 发生错误的行数: 907

**Comment by ihmily** [comment]
试一下刚更新的3.0.2修复版 https://github.com/ihmily/DouyinLiveRecorder/releases/tag/v3.0.2

**Comment by aYu-asd** [comment]
还是不行，这下又没有报错了

**Comment by ihmily** [comment]
那就奇怪了，其他平台可以正常录制吗？我测试了两个机器都是可以正常录制虎牙的

**Comment by aYu-asd** [comment]
现在好了，又可以了。
