### ISSUE TITLE
3.0.2新版本的几个小疑问。

### ISSUE THREAD

**Issue by douying2334** [ihmily/DouyinLiveRecorder#220]
1.请问可以直接用3.0.1版本的config文件夹替换到3.0.2版本吗 免得重新设置
2.视频分段录制理论上会不会造成视频不连贯呀，比如分段录制会不会有间隔还是说瞬间的分段瞬间自动录制 合并会完整不会卡顿？ （因为有时发现比如设置分段180s 结果视频有的是3分钟有的2.58分钟 有的2.59分钟）
3,请问怎么设置视频ts分段录制后 ，自动合并成ts

4.小建议  ，开始录制，但是录制中途有时候会提前显示录制完成，但实际主播还在直播，这个时候很多情况是主播卡顿 换网络，官方断开等等原因，请问怎么设置 这种突然断开后就瞬间自动重新连接 ，而不是等待软件循环时间监控间隔到了再重新连接，比如设置120s监控间隔  ，意外录制断开就马上连接而不是等120s后监控到再连接录制

**Comment by ihmily** [comment]
1、正常可以直接替换，3.0.2版本新增的配置选项会自动在你原有的config文件中生成

2、一般不会卡顿，分段完全是由ffmpeg实现的，在录制的过程中分割时不会停止录制，几乎是瞬时的，除非网络延迟很大，至于时间不准确180s，这个也由ffmpeg决定，其实只要视频画面能连贯就问题不大。

3、`请问怎么设置视频ts分段录制后 ，自动合并成ts` 设置了分段后又要合并？**那关闭分段选项就好了**，有点不大理解你的需求。如果非要这样操作，可以自己使用ffmpeg命令也可以简单方便的进行合并。

4、这个我会考虑，计划下个版本进行优化

**Comment by douying2334** [comment]
> 1、正常可以直接替换，3.0.2版本新增的配置选项会自动在你原有的config文件中生成
> 
> 2、一般不会卡顿，分段完全是由ffmpeg实现的，在录制的过程中分割时不会停止录制，几乎是瞬时的，除非网络延迟很大，至于时间不准确180s，这个也由ffmpeg决定，其实只要视频画面能连贯就问题不大。
> 
> 3、`请问怎么设置视频ts分段录制后 ，自动合并成ts` 设置了分段后又要合并？**那关闭分段选项就好了**，有点不大理解你的需求。如果非要这样操作，可以自己使用ffmpeg命令也可以简单方便的进行合并。
> 
> 4、这个我会考虑，计划下个版本进行优化

谢谢详细解释。 
3.是这样的  因为抖音录制有个很常见的bug就是 如果主播切换清晰度或者换网络，或者其他未知原因，就会导致在卡顿，主播切换清晰度那个时间点后出现花屏，哪怕后面长达几个小时的直播视频也都是只有声音，画面全是花屏。为了避免这个情况，就采取了分段录制的方法。

**Comment by elicary894** [comment]
> 1、正常可以直接替换，3.0.2版本新增的配置选项会自动在你原有的config文件中生成
> 
> 2、一般不会卡顿，分段完全是由ffmpeg实现的，在录制的过程中分割时不会停止录制，几乎是瞬时的，除非网络延迟很大，至于时间不准确180s，这个也由ffmpeg决定，其实只要视频画面能连贯就问题不大。
> 
> 3、`请问怎么设置视频ts分段录制后 ，自动合并成ts` 设置了分段后又要合并？**那关闭分段选项就好了**，有点不大理解你的需求。如果非要这样操作，可以自己使用ffmpeg命令也可以简单方便的进行合并。
> 
> 4、这个我会考虑，计划下个版本进行优化

大佬那我把URL_config文件的af直播链接，直接复制在新的版本的URL_config文件里，再运行就网络错误，可是再打开直播间把链接复制到文件里就可以下载，是哪一步的错误呢
