### ISSUE TITLE
请问能增加账号登录功能嘛 比如cookie 或者 账号密码

### ISSUE THREAD

**Issue by Mikosxz** [ihmily/DouyinLiveRecorder#221]
因为有的录制19R需要登录状态

**Comment by ihmily** [comment]
**已经支持账号登录和配置cookie**，可以在config文件夹内的config.ini文件中进行配置，详情请看：

https://github.com/ihmily/DouyinLiveRecorder/blob/01a9094e6aff77357861f0467d8ee09130cbc5e7/config/config.ini#L30C1-L63C17
