### ISSUE TITLE
centos7照教学安装后运行python3 main.py 出现错误

### ISSUE THREAD

**Issue by brina60602** [ihmily/DouyinLiveRecorder#222]
您好 这种要怎么修改？

[root@Vtuber DouyinLiveRecorder]# python3 main.py
Traceback (most recent call last):
  File "main.py", line 31, in <module>
    from spider import (
  File "/home/centos/DouyinLiveRecorder/spider.py", line 863, in <module>
    tuple[str, Any]:
TypeError: 'type' object is not subscriptable

**Comment by matakk** [comment]
好像是 Python 3.8一下的问题
![image](https://github.com/ihmily/DouyinLiveRecorder/assets/6842094/b4999c80-ca88-4b9a-97b5-0f7c58f50e51)
但是我无法使用高版本的.
