### ISSUE TITLE
录制 b 站直播失败，http://live.bilibili.com/25171694 未知直播地址，这个问题怎么解决呀

### ISSUE THREAD

**Issue by zihaoxingstudy1** [ihmily/DouyinLiveRecorder#223]
能录制抖音直播，但是不能正常录制 b 站直播

运行新线程,传入地址 https://live.douyin.com/683226600348
运行新线程,传入地址 http://live.bilibili.com/25171694
2024-03-11 23:39:04.671 | WARNING  | __main__:start_record:897 - http://live.bilibili.com/25171694 未知直播地址

**Comment by ihmily** [comment]
`http://live.bilibili.com/25171694` 改为 `https://live.bilibili.com/25171694`

用https就可以了

**Comment by zihaoxingstudy1** [comment]
> `http://live.bilibili.com/25171694` 改为 `https://live.bilibili.com/25171694`
> 
> 用https就可以了

谢谢啊
