### ISSUE TITLE
af录制的问题

### ISSUE THREAD

**Issue by elicary894** [ihmily/DouyinLiveRecorder#225]
2024-03-12 09:42:09.858 | WARNING  | __main__:start_record:1279 - 错误信息: Command '['ffmpeg', '-y', '-v', 'verbose', '-rw_timeout', '30000000', '-loglevel', 'error', '-hide_banner', '-user_agent', 'Mozilla/5.0 (Linux; Android 11; SAMSUNG SM-G973U) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/14.2 Chrome/87.0.4280.141 Mobile Safari/537.36', '-protocol_whitelist', 'rtmp,crypto,file,http,https,tcp,tls,udp,rtp', '-thread_queue_size', '1024', '-analyzeduration', '40000000', '-probesize', '20000000', '-fflags', '+discardcorrupt', '-i', 'http://live-global-cdn-v02.afreecatv.com/live-stmc-39/auth_playlist.m3u8?aid=.A32.7bbT56vyHM9fKZk.FHw9EBu0Cy006vKAI6VBSyR5UqSagE2uM6SOVUQayLg83jnnJyodiNJNsJmbDpQa_d4Aodcex7qwkqrXvDpGKG2_Pu0NtIrDO1fpklu452KlT-LxrfhTyjcPwsFZlR_g', '-bufsize', '15000k', '-sn', '-dn', '-reconnect_delay_max', '60', '-reconnect_streamed', '-reconnect_at_eof', '-max_muxing_queue_size', '2048', '-correct_ts_overflow', '1', '-c:v', 'copy', '-c:a', 'copy', '-map', '0', '-f', 'segment', '-segment_time', '1800', '-segment_format', 'mpegts', '-reset_timestamps', '1', 'C:/Users/10467/Downloads/DouyinLiveRecorder.v3.0.2/DouyinLiveRecorder v3.0.2/DouyinLiveRecorder.v3.0.2/downloads/AfreecaTV/지연e♥/지연e♥_2024-03-12_09-42-04_%03d.ts']' returned non-zero exit status 4294967158. 发生错误的行数: 1275

**Comment by ihmily** [comment]
一直都这样吗？其他直播间会吗

**Comment by elicary894** [comment]
> 一直都这样吗？其他直播间会吗

是的都会

**Comment by ihmily** [comment]
我看你没设置代理地址，你是哪里的网络？网页上能正常观看吗

**Comment by elicary894** [comment]
> 我看你没设置代理地址，你是哪里的网络？网页上能正常观看吗

我设置了代理啊，网页上可以观看，以前都可以录的，就昨天开始录不了

**Comment by ihmily** [comment]
我看看你的config.ini文件配置内容

**Comment by elicary894** [comment]
> 我看看你的config.ini文件配置内容

[录制设置]
直播保存路径（不填则默认） = 
视频保存格式ts|mkv|flv|mp4|ts音频|mkv音频 = ts
原画|超清|高清|标清 = 原画
是否使用代理ip（是/否） = 是
代理地址 = http://127.0.0.1:7890
同一时间访问网络的线程数 = 20
循环时间(秒) = 120
排队读取网址时间(秒) = 0
是否显示循环秒数 = 否
分段录制是否开启 = 是
视频分段时间(秒) = 1800
ts录制完成后自动转为mp4格式 = 否
ts录制完成后自动增加生成m4a格式 = 否
追加格式后删除原文件 = 否
生成时间文件 = 否
使用代理录制的平台（逗号分隔） = tiktok, afreecatv, pandalive, winktv, flextv, popkontv
额外使用代理录制的平台（逗号分隔） =

**Comment by ihmily** [comment]
> 2024-03-12 09:42:09.858 | WARNING | **main**:start_record:1279 - 错误信息: Command '['ffmpeg', '-y', '-v', 'verbose', '-rw_timeout', '30000000', '-loglevel', 'error', '-hide_banner', '-user_agent', 'Mozilla/5.0 (Linux; Android 11; SAMSUNG SM-G973U) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/14.2 Chrome/87.0.4280.141 Mobile Safari/537.36', '-protocol_whitelist', 'rtmp,crypto,file,http,https,tcp,tls,udp,rtp', '-thread_queue_size', '1024', '-analyzeduration', '40000000', '-probesize', '20000000', '-fflags', '+discardcorrupt', '-i', 'http://live-global-cdn-v02.afreecatv.com/live-stmc-39/auth_playlist.m3u8?aid=.A32.7bbT56vyHM9fKZk.FHw9EBu0Cy006vKAI6VBSyR5UqSagE2uM6SOVUQayLg83jnnJyodiNJNsJmbDpQa_d4Aodcex7qwkqrXvDpGKG2_Pu0NtIrDO1fpklu452KlT-LxrfhTyjcPwsFZlR_g', '-bufsize', '15000k', '-sn', '-dn', '-reconnect_delay_max', '60', '-reconnect_streamed', '-reconnect_at_eof', '-max_muxing_queue_size', '2048', '-correct_ts_overflow', '1', '-c:v', 'copy', '-c:a', 'copy', '-map', '0', '-f', 'segment', '-segment_time', '1800', '-segment_format', 'mpegts', '-reset_timestamps', '1', 'C:/Users/10467/Downloads/DouyinLiveRecorder.v3.0.2/DouyinLiveRecorder v3.0.2/DouyinLiveRecorder.v3.0.2/downloads/AfreecaTV/지연e♥/지연e♥_2024-03-12_09-42-04_%03d.ts']' returned non-zero exit status 4294967158. 发生错误的行数: 1275


看你这个报错里的参数 你好像没有使用到设置的 `http://127.0.0.1:7890` 代理进行录制，如果使用到应该会有 `'-http_proxy', 'http://127.0.0.1:7890'`

**Comment by elicary894** [comment]
> > 2024-03-12 09:42:09.858 | WARNING | **main**:start_record:1279 - 错误信息: Command '['ffmpeg', '-y', '-v', 'verbose', '-rw_timeout', '30000000', '-loglevel', 'error', '-hide_banner', '-user_agent', 'Mozilla/5.0 (Linux; Android 11; SAMSUNG SM-G973U) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/14.2 Chrome/87.0.4280.141 Mobile Safari/537.36', '-protocol_whitelist', 'rtmp,crypto,file,http,https,tcp,tls,udp,rtp', '-thread_queue_size', '1024', '-analyzeduration', '40000000', '-probesize', '20000000', '-fflags', '+discardcorrupt', '-i', 'http://live-global-cdn-v02.afreecatv.com/live-stmc-39/auth_playlist.m3u8?aid=.A32.7bbT56vyHM9fKZk.FHw9EBu0Cy006vKAI6VBSyR5UqSagE2uM6SOVUQayLg83jnnJyodiNJNsJmbDpQa_d4Aodcex7qwkqrXvDpGKG2_Pu0NtIrDO1fpklu452KlT-LxrfhTyjcPwsFZlR_g', '-bufsize', '15000k', '-sn', '-dn', '-reconnect_delay_max', '60', '-reconnect_streamed', '-reconnect_at_eof', '-max_muxing_queue_size', '2048', '-correct_ts_overflow', '1', '-c:v', 'copy', '-c:a', 'copy', '-map', '0', '-f', 'segment', '-segment_time', '1800', '-segment_format', 'mpegts', '-reset_timestamps', '1', 'C:/Users/10467/Downloads/DouyinLiveRecorder.v3.0.2/DouyinLiveRecorder v3.0.2/DouyinLiveRecorder.v3.0.2/downloads/AfreecaTV/지연e♥/지연e♥_2024-03-12_09-42-04_%03d.ts']' returned non-zero exit status 4294967158. 发生错误的行数: 1275
> 
> 看你这个报错里的参数 你好像没有使用到设置的 `http://127.0.0.1:7890` 代理进行录制，如果使用到应该会有 `'-http_proxy', 'http://127.0.0.1:7890'`

那大佬有没什么解决方案

**Comment by ihmily** [comment]
额外使用代理录制的平台（逗号分隔） = afreecatv

这样设置试试

**Comment by elicary894** [comment]
> 额外使用代理录制的平台（逗号分隔） = afreecatv
> 
> 这样设置试试

大佬我试出来，就直接把之前URL_config文件的链接直接复制到新的版本的URL_config文件就录不上，但再打开直播间复制地址到URL_config文件里就可以录了，这是正常的吗，感谢解答
