### ISSUE TITLE
我要是一直在服务器上开着监测进程，等待时间设置多少面比较合适

### ISSUE THREAD

**Issue by zihaoxingstudy1** [ihmily/DouyinLiveRecorder#226]
我要是一直在服务器上开着监测进程，等待时间设置多少面比较合适，默认是 120s 在 confih.ini

**Comment by ihmily** [comment]
5分钟、10分钟...当然是越大越好，设置大一点，可以避免因频繁访问B站导致出问题，但这样检测可能不是很及时，当主播直播时，有可能会出现少录制几分钟，所以得你自己权衡，看能不能接受一点误差。

**Comment by zihaoxingstudy1** [comment]
哦哦，是设置时间久一点安全一些, 但会丢失开头的那几分钟，我要是在户外用手机直播，直播的时候提前用手机ssh连接登录下服务器，让服务器把python main.py录屏进程开起来录自己的直播，这种情况是不需要把等待时间设置的太久是吗        
            
                
                    
                            
                                
                            
                            
                                zihaoxing
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        ---- 回复的原邮件 ***@***.***>发送日期2024年3月12日 ***@***.***>***@***.***>***@***.***>主题Re: [ihmily/DouyinLiveRecorder] 我要是一直在服务器上开着监测进程，等待时间设置多少面比较合适 (Issue #226)5分钟、10分钟...当然是越大越好，设置大一点，可以避免因频繁访问B站导致出问题，但这样检测可能不是很及时，当主播直播时，有可能会出现少录制几分钟，所以得你自己权衡，看能不能接受一点误差。—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by ihmily** [comment]
`设置时间久一点安全一些, 但会丢失开头的那几分钟`  这个不是必然会丢失，如果主播刚开播，软件也刚好在那时检测直播状态，那么就不会少录制了。因此，只是概率大小问题。

这个监测原理就是比如设置默认是120s，那就是每经过120秒就去请求一次B站，就这样的时间间隔一直循环往复获取直播状态，如果获取到的状态是在直播，则软件开始录制。

至于你直播前开启录制软件，那就不需要考虑这个等待时间了，可以设置稍微小一点，1是让你直播一开启就能被检测到，然后开始录制，2是如果你直播时网络中断，也能快速再次启动录制。
