### ISSUE TITLE
你好，录制Tik Tok直播的时候一直显示错误代码644

### ISSUE THREAD

**Issue by Amber834194** [ihmily/DouyinLiveRecorder#23]
目前是随便找了个直播间在调试，一直出现这样的提示
错误信息644:HTTPSConnectionPool(host= ' www . tiktok. com'，port=443): Max retries exceeded with url: /@hi _yang0522/live （Caused by ProxyError( ' Cannot connect to proxy. ' ，ConnectionRestError(10054, ' 远程主机强迫关闭了一个现有的连接。’，None，10054，None)))
读取的地址为: https://www . tiktok. com/ @hi_yang0522/live 发生错误的行数: 511
按照您提供的注意事项调试了很久也没有解决，想问问应该怎么办

**Comment by ihmily** [comment]
这是ssl证书验证的问题，是我改代码时把tiktok的请求代码也误设置为不使用代理，所以相当于没有使用代理去访问tiktok，才出现了这个错误。目前最新版本1.0.6已将其修复。

**Comment by Amber834194** [comment]
非常感谢更新！不过又出现了下面的问题↓
错误信息644:HTTPSConnectionPooL(host= ' www tiktok . com ，port=443): Max retries exceeded with url: /@parksuni198/live (Caused by ProxyError(' Cannot connect to proxy. '，ConnectionResetError(10054， ' 远程主机强迫关闭了一个现有的连接。', None, 10054，None)))
读取的地址为: https : //www . tiktok . com/@parksuni198ve发生错误的行数: 513
感觉是类似的问题吗？麻烦您了！
