### ISSUE TITLE
从抖音主播 id 直接添加

### ISSUE THREAD

**Issue by Hua-Wu-Que-Code** [ihmily/DouyinLiveRecorder#231]
希望下一个版本可以直接从主播 id 获取主播直播链接，这样不需要等到主播开播后添加直播间链接了

**Comment by ihmily** [comment]
> 希望下一个版本可以直接从主播 id 获取主播直播链接，这样不需要等到主播开播后添加直播间链接了

参考 https://github.com/ihmily/DouyinLiveRecorder/issues/334#issuecomment-2094076847

可以自己修改地址实现 进入作者主页 复制抖音号
![image](https://github.com/ihmily/DouyinLiveRecorder/assets/114978440/acd55d7f-2440-4104-855a-c490fa941eab)

然后将其构造直播间地址，`https://live.douyin.com/抖音号`

如上图中作者的抖音号是romi999，那么她的直播间地址就是 https://live.douyin.com/romi999
