### ISSUE TITLE
winktv无法走代理的bug

### ISSUE THREAD

**Issue by astartabc** [ihmily/DouyinLiveRecorder#235]
按照使用说明设置配置文件，但仍然无法使用代理，代理端口正确
部分配置文件内容如下:
![屏幕截图 2024-03-14 191823](https://github.com/ihmily/DouyinLiveRecorder/assets/157791384/fd33b2d0-0fd7-4dd2-9618-2458904ee3a1)

**Comment by astartabc** [comment]
> 有报错信息吗？直播间地址也发一下

没有任何报错信息,就是不走代理
每个直播间都这样,不是某一个直播间的问题
例:https://www.winktv.co.kr/live/play/jellybebe

**Comment by ihmily** [comment]
> > 有报错信息吗？直播间地址也发一下
> 
> 没有任何报错信息,就是不走代理 每个直播间都这样,不是某一个直播间的问题 例:https://www.winktv.co.kr/live/play/jellybebe

不是代理的原因，你可以试试这个 直播间 https://www.winktv.co.kr/live/play/anjer1004 ，是直播间需要登录才能观看的问题

**Comment by astartabc** [comment]
> > > 有报错信息吗？直播间地址也发一下
> > 
> > 
> > 没有任何报错信息，就是不走代理每个直播间都是这样，不是某个直播间的问题 例： https: [//www.winktv.co.kr/live/play/jellybebe](https://www.winktv.co.kr/live/play/jellybebe)
> 
> 不是代理的原因，你可以试试这个直播间https://www.winktv.co.kr/live/play/anjer1004，是直播间需要登录才能观看的问题

确实是登录才能观看,但有正常设置cookie,也能获取到直播间。
由于是海外平台,直连会导致网络不够稳定,影响录制效果,但又无法正常走代理。

**Comment by astartabc** [comment]
> 经过测试，如果配置正确是能走代理的，我上面发的直播间是不需要登录就可以观看的，你可以拿这个测试。

好吧,那我再研究一下,感谢作者的回复！

**Comment by NormanMises** [comment]
不是需不需要登录的问题吧 即使需要登录也要发请求不是吗？但代理的日志里完全没有请求的日志
