### ISSUE TITLE
无语 panda挂着检测不到 

### ISSUE THREAD

**Issue by NormanMises** [ihmily/DouyinLiveRecorder#239]
panda可以直连结果用软件获取不到流 只能代理，结果今天代理又获取不到流了

**Comment by ihmily** [comment]
你是在ffmpeg开始录制的时候报错，还是说一开始获取直播源地址就报错了？

你试试这个直播间 
https://www.pandalive.co.kr/live/play/luvbom10

看是否能正常录制。

**Comment by NormanMises** [comment]
没有报错 直接检测不到

**Comment by ihmily** [comment]
不可能什么都不显示吧，你把URL_config.ini文件全部清空，就留一个地址试试。

**Comment by ihmily** [comment]
`网络异常，请检查本网络是否能正常访问PandaTV直播平台` 出现这个是因为 你本机无法访问Google 。

你把你录制的这个直播间地址发一下

**Comment by NormanMises** [comment]
https://www.pandalive.co.kr/live/play/jinricp,主播: 진리컴퍼니 (jinricp)

**Comment by NormanMises** [comment]
flex也能直连，不知道为什么获取不到流

**Comment by NormanMises** [comment]
老哥 代理的格式是什么啊  是 127.0.0.1:12345    还是 http://127.0.0.1:12345             ？

**Comment by NormanMises** [comment]
![image](https://github.com/ihmily/DouyinLiveRecorder/assets/38835726/7e9a917a-8b69-482d-b7db-4cdc91be76ca)
![image](https://github.com/ihmily/DouyinLiveRecorder/assets/38835726/4b8b1c9c-f30f-4e58-97f5-c2906f8f3127)
![image](https://github.com/ihmily/DouyinLiveRecorder/assets/38835726/c9d52ec0-c958-41c6-9f88-46f1d7660da3)
![image](https://github.com/ihmily/DouyinLiveRecorder/assets/38835726/0c27139b-1574-4969-b0a0-a2348717af96)
这样设置不走代理

**Comment by NormanMises** [comment]
好像exe根本没有发出请求了 什么代理日志都没有

**Comment by ihmily** [comment]
`使用代理录制的平台（逗号分隔） = tiktok, afreecatv, pandalive, winktv, flextv, popkontv` 

你的config.ini配置文件中有这一行吗

**Comment by NormanMises** [comment]
有

**Comment by NormanMises** [comment]
现在我本机上已经完全失效了
