### ISSUE TITLE
非常不错，录制douyin，但是有个问题，如果我录制付费直播间，就不行了，因为虽然录制了，但是视频是花屏的

### ISSUE THREAD

**Issue by fangbulaji** [ihmily/DouyinLiveRecorder#241]
非常不错，录制douyin，但是有个问题，如果我录制付费直播间，就不行了，因为虽然录制了，但是视频是花屏的，请问有什么办法解决这个问题么，是因为被加密了么，那有什么办法可以隐身录制，或者破解呢

**Comment by ihmily** [comment]
> 非常不错，录制douyin，但是有个问题，如果我录制付费直播间，就不行了，因为虽然录制了，但是视频是花屏的，请问有什么办法解决这个问题么，是因为被加密了么，那有什么办法可以隐身录制，或者破解呢

付费直播的话，如果你能看那个直播，那就能录制，前提是需要你自己当时的Cookie
