### ISSUE TITLE
这条直播链接提示有问题?其他的都是正常的

### ISSUE THREAD

**Issue by YJL12345** [ihmily/DouyinLiveRecorder#248]
https://live.douyin.com/238695847949
![Snipaste_2024-03-19_05-52-14](https://github.com/ihmily/DouyinLiveRecorder/assets/42275612/af4efdf3-5ad7-4b13-ad0a-5593f0fc952c)

**Comment by YJL12345** [comment]
复现:
填写链接,第一次录制没问题,录制分段视频之后,最后一个视频文件有概率损坏,而且直播停了之后,录制却不会停.
关掉软件重新录制,链接后面自动填写了主播的id,就不能录制了

**Comment by ihmily** [comment]
最新版已修复
