### ISSUE TITLE
494错误

### ISSUE THREAD

**Issue by 20082010** [ihmily/DouyinLiveRecorder#25]
错误信息: 'NoneType' object has no attribute 'group' 发生错误的行数: 494
这是啥原因？

**Comment by Hertz221** [comment]
我也一样。。

**Comment by 20082010** [comment]
发现了。主要是大家懒。。cookies用的都是默认的。作者重新登录了之后就会发生变化。需要填写自己的。不过填写了自己的。依旧还是报错。。。
