### ISSUE TITLE
问一下关于推送的问题

### ISSUE THREAD

**Issue by soilhare** [ihmily/DouyinLiveRecorder#251]
我只设置了一个flextv的主播，只有我连接代理并且打开DouyinLiveRecorder检测直播的时候才会推送开播通知，想问一下怎么才能先通知，我再去打开DouyinLiveRecorder录制，是要把这个部署在服务器上吗

**Comment by Bill-tw** [comment]
選項裡面有個僅通知不錄製的開關。程序要執行才有檢測也就是要部署在服務器上是的。

**Comment by ihmily** [comment]
> 我只设置了一个flextv的主播，只有我连接代理并且打开DouyinLiveRecorder检测直播的时候才会推送开播通知，想问一下怎么才能先通知，我再去打开DouyinLiveRecorder录制，是要把这个部署在服务器上吗

@Bill-tw 说的正确，这个只需要通知你开播的话，需要一直运行程序并且设置只通知不录制
