### ISSUE TITLE
docker 如何安装老版本

### ISSUE THREAD

**Issue by Nzybwzy** [ihmily/DouyinLiveRecorder#252]
你好 docker 如何安装 20240209 版本 哪里能获取到历史的sha256值    因为后面版本 有些panda主播拉不到1080 只能拉到720  重启也没用

**Comment by Nzybwzy** [comment]
.

**Comment by ihmily** [comment]
@Nzybwzy 这是docker仓库 https://hub.docker.com/r/ihmily/douyin-live-recorder/tags ，里面包含所有历史版本
