### ISSUE TITLE
遇到新的错误，错误代码451

### ISSUE THREAD

**Issue by 0zxcvbnm0** [ihmily/DouyinLiveRecorder#26]
![IMG_20230904_231150](https://github.com/ihmily/DouyinLiveRecorder/assets/144042768/86884926-de5e-42b1-9564-8e4b859750f4)

遇到新的错误，今天早上还能用，晚上就这样了，空间啥的都有，请问一下，这是什么原因？

**Comment by ihmily** [comment]
抖音官方更新了版本，现在v1.0.7版本已经修复
