### ISSUE TITLE
config.ini里面分段录制设置成了否 但TikTok录制还是会分段是怎么回事

### ISSUE THREAD

**Issue by heiheiepro** [ihmily/DouyinLiveRecorder#261]
config.ini里面分段录制设置成了否 但TikTok录制还是会分段是怎么回事 不想分段录制 想整场直播只录制为一个文件

**Comment by ihmily** [comment]
> config.ini里面分段录制设置成了否 但TikTok录制还是会分段是怎么回事 不想分段录制 想整场直播只录制为一个文件

有可能是网络不佳，录制中断了
