### ISSUE TITLE
设置录制格式为flv时无法录制

### ISSUE THREAD

**Issue by LoveDqi** [ihmily/DouyinLiveRecorder#264]
还有在设置为ts格式
开启分段录制，转码为mp4，没有开启删除源文件的前提下
录制完成后并没有ts的文件，只有mp4的文件

**Comment by ihmily** [comment]
> 还有在设置为ts格式 开启分段录制，转码为mp4，没有开启删除源文件的前提下 录制完成后并没有ts的文件，只有mp4的文件

开启分段后不支持 ts转mp4
