### ISSUE TITLE
直播录制出错    我开了代理IP为什么还是录不了

### ISSUE THREAD

**Issue by a1122335** [ihmily/DouyinLiveRecorder#266]
![{091941F8-5C1D-45c1-9A2E-9710D6448073}](https://github.com/ihmily/DouyinLiveRecorder/assets/149315573/1efd25e7-e53a-42f8-8db9-55fe120673bb)

**Comment by Lesyooo** [comment]
解决了吗老哥

**Comment by a1122335** [comment]
还没有




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ihmily/DouyinLiveRecorder"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月2日(星期二) 上午9:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ihmily/DouyinLiveRecorder] 直播录制出错    我开了代理IP为什么还是录不了 (Issue #266)





 
解决了吗老哥
