### ISSUE TITLE
原理 在html读出视频流的真正地址 然后用ffmpeg 去下载直播..

### ISSUE THREAD

**Issue by ayun110** [ihmily/DouyinLiveRecorder#272]
原理 在html读出视频流的真正地址 然后用ffmpeg 去下载直播..

**Comment by Bill-tw** [comment]
就是 ffmpeg 录制时偶发会有视频音频不同步的现象不知道怎么优化。估计是任一边的网络卡一下但又没断造成的。分段录制没法救这个，困扰。
