### ISSUE TITLE
ModuleNotFoundError: No module named 'requests'

### ISSUE THREAD

**Issue by qazgp** [ihmily/DouyinLiveRecorder#273]
请问一运行就报这个错误该怎么解决，python版本是3.8

**Comment by ihmily** [comment]
源码运行先安装依赖，参考 [命令控制台执行](https://github.com/ihmily/DouyinLiveRecorder#:~:text=ihmily/DouyinLiveRecorder.git-,2.%E8%BF%9B%E5%85%A5%E9%A1%B9%E7%9B%AE%E6%96%87%E4%BB%B6%E5%A4%B9%EF%BC%8C%E5%AE%89%E8%A3%85%E4%BE%9D%E8%B5%96,-cd%20DouyinLiveRecorder%0Apip3)
