### ISSUE TITLE
已经没法获取抖音直播流媒体地址

### ISSUE THREAD

**Issue by hejiaonju** [ihmily/DouyinLiveRecorder#28]
我用下面这个，后面附上直播间的连接，现在已经无法获取流媒体地址了
https://hmily.vip/api/jx/live/?url=

**Comment by 20082010** [comment]
配置里用的是作者自己的cookies。这个失效了。所以用不了了

**Comment by ihmily** [comment]
@20082010 
抖音官方更新了版本，现在v1.0.7已同步更新
