### ISSUE TITLE
FLEXTV無法錄製

### ISSUE THREAD

**Issue by Irene75b** [ihmily/DouyinLiveRecorder#282]
用網頁版網址貼上後會出現
FlexTV直播间数据获取失败 ' NoneType ' object has no attribute 'group '

**Comment by a1122335** [comment]
我的前几天fixeTV  可以录制   昨天开始就不能用了

**Comment by a1122335** [comment]
可以加个好友  一起探讨下吗

**Comment by Irene75b** [comment]
我不懂程式碼哈哈
我也是從昨天開始不能錄製

**Comment by a1122335** [comment]
你的  AF可以录制吗

**Comment by Irene75b** [comment]
可以

**Comment by a1122335** [comment]
能交下你是怎么设置的吗

**Comment by Irene75b** [comment]
我設定除了畫質跟檔案類型以外的都沒動
