### ISSUE TITLE
这个到底是怎么回事   就是录制不了   连续尝试了 十几天  心累    有哪位大佬告知下   有偿都可以

### ISSUE THREAD

**Issue by a1122335** [ihmily/DouyinLiveRecorder#284]
![{58E8F867-0275-4e97-94EE-DDDC1CF6F257}](https://github.com/ihmily/DouyinLiveRecorder/assets/149315573/5294c75e-fe4a-4210-bb7d-89ab102d03cb)

**Comment by ihmily** [comment]
@a1122335 flextv 官方更新了，所以无法录制，现在仓库代码已更新，可以正常录制了，新版打包exe我这两天更新发布。

![image](https://github.com/ihmily/DouyinLiveRecorder/assets/114978440/bc55ce22-3446-4b46-965c-67c167ab51d2)

![image](https://github.com/ihmily/DouyinLiveRecorder/assets/114978440/fd1705ad-31d1-42b1-926a-33c75e77a26a)

**Comment by a1122335** [comment]
作者大大   新版打包exe更新了吗

**Comment by ihmily** [comment]
> 作者大大 新版打包exe更新了吗

已更新
