### ISSUE TITLE
关于使用程序过程中发现的popkontv直播平台相关的一些小bug和建议

### ISSUE THREAD

**Issue by xueli12** [ihmily/DouyinLiveRecorder#294]
作者大大您好，
      在使用程序的过程中发现以下一些小bug和我的一些建议，1-5的bug我尝试修改了一下，可能不完善，修改后的代码已发大大的iubridge邮箱啦~：

1.目前程序中使用了以下代码，仅将搜索API搜索出来的结果的第一组数据作为后续请求直播流的参数，存在问题。搜索接口https://www.popkontv.com/api/proxy/broadcast/v1/search/all   采用的是模糊匹配的方式搜索，如果主播的名字过于简单，比如举个极端的例子，搜11，会出现很多结果，因此需要在搜索结果中匹配主播id完全等于11的那组数据才是正确的。
    anchor_id = json_data['data']['broadCastList'][0]['mcSignId']
    anchor_name = f"{json_data['data']['broadCastList'][0]['nickName']}-{anchor_id}"
    partner_code = json_data['data']['broadCastList'][0]['mcPartnerCode']

建议采用以下逻辑，匹配json结果中mcSignId等于anchor_id的那组数据：
                for item in response_json['data']['liveList']:
                    if item['mcSignId'] == anchor_id:

2.搜索API经常抽风，部分主播无法通过https://www.popkontv.com/api/proxy/broadcast/v1/search/all 找到直播间
现有程序出现报错时的日志：
![image](https://github.com/ihmily/DouyinLiveRecorder/assets/51438016/2f97d164-15d8-4a7d-9801-63fe3e10b516)

出现bug的例子：
比如https://www.popkontv.com/live/view?castId=162cm&partnerCode=P-00074 是无法通过搜索来获取到partnerCode的，
![image](https://github.com/ihmily/DouyinLiveRecorder/assets/51438016/42787241-2dc2-45e4-97ed-c130e61c9b93)
但是确实有这个主播   https://www.popkontv.com/channel/notices?mcid=162cm&mcPartnerCode=P-00074
![image](https://github.com/ihmily/DouyinLiveRecorder/assets/51438016/a18c773f-acd2-4977-a17b-8b502f9ae456)

3.从这个搜索接口https://www.popkontv.com/api/proxy/broadcast/v1/search/all 获取的一些变量的数据在少数情况下会不准确，导致后续无法获取直播流。据我所知，目前发现的出现过不准确数据的是cast_start_date_code变量，建议在通过https://www.popkontv.com/api/proxy/broadcast/v1/search/all 获取partnerCode后直接请求直播间地址来获取cast_start_date_code，比如 https://www.popkontv.com/live/view?castId=eywkrl0112&partnerCode=【partnerCode】，从我这几个月的录制情况来看，直接请求直播间地址获取到的数据比搜索的接口准确。

4.目前程序是从直播间URL的链接中提取的castId，然后构造f'{anchor_id}-{cast_start_date_code}'作为请求直播流的参数。但是popkontv的程序员很坑爹，部分情况下直播间从响应内容获取的mc_signId和castId会不一样，建议是直接请求直播间地址从响应内容中获取mc_signId作为请求直播流的参数f'{mc_signId}-{cast_start_date_code}'。

5.获取直播流的castType目前定义为0，但是还有其他castType的数值，也是建议从直播间的响应内容中获取castType的数值，

6.部分直播间可能需要送礼物才能观看，json_data['statusCd'] == "L00A1"的情况下，建议增加打印提示，比如：

7.求支持按文件大小分割视频。据说biliup可以按大小分割，但很多海外平台没有，也不会使用。

8.求支持分段视频在保存格式为ts时，能够在录制完成后转码为mp4，而不是实时转码为mp4，因为中途程序崩溃视频就坏了。如果在ts下载完成后才转码，即使转码过程中崩溃，起码还有ts文件能看。

**Comment by ihmily** [comment]
@xueli12 非常感谢你提的issue，关于`popkontv` 的直播源获取 已经根据你的测试代码，更新到主分支

**Comment by ihmily** [comment]
@xueli12 已在项目README将你纳入贡献者展示
