### ISSUE TITLE
pandaTV  19+的是不是录制不了？也没有登录的设置？

### ISSUE THREAD

**Issue by a1122335** [ihmily/DouyinLiveRecorder#301]
![{5307C665-82A0-423e-A5BE-7A4615A2AE56}](https://github.com/ihmily/DouyinLiveRecorder/assets/149315573/b76dd141-c1da-4475-a8a4-e40af4d73be4)
pandaTV   是不是19+的录制不了啊  ？

**Comment by ihmily** [comment]
>pandaTV 是不是19+的录制不了啊 ？

你需要在pandatv网页上登录19+账号，获取登录后的Cookie，填写在配置文件中，然后才能录制pandaTV 19+直播.

**Comment by a1122335** [comment]
![{0D6E5091-13E8-4169-BA18-EEB92A3DF54B}](https://github.com/ihmily/DouyinLiveRecorder/assets/149315573/1e37e6c5-1e0f-4b3e-b0b0-010d28081f20)
![{9753C19F-CB2C-4cfc-B9AF-BD7E53A62BAF}](https://github.com/ihmily/DouyinLiveRecorder/assets/149315573/0b8fef48-f3e3-4dae-8fe4-c065733d48d5)
![{B52F162D-419A-423d-BB97-F2650E008E1F}](https://github.com/ihmily/DouyinLiveRecorder/assets/149315573/eb137a72-c39d-46da-9ca1-9f39ffca3885)
![{B680AD9E-7A73-4c4d-8EC2-1B096CE6A5C0}](https://github.com/ihmily/DouyinLiveRecorder/assets/149315573/01801a20-ba3d-497f-9b61-902994171689)
作者大大  按照你的方法试过了   还是录制不了19+
