### ISSUE TITLE
因程序意外退出，录制中断，原来正在录制的视频无法打开了

### ISSUE THREAD

**Issue by xueli12** [ihmily/DouyinLiveRecorder#302]
设置里设置了视频保存格式为ts，但录制过程中的格式一直是mp4，
![image](https://github.com/ihmily/DouyinLiveRecorder/assets/51438016/545304cd-bf8f-4dbc-856b-d2814ea0f2f9)

因为系统的问题出现了报错，导致录播程序被关闭，无法使用ctrl+c，只能关闭计算机重启，重启后发现录制过程中的视频无法打开了
![image](https://github.com/ihmily/DouyinLiveRecorder/assets/51438016/c529897a-4047-4135-86e3-446c9ad59348)

![image](https://github.com/ihmily/DouyinLiveRecorder/assets/51438016/1615bd05-e7b5-41ad-a2bd-f7d5551b5450)

建议：能否在录制过程中使用原格式，录制结束时再进行转码，避免上述问题，据我所知ts在录制过程中中断还能看

**Comment by ihmily** [comment]
是的，ts格式可边观看边录制，你这种情况可能需要设置不分段，就是录制结束后转码的。

**Comment by ihmily** [comment]
>大大，这个软件部署在我的服务器上会频繁出现这个报错，不过不是立刻发生的，是运行一阵子，有时候一天有时候几分钟就有这种报错，点击它后又会弹出，然后py程序是直接退出了，但是ffmpeg还在后台下载，用了py文件或者打包的exe文件都是这样，已经重装过一次系统还是有这问题。。。目前使用了另一个程序来录制，录制几天没出现过这种问题。

我也不太了解这个，估计是系统问题，有没有安装什么杀毒软件，安全软件，可能有冲突
