### ISSUE TITLE
3.0.2版本配置微信通知未通知

### ISSUE THREAD

**Issue by slmepipi** [ihmily/DouyinLiveRecorder#305]
[推送配置]
直播状态通知(可选微信|钉钉|tg或者都填) = 
钉钉推送接口链接 = 
微信推送接口链接 = https://xizhi.qqoq.net/xxxxxxxxxxxxxxx.send
钉钉通知@对象(填手机号) = 
tgapi令牌 = 
tg聊天id(个人或者群组id) = 
只推送通知不录制（是/否） = 否
直播推送检测频率（秒） = 120

请帮忙查看是哪里出现问题感谢

**Comment by ihmily** [comment]
> 直播状态通知(可选微信|钉钉|tg或者都填) =

@slmepipi  如果要微信推送，`直播状态通知(可选微信|钉钉|tg或者都填) =` 这个要填 微信

正确的配置：
直播状态通知(可选微信|钉钉|tg或者都填) = 微信
