### ISSUE TITLE
无法启动软件

### ISSUE THREAD

**Issue by keunnel** [ihmily/DouyinLiveRecorder#31]
双击软件后显示：
The program can't start because api-ms-win-core-path-lt-1-0.dll is missing from your computer. Try reinstalling the program to fix this problem.
请求帮助。谢谢。

**Comment by ihmily** [comment]
你是win7系统吧？该软件不兼容win7，你可以试试下载api-ms-win-core-path-l1-1-0.dll 文件，将其放入exe文件同个目录下
下载地址：
https://wweb.lanzoum.com/icLdf17m0z2d    密码:7fi6
如果运行加入这个dll文件还有错误，那就没办法了，请在win10/11上运行本程序。

**Comment by keunnel** [comment]
是用着win7系统。已经依据你的指示下载该文件，但乃然无法启动此软件。能否有其他方法，或能介绍一款能兼容win7的录屏抖音直播软件吗？谢谢。

**Comment by ihmily** [comment]
> 是用着win7系统。已经依据你的指示下载该文件，但乃然无法启动此软件。能否有其他方法，或能介绍一款能兼容win7的录屏抖音直播软件吗？谢谢。

或许你可以试试最新发布，我上传了一个可能适用于win7系统的1.0.9版本，传送门：[DouyinLiveRecorder.v1.0.9](https://github.com/ihmily/DouyinLiveRecorder/releases/tag/v1.0.9)
