### ISSUE TITLE
[求助] 兄弟们, 这是啥情况, afreeca的录制不了啊, 地址正确, 网络正常(我用别的录制正常)

### ISSUE THREAD

**Issue by sirblangch** [ihmily/DouyinLiveRecorder#311]
![微信图片_20240421103039](https://github.com/ihmily/DouyinLiveRecorder/assets/167659962/71b5997d-2dc1-404e-a5c8-f4ef17381249)

**Comment by ihmily** [comment]
如果开了代理，检查代理地址和端口填写的是否正确，如果网络本身能访问，就可以不用开启代理设置
