### ISSUE TITLE
求助 flextv 设置基本配置后录制报错

### ISSUE THREAD

**Issue by CastleYeager** [ihmily/DouyinLiveRecorder#313]
这是我的config.ini文件，只修改了两处
![image](https://github.com/ihmily/DouyinLiveRecorder/assets/61653667/d7406756-38c4-47a9-a58b-ee1e756e2f06)

这是我的URL_config.ini文件，只录制一位flextv主播
![image](https://github.com/ihmily/DouyinLiveRecorder/assets/61653667/d5ecdadf-fea6-4c37-abf0-195050a3e24a)

这是我的报错信息
![image](https://github.com/ihmily/DouyinLiveRecorder/assets/61653667/911f96cd-3ac9-4539-8da5-71937914d771)
![image](https://github.com/ihmily/DouyinLiveRecorder/assets/61653667/ccd016b3-da13-43bb-aa19-4361780d97b9)

大佬们帮忙看下，感激不尽

**Comment by ihmily** [comment]
这个之前的代码已经失效了，仓库代码已经修复这个问题，你可以运行代码录制（如果会的花），这两天我打包一下软件吧

![image](https://github.com/ihmily/DouyinLiveRecorder/assets/114978440/87df63f0-58ff-427f-a2b4-b8bcdf971ebc)

![image](https://github.com/ihmily/DouyinLiveRecorder/assets/114978440/674780b7-4822-4f93-b4db-45fa1c771f28)

**Comment by CastleYeager** [comment]
源码运行时也有些问题

安装依赖
![image](https://github.com/ihmily/DouyinLiveRecorder/assets/61653667/56873e96-6042-42e9-9e00-b8b208b3d45c)

执行启动命令后报错信息，保存信息略有不同：
![image](https://github.com/ihmily/DouyinLiveRecorder/assets/61653667/aa2cc2d0-effa-41eb-8f96-0e38944a1347)

此时的配置文件
![image](https://github.com/ihmily/DouyinLiveRecorder/assets/61653667/16115fd4-a9cb-4850-856a-bbac84b5421c)
![image](https://github.com/ihmily/DouyinLiveRecorder/assets/61653667/00ebc56c-fb14-4ea6-979b-9719cb7959bc)

**Comment by ihmily** [comment]
@CastleYeager 

你的网络证书有问题，你把https改为http试试，还是不行的话，重启一下电脑

**Comment by CastleYeager** [comment]
@ihmily 
还是一样的报错信息
考虑是否与我使用的环境有关，我使用的是某里云的轻量应用服务器，香港节点，用其他软件录制afc、twc之类的平台没问题
![image](https://github.com/ihmily/DouyinLiveRecorder/assets/61653667/f50b8a8d-d0de-4ca2-9be1-766d643e515c)

**Comment by CastleYeager** [comment]
@ihmily 
问题初步排查是我使用的环境问题；
我在自己本地也使用源码运行，当开启香港节点梯子时，网络异常；
当我开启韩国节点梯子时，录制成功；

韩国梯子，成功：
![image](https://github.com/ihmily/DouyinLiveRecorder/assets/61653667/26aa8a07-cc75-484c-ab29-c80e572276bd)

香港梯子，失败：
![image](https://github.com/ihmily/DouyinLiveRecorder/assets/61653667/5f08b008-978d-4565-9f26-7bb09c9e998a)

问题是，本地使用香港梯子时的报错 和 云环境下的报错 也不一致，希望可以帮忙看下云环境下是否有解决方案，或者规避方案，谢谢

**Comment by ihmily** [comment]
> 问题是，本地使用香港梯子时的报错 和 云环境下的报错 也不一致，希望可以帮忙看下云环境下是否有解决方案，或者规避方案，谢谢

![image](https://github.com/ihmily/DouyinLiveRecorder/assets/114978440/1a60f4bc-1a95-44a3-a6a8-424bb92b3c13)
![image](https://github.com/ihmily/DouyinLiveRecorder/assets/114978440/611c1d16-d722-4cb6-9785-f145f5fc35ca)


根本原因都是网络，估计你的代理节点不稳定导致的。前面无法录制是报错为代理ssl验证失败，后面直接提示网络异常是因为连访问Google都失败了，然后你的代理开启设置又是关闭的，所以被代码逻辑判定为无法访问外网，直接抛出异常了，因此两次报的错不一样。

**Comment by CastleYeager** [comment]
```
后面直接提示网络异常是因为连访问Google都失败了，然后你的代理开启设置又是关闭的，所以被代码逻辑判定为无法访问外网，直接抛出异常了，因此两次报的错不一样。
```
是的，我改成不使用代理后，本机挂香港节点也可以正常录制了
大佬牛批

代理ssl验证失败，是否有解，这块不是很熟悉

**Comment by ihmily** [comment]
> 代理ssl验证失败，是否有解，这块不是很熟悉

修改python ssl验证或者在请求flextv的时候开启禁用SSL证书验证参数。

比如直接在spider.py顶部全局加上下面代码
```
import ssl
ssl._create_default_https_context = ssl._create_unverified_context
```

**Comment by CastleYeager** [comment]
@ihmily 
可行，实测云环境下已解决
![image](https://github.com/ihmily/DouyinLiveRecorder/assets/61653667/75965e9e-7202-4fa3-b858-ac050948bde3)

感谢大佬，此issue可关
