### ISSUE TITLE
pandaTV  19+  登录了   还是录制不了

### ISSUE THREAD

**Issue by a1122335** [ihmily/DouyinLiveRecorder#315]
![{0D6E5091-13E8-4169-BA18-EEB92A3DF54B}](https://github.com/ihmily/DouyinLiveRecorder/assets/149315573/fb2884b8-0b5a-4780-8cde-9e000c1d9b78)
![{9753C19F-CB2C-4cfc-B9AF-BD7E53A62BAF}](https://github.com/ihmily/DouyinLiveRecorder/assets/149315573/23fa1132-156d-41c3-aa47-ddb074bfd5fb)
![{B52F162D-419A-423d-BB97-F2650E008E1F}](https://github.com/ihmily/DouyinLiveRecorder/assets/149315573/58631453-d8f0-48f5-b699-1a6b5ac54186)
![{B680AD9E-7A73-4c4d-8EC2-1B096CE6A5C0}](https://github.com/ihmily/DouyinLiveRecorder/assets/149315573/b32d8179-c27a-48d1-831c-1b09422832e7)

**Comment by ihmily** [comment]
有在直播间的地址吗？发一个我看看

**Comment by a1122335** [comment]
https://www.pandalive.co.kr/live/play/parkeil123

**Comment by Nzybwzy** [comment]
好像遇到过 更换cookie恢复正常 接连两次频繁换cookie之后 ip被封一天 第二天减少录制直播间数量恢复正常

**Comment by knight0908** [comment]
> 好像遇到过 更换cookie恢复正常 接连两次频繁换cookie之后 ip被封一天 第二天减少录制直播间数量恢复正常

您好，请问Panda TV的cookie  具体在哪能看到

**Comment by jiblay** [comment]
Hello, where can I see the cookies of Panda TV?
