### ISSUE TITLE
同一个直播间，用本项目录制的码率没有其他项目录制的高

### ISSUE THREAD

**Issue by lxr760** [ihmily/DouyinLiveRecorder#321]
部署方式是Docker   镜像为https://hub.docker.com/r/ihmily/douyin-live-recorder

图1是本项目录制的文件  体积3.5G
![image](https://github.com/ihmily/DouyinLiveRecorder/assets/8476457/798134b4-44d2-41e7-9853-f44b1a5217b4)

图2是其他项目录制的文件  体积11.6G
![image](https://github.com/ihmily/DouyinLiveRecorder/assets/8476457/0fe1f484-f5c6-495c-8b8a-f23e4c4e4d65)

**Comment by lxr760** [comment]
> @lxr760 哪个平台？如果是国外平台有可能是 [#186 (comment)](https://github.com/ihmily/DouyinLiveRecorder/issues/186#issuecomment-1986815180) 这个问题 ，将所有清晰度都录制保存到一起去了。因为2w的比特率 有点不太正常
> 
> 你可以获取到m3u8直播源地址，将其下载并以txt方式打开，看看里面是否有多个清晰度的m3u8地址。

就是国内的抖音           2w的波特率其实正常，这个直播间是打游戏直播，用的不是手机而是显卡HDMI输出，所以码率很高

**Comment by ihmily** [comment]
> > @lxr760 哪个平台？如果是国外平台有可能是 [#186 (comment)](https://github.com/ihmily/DouyinLiveRecorder/issues/186#issuecomment-1986815180) 这个问题 ，将所有清晰度都录制保存到一起去了。因为2w的比特率 有点不太正常
> > 你可以获取到m3u8直播源地址，将其下载并以txt方式打开，看看里面是否有多个清晰度的m3u8地址。
> 
> 就是国内的抖音 2w的波特率其实正常，这个直播间是打游戏直播，用的不是手机而是显卡HDMI输出，所以码率很高

可以发一下直播间地址吗?,我观察一下

**Comment by lxr760** [comment]
> > > @lxr760 哪个平台？如果是国外平台有可能是 [#186 (comment)](https://github.com/ihmily/DouyinLiveRecorder/issues/186#issuecomment-1986815180) 这个问题 ，将所有清晰度都录制保存到一起去了。因为2w的比特率 有点不太正常
> > > 你可以获取到m3u8直播源地址，将其下载并以txt方式打开，看看里面是否有多个清晰度的m3u8地址。
> > 
> > 
> > 就是国内的抖音 2w的波特率其实正常，这个直播间是打游戏直播，用的不是手机而是显卡HDMI输出，所以码率很高
> 
> 可以发一下直播间地址吗?,我观察一下

直播间地址  https://live.douyin.com/685619235482      大概晚上7 8点播，他的直播间有5档画质，比一般的直播间要

**Comment by lxr760** [comment]
除了码率  帧率也会比别的软件录制的低      2个均是同一个直播间录制      左边是别家      右边是本项目
![image](https://github.com/ihmily/DouyinLiveRecorder/assets/8476457/94a802ac-bde9-4bf8-9ff5-9f4f9627966a)

**Comment by ihmily** [comment]
已修复该问题，此issue先关了
