### ISSUE TITLE
pandaTV19+这样登录了  还是录制不了啊     也没有登录pandaTV的地方

### ISSUE THREAD

**Issue by a1122335** [ihmily/DouyinLiveRecorder#323]
![{98AB1C93-C4C8-4840-A8C1-172FF2E23F92}](https://github.com/ihmily/DouyinLiveRecorder/assets/149315573/39b8cc69-45d8-4fba-b982-19209f5e72a0)
![{571AEB71-62BC-4a64-9916-037C37D43308}](https://github.com/ihmily/DouyinLiveRecorder/assets/149315573/95d5692b-6c1c-46b2-ae2b-8b638f0e9835)
![{947BDD41-053B-4de9-AD59-A8A474CB79A7}](https://github.com/ihmily/DouyinLiveRecorder/assets/149315573/96ab1eb4-98f2-4294-bc95-3502026f9895)
pandaTV19+这样登录了  还是录制不了啊     也没有登录pandaTV的地方

**Comment by ihmily** [comment]
你得自己在网站登录账号 获取cookie，填入下方
![image](https://github.com/ihmily/DouyinLiveRecorder/assets/114978440/25bc5e65-853d-4d77-ba22-912121f99315)

没有pandatv登录配置，至于如何获取cookie，自行网上搜索
