### ISSUE TITLE
关于直播提醒推送的优化建议

### ISSUE THREAD

**Issue by lxr760** [ihmily/DouyinLiveRecorder#326]
配置如下
[推送配置]
直播状态通知(可选微信|钉钉|tg或者都填) = 微信|tg
钉钉推送接口链接 = 
微信推送接口链接 = ***
钉钉通知@对象(填手机号) = 
tgapi令牌 = ***
tg聊天id(个人或者群组id) = ***
只推送通知不录制（是/否） = 是
直播推送检测频率（秒） = 60
开播推送开启（是/否）= 是
关播推送开启（是/否）= 是

目前发现，开播提醒的格式为 序号* 直播间名字* 正在直播中，时间：2024-04-28 19:34:58.932090
结束直播的提醒为序号* 直播间名字* 直播已结束！

建议将开播提醒的时间优化为YYYY-MM--DD HH:mm:ss      秒后面的小数位可以省略
直播结束的提醒建议加上时间    目前提醒里没有

另外，提醒里序列号跟URL_config配置里的排序对不上

**Comment by ihmily** [comment]
>目前发现，开播提醒的格式为 序号* 直播间名字* 正在直播中，时间：2024-04-28 19:34:58.932090
>结束直播的提醒为序号* 直播间名字* 直播已结束！
>
>建议将开播提醒的时间优化为YYYY-MM--DD HH:mm:ss 秒后面的小数位可以省略
>直播结束的提醒建议加上时间 目前提醒里没有

已更新，至于那个序号不对，只是做个区分，并不是按照地址填写顺序
