### ISSUE TITLE
运行项目报错

### ISSUE THREAD

**Issue by xiaohaigge** [ihmily/DouyinLiveRecorder#329]
![image](https://github.com/ihmily/DouyinLiveRecorder/assets/129136883/aaa9976c-83c1-4edd-b80c-08920f58fd4a)

**Comment by xiaohaigge** [comment]
明明检测到直播了 却不录制

**Comment by ihmily** [comment]
你开了代理吗？网络不通

**Comment by xiaohaigge** [comment]
![image](https://github.com/ihmily/DouyinLiveRecorder/assets/129136883/daa7a2e1-75af-42fd-804b-80ef8ff00c50)
录制是录制了  这个报错了

**Comment by ihmily** [comment]
> 能提个小小的建议吗，就是nas里部署 看不到运行状态只能在log里看，能否增加个可视化？

这个后续有时间搞吧，得重构

**Comment by G999ithub** [comment]
前两天可以运行，今天报错一个也不行了

**Comment by G999ithub** [comment]
> 前两天可以运行，今天报错一个也不行了

今天报错  373 982         373 984
一个直播间一组

**Comment by ihmily** [comment]
@G999ithub 

提示：IP banned. Please change device or network.
快手录制，最好主播开播后要录制的时候再开，不然很容易风控，被禁ip就无法录制了。过个几天或者换个网络就正常了，快手就这么严格，暂时没办法。

**Comment by G999ithub** [comment]
> @G999ithub
> 
> 提示：IP baned.请更换设备或网络。 快手录制，最好主播开播后要录制的时候再开，不然很容易风控，被禁ip就无法录制了。过个几天或者换个网络就正常了，快手就这么严格，暂时没办法。

也就是说 上一个录屏 不能等到程序自动结束，否则，程序会自己搜索直播间，导致被封。  下一个录屏就提示需要换ip 运行失败.......

**Comment by G999ithub** [comment]
> @G999ithub
> 
> 提示：IP baned.请更换设备或网络。 快手录制，最好主播开播后要录制的时候再开，不然很容易风控，被禁ip就无法录制了。过个几天或者换个网络就正常了，快手就这么严格，暂时没办法。

换句话说，你不能等到程序自动结束最后一次录屏，否则，程序会自行搜索直播间，导致被堵。下一个录屏提示需要更改 IP，操作失败...

**Comment by G999ithub** [comment]
> @G999ithub
> 
> 提示：IP baned.请更换设备或网络。 快手录制，最好主播开播后要录制的时候再开，不然很容易风控，被禁ip就无法录制了。过个几天或者换个网络就正常了，快手就这么严格，暂时没办法。

也就是说 上一个录屏 不能等到程序自动结束，否则，程序会自己搜索直播间，导致被封。下一个录屏就提示需要换ip 运行失败.......
