### ISSUE TITLE
其他平台都能录制   就是afreecatv录制不了   不知道什么原因

### ISSUE THREAD

**Issue by a1122335** [ihmily/DouyinLiveRecorder#330]
![{31C65529-E37C-457b-B838-A294266CC54E}](https://github.com/ihmily/DouyinLiveRecorder/assets/149315573/2ff948bc-909c-4959-8cf7-3beb899f85b1)

**Comment by ihmily** [comment]
网络问题，你修改为这个 `是否使用代理ip（是/否） = 否` 试试，还是不行的话换个地区的代理
