### ISSUE TITLE
无法录制afreecatv平台

### ISSUE THREAD

**Issue by yunhaihaihai** [ihmily/DouyinLiveRecorder#331]
![IMG_20240429_180133_892](https://github.com/ihmily/DouyinLiveRecorder/assets/162297816/88ffb3dc-ee38-4578-ae35-83c8d7902416)
录制afreeactv，代理地址前面必须要加http,但是录制pandatv前面加了http就不能录制了，很神奇，麻烦作者解答一下谢谢

**Comment by ihmily** [comment]
加不加都能正常录制，你这个可能跟你的网络代理有关系。

**Comment by yunhaihaihai** [comment]
我已我已经换了地区了

**Comment by yunhaihaihai** [comment]
账号密码也已经成功登录

**Comment by ihmily** [comment]
直播间地址发一下，我看看我这是否正常

**Comment by yunhaihaihai** [comment]
https://play.afreecatv.com/dign1461/264596026

**Comment by ihmily** [comment]
@yunhaihaihai  代理地址加http和不加都是正常录制的，还是跟你的网络环境有关

![image](https://github.com/ihmily/DouyinLiveRecorder/assets/114978440/419ab759-87f3-4789-8bd3-8dc29975e027)
![image](https://github.com/ihmily/DouyinLiveRecorder/assets/114978440/7684b801-8205-4ded-b7b7-6bb61f7f2149)
![image](https://github.com/ihmily/DouyinLiveRecorder/assets/114978440/eb3e9bad-061a-4b10-a738-debb0a2dcc9f)

**Comment by ihmily** [comment]
你可以拿m3u8直播源地址到播放器播放试试

**Comment by yunhaihaihai** [comment]
都是没有问题的，播放器可以看😂，还有其他排除的方法吗

**Comment by justdoiting** [comment]
> 都是没有问题的，播放器可以看😂，还有其他排除的方法吗

可以检查一下你的代理工具有没有设置代理https

**Comment by xueli12** [comment]
> 你可以拿m3u8直播源地址到播放器播放试试



> @yunhaihaihai 代理地址加http和不加都是正常录制的，还是跟你的网络环境有关
> 
> ![image](https://private-user-images.githubusercontent.com/114978440/326426378-419ab759-87f3-4789-8bd3-8dc29975e027.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0Nzk2OTksIm5iZiI6MTcxNDQ3OTM5OSwicGF0aCI6Ii8xMTQ5Nzg0NDAvMzI2NDI2Mzc4LTQxOWFiNzU5LTg3ZjMtNDc4OS04YmQzLThkYzI5OTc1ZTAyNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQzMFQxMjE2MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xY2UwODkyNTE5ZDY0ODhlYmYxODlmYmIwNGJkMDc0YzEwNDVjM2U0NWIzYzk1YjRhNjA5YzYwMjcxMWE5MmE5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.W_8iXMQB08tyIk080l6nkZSgX2d67oyulLWaQBgXXPs) ![image](https://private-user-images.githubusercontent.com/114978440/326426916-7684b801-8205-4ded-b7b7-6bb61f7f2149.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0Nzk2OTksIm5iZiI6MTcxNDQ3OTM5OSwicGF0aCI6Ii8xMTQ5Nzg0NDAvMzI2NDI2OTE2LTc2ODRiODAxLTgyMDUtNGRlZC1iN2I3LTZiYjYxZjdmMjE0OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQzMFQxMjE2MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMTg0ZTM5ZDYyYzhlNTYxMzcwNDY1YjRiOGEwMDVhMGYxY2JmZDhlMTBlMDE3NjE1MmU2OGQzNWRmY2ViZTA4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nFM4zKQuk8uQI3KoJ1PpxTY9ojxnXCRu6jSM2fA0Dr0) ![image](https://private-user-images.githubusercontent.com/114978440/326427053-eb3e9bad-061a-4b10-a738-debb0a2dcc9f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0Nzk2OTksIm5iZiI6MTcxNDQ3OTM5OSwicGF0aCI6Ii8xMTQ5Nzg0NDAvMzI2NDI3MDUzLWViM2U5YmFkLTA2MWEtNGIxMC1hNzM4LWRlYmIwYTJkY2M5Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQzMFQxMjE2MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MDg5NWJiNTkxNzhmOTRiZDIxMjVhMjRjNmYxMzg4ZmM2ODM2OGZiZGFhMWRmMTczNzg3ZWI2N2U3OTcwZmQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.POXiecn6nJ5gre22cqmsMizLWwuYNQcTOBqpO0Vsk8M)

估计大大不是在大陆地区吧。我也没法使用代理录，填了端口号和启用IP地址也不行，clashverge的日志里没看到有任何afreeca的请求，pandalive也有这样的问题。对了，我没开系统代理。不过我使用另一个程序，不用系统代理，也能走clashverge的端口使用代理。建议大大搞个代理软件，不开系统代理的情况下，看看代理软件是否有看到afreeca和pandalive的请求

**Comment by ihmily** [comment]
>估计大大不是在大陆地区吧。我也没法使用代理录，填了端口号和启用IP地址也不行，clashverge的日志里没看到有任何afreeca的请求，pandalive也有这样的问题。对了，我没开系统代理。不过我使用另一个程序，不用系统代理，也能走clashverge的端口使用代理。建议大大搞个代理软件，不开系统代理的情况下，看看代理软件是否有看到afreeca和pandalive的请求

@xueli12 @yunhaihaihai 我确实不是大陆网络，但我刚在大陆的机器上 移动的网络挂代理试了一下 

当明确加上http:// 时能正常录制，不加确实会报错。

![image](https://github.com/ihmily/DouyinLiveRecorder/assets/114978440/67837307-589d-4401-905a-04404409a9bb)

**Comment by xueli12** [comment]
> > 估计大大不是在大陆地区吧。我也没法使用代理录，填了端口号和启用IP地址也不行，clashverge的日志里没看到有任何afreeca的请求，pandalive也有这样的问题。对了，我没开系统代理。不过我使用另一个程序，不用系统代理，也能走clashverge的端口使用代理。建议大大搞个代理软件，不开系统代理的情况下，看看代理软件是否有看到afreeca和pandalive的请求
> 
> @xueli12 @yunhaihaihai 我确实不是大陆网络，但我刚在大陆的机器上 移动的网络挂代理试了一下
> 
> 当明确加上http:// 时能正常录制，不加确实会报错。
> 
> ![image](https://private-user-images.githubusercontent.com/114978440/326828319-67837307-589d-4401-905a-04404409a9bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0ODQ3MzksIm5iZiI6MTcxNDQ4NDQzOSwicGF0aCI6Ii8xMTQ5Nzg0NDAvMzI2ODI4MzE5LTY3ODM3MzA3LTU4OWQtNDQwMS05MDVhLTA0NDA0NDA5YTliYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQzMFQxMzQwMzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MDk2YzdkZDE4ZDg5ZTQzZDQ4NDExNjEwZjBlNjM2OTMyOGIxNTVmZWM1Y2U5M2M4YTEyNjlhNTRhYjRhMjNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4nK3gemOn_gomSUibybyeAbOG4fVw3xU49sZPipRa8k)

我现在试了下，又行了，可以录了，加上http之后
![image](https://github.com/ihmily/DouyinLiveRecorder/assets/51438016/7c4d3337-de92-4d00-b722-d79f5d1c0166)

**Comment by xueli12** [comment]
> > 估计大大不是在大陆地区吧。我也没法使用代理录，填了端口号和启用IP地址也不行，clashverge的日志里没看到有任何afreeca的请求，pandalive也有这样的问题。对了，我没开系统代理。不过我使用另一个程序，不用系统代理，也能走clashverge的端口使用代理。建议大大搞个代理软件，不开系统代理的情况下，看看代理软件是否有看到afreeca和pandalive的请求
> 
> @xueli12 @yunhaihaihai 我确实不是大陆网络，但我刚在大陆的机器上 移动的网络挂代理试了一下
> 
> 当明确加上http:// 时能正常录制，不加确实会报错。
> 
> ![image](https://private-user-images.githubusercontent.com/114978440/326828319-67837307-589d-4401-905a-04404409a9bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0ODQ3MzksIm5iZiI6MTcxNDQ4NDQzOSwicGF0aCI6Ii8xMTQ5Nzg0NDAvMzI2ODI4MzE5LTY3ODM3MzA3LTU4OWQtNDQwMS05MDVhLTA0NDA0NDA5YTliYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQzMFQxMzQwMzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MDk2YzdkZDE4ZDg5ZTQzZDQ4NDExNjEwZjBlNjM2OTMyOGIxNTVmZWM1Y2U5M2M4YTEyNjlhNTRhYjRhMjNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4nK3gemOn_gomSUibybyeAbOG4fVw3xU49sZPipRa8k)

确实可以了，我加上了http好了

**Comment by ihmily** [comment]
> > > 估计大大不是在大陆地区吧。我也没法使用代理录，填了端口号和启用IP地址也不行，clashverge的日志里没看到有任何afreeca的请求，pandalive也有这样的问题。对了，我没开系统代理。不过我使用另一个程序，不用系统代理，也能走clashverge的端口使用代理。建议大大搞个代理软件，不开系统代理的情况下，看看代理软件是否有看到afreeca和pandalive的请求
> > 
> > 
> > @xueli12 @yunhaihaihai 我确实不是大陆网络，但我刚在大陆的机器上 移动的网络挂代理试了一下
> > 当明确加上http:// 时能正常录制，不加确实会报错。
> > ![image](https://private-user-images.githubusercontent.com/114978440/326828319-67837307-589d-4401-905a-04404409a9bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0ODQ3MzksIm5iZiI6MTcxNDQ4NDQzOSwicGF0aCI6Ii8xMTQ5Nzg0NDAvMzI2ODI4MzE5LTY3ODM3MzA3LTU4OWQtNDQwMS05MDVhLTA0NDA0NDA5YTliYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQzMFQxMzQwMzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MDk2YzdkZDE4ZDg5ZTQzZDQ4NDExNjEwZjBlNjM2OTMyOGIxNTVmZWM1Y2U5M2M4YTEyNjlhNTRhYjRhMjNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4nK3gemOn_gomSUibybyeAbOG4fVw3xU49sZPipRa8k)
> 
> 确实可以了，我加上了http好了

我用国内机器挂代理，录制很容易中断，而且录制出来会卡顿和跳帧。反之直连或者节点网速快，录制出来没任何问题，录制了四个多小时都非常流畅。总之，访问外网网速问题影响很大
