### ISSUE TITLE
抖音直播添加解析失败

### ISSUE THREAD

**Issue by fgo1212** [ihmily/DouyinLiveRecorder#334]
抖音直播添加解析失败，例子https://live.douyin.com/Pc_cold

**Comment by ihmily** [comment]
这个直播间比较特殊
正常抖音直播间地址都是 https://live.douyin.com/+一串数字， 可能要做特殊处理

**Comment by lxr760** [comment]
> 这个直播间比较特殊 正常抖音直播间地址都是 [https://live.douyin.com/+一串数字，](https://live.douyin.com/+%E4%B8%80%E4%B8%B2%E6%95%B0%E5%AD%97%EF%BC%8C) 可能要做特殊处理

不是比较特殊，是抖音直播间的链接有2种：1种是https://live.douyin.com/+抖音ID号，还有一种是https://live.douyin.com/+直播间号

**Comment by ihmily** [comment]
> 抖音直播添加解析失败，例子https://live.douyin.com/Pc_cold

这个直播间貌似没有开通直播权限，或者被官方关掉了直播权限

**Comment by ihmily** [comment]
> > 这个直播间比较特殊 正常抖音直播间地址都是 [https://live.douyin.com/+一串数字，](https://live.douyin.com/+%E4%B8%80%E4%B8%B2%E6%95%B0%E5%AD%97%EF%BC%8C) 可能要做特殊处理
> 
> 不是比较特殊，是抖音直播间的链接有2种：1种是[https://live.douyin.com/+抖音ID号，还有一种是https://live.douyin.com/+直播间号](https://live.douyin.com/+%E6%8A%96%E9%9F%B3ID%E5%8F%B7%EF%BC%8C%E8%BF%98%E6%9C%89%E4%B8%80%E7%A7%8D%E6%98%AFhttps://live.douyin.com/+%E7%9B%B4%E6%92%AD%E9%97%B4%E5%8F%B7)

111 嗯 正常两种都可以用来录制
