### ISSUE TITLE
douyin录制画质非原画，附原因和参考代码供参考

### ISSUE THREAD

**Issue by xueli12** [ihmily/DouyinLiveRecorder#338]
经测试douyin录制画质非原画，下面对于同一个直播间进行测试对比：
如下图为使用本程序录制的视频的码率信息，并非原画画质，画质低很多，原因在于通过flv_url_list = stream_url['flv_pull_url']获取到的流的信息中并不包含原画：
![image](https://github.com/ihmily/DouyinLiveRecorder/assets/51438016/23ddc82e-524b-4f4c-a563-02d7e7b6be1a)

下面这两个为使用其他两个不同的程序录制的视频的码率信息，均为原画画质：
![image](https://github.com/ihmily/DouyinLiveRecorder/assets/51438016/f51ba4f7-cc64-4b4a-8cc6-28d73aaee5cb)
![image](https://github.com/ihmily/DouyinLiveRecorder/assets/51438016/3419e362-fd00-46a2-a8e9-660eb2343889)

最后附上能获取到douyin原画直播流的项目的代码供大大参考：

第一个是https://github.com/biliup/biliup/blob/master/biliup/plugins/douyin.py
其中biliup这段代码的逻辑是在原画获取不到时会优先选最低一档的画质，建议在参考biliup代码的的基础上在origin画质获取不到时选择uhd画质，从高到低选择

第二个是
https://github.com/hr3lxphr6j/bililive-go/blob/master/src/live/douyin/douyin.go
看不太懂代码

**Comment by xueli12** [comment]
出现类似的问题的issue：https://github.com/ihmily/DouyinLiveRecorder/issues/321

**Comment by lxr760** [comment]
关于画质，我在另外一个项目里提过。那个作者说蓝光是最高画质，原画并不是最高。        但抖音web或者app画质选项里原画都是排在最上面的

https://github.com/OriX6/liveRecordAuto/issues/23

**Comment by ihmily** [comment]
>最后附上能获取到douyin原画直播流的项目的代码供大大参考：
>第一个是https://github.com/biliup/biliup/blob/master/biliup/plugins/douyin.py
其中biliup这段代码的逻辑是在原画获取不到时会优先选最低一档的画质，建议在参考biliup代码的的基础上在origin画质获取不到时选择uhd画质，从高到低选择
>
>第二个是
>https://github.com/hr3lxphr6j/bililive-go/blob/master/src/live/douyin/douyin.go
>看不太懂代码

### 一

emmm...本项目录制一直都是遵循 从高到低 进行画质选择的呀，没有对应画质就下一档，录制软件内的画质设置也是相对的，画质按照直播间支持的画质从高到低。不止抖音平台，本项目支持录制的其他10多个平台，全都是采用该策略进行录制的，没有对应画质，就自动适配录制下一档的画质。

在本软件中 蓝光(原画)>超清>高清>标清>流畅 依次类推 ，配置文件中的画质与直播间画质有时不是一一对应的，只是代表每一档阶梯的画质，其中蓝光和原画是一样的。录制时，如果你配置的是录制蓝光/原画 画质，那么代表你要录制第一档的画质，你配置的是录制超清画质，那么代表录制第二档画质。

举个例子：
比如上面的第一档画质和第二档画质，如果直播间支持 蓝光、超清等画质，那么第一档画质就是蓝光，第二档画质就是超清，此时是一一对应。

但如果这个直播间本身最高只有高清画质，然后就是流畅画质，你在软件中配置的蓝光或者原画录制，实际上录制的是高清画质，而配置成超清录制，实际录制的是流畅画质，因为此时第一档画质就是高清，第二档画质是流畅。

总之，你只需要确定，如果要录制最高画质，那配置为原画或者蓝光即可。想要录制第二高画质，那么配置成超清即可


### 二

看了一下你贴的两个项目的代码，其实三个项目获取直播源的方式都是一样的，都是使用同一个接口解析的数据，至于你说的本项目和另外两个项目相比 录制的码率更低，我去测试了一下，发现是我获取直播流数据后，解析数据的时候，把最高画质给漏掉了，几个月前有人提过 https://github.com/ihmily/DouyinLiveRecorder/issues/141   当时我没认真看 /(ㄒoㄒ)/~~ 现在已经修复该问题，更新到3.0.4版本。

**Comment by fqyy10** [comment]
老哥，抖音的ttwid不会抓取，b站跟我的不一样，我的一直是bd ticjet

**Comment by ihmily** [comment]
> 老哥，抖音的ttwid不会抓取，b站跟我的不一样，我的一直是bd ticjet

@fqyy10 ttwid不是很重要，在浏览器复制一个写死就行，或者直接用我的ttwid
