### ISSUE TITLE
申请新平台（流星直播）

### ISSUE THREAD

**Issue by justdoiting** [ihmily/DouyinLiveRecorder#341]
7u66.com

和bigo直播很像，网页版用猫抓就能抓源，而且都是只有一条源，画质比bigo好很多，bigo是m3u8源，流星直播是flv源

**Comment by ihmily** [comment]
> 7u66.com
> 
> 和bigo直播很像，网页版用猫抓就能抓源，而且都是只有一条源，画质比bigo好很多，bigo是m3u8源，流星直播是flv源

3.0.4版本已新增流星直播录制
