### ISSUE TITLE
does Docker TwitCasting need cookies?

### ISSUE THREAD

**Issue by theandychung** [ihmily/DouyinLiveRecorder#346]
Docker建立時不知道為什麼沒有URL_config.ini
![image](https://github.com/ihmily/DouyinLiveRecorder/assets/18351023/616b53d1-423b-496a-b845-2389fb94fe69)

自建一個URL_config.ini放入一個正在進行的twitcast URL後得到error
請問是否需要自建一個cookies放入？
如果是，請問放入何處？

謝謝

以下為log

<details>
  <summary>
    Log
  </summary>
<code>
-----------------------------------------------------
|                DouyinLiveRecorder                 |
-----------------------------------------------------
版本号: v3.0.4
GitHub: https://github.com/ihmily/DouyinLiveRecorder
支持平台: 
国内站点：抖音|快手|虎牙|斗鱼|YY|B站|小红书|bigo|blued|网易CC|千度热播|猫耳FM|Look|TwitCasting|百度|微博|酷狗|LiveMe|花椒|流星
海外站点：TikTok|AfreecaTV|PandaTV|WinkTV|FlexTV|PopkonTV|TwitchTV
.....................................................
系统代理检测中，请耐心等待...
已备份配置文件 ./config/config.ini 到 ./backup_config/config.ini_2024-05-08_14-06-12
已备份配置文件 ./config/URL_config.ini 到 ./backup_config/URL_config.ini_2024-05-08_14-06-12
全局/规则网络代理已开启√
运行新线程,传入地址 https://twitcasting.tv/katyuhyan
获取TwitCasting数据失败，正在尝试登录...
2024-05-08 14:06:15.969 | ERROR    | utils:wrapper:18 - 错误信息: type: RuntimeError, TwitCasting登录失败,请检查配置文件中的账号密码是否正确 in function get_twitcasting_stream_url at line: 1500
2024-05-08 14:06:15.970 | ERROR    | __main__:start_record:1506 - 错误信息: 'list' object has no attribute 'get' 发生错误的行数: 1073
共监测1个直播中 | 同一时间访问网络的线程数: 3 | 是否开启代理录制: 是 | 是否生成时间文件: 否 | 录制视频质量为: 原画 | 录制视频格式为: TS | 目前瞬时错误数为: 1 | 当前时间: 2024-05-08 14:06:23
没有正在录制的直播 14:06:23
共监测1个直播中 | 同一时间访问网络的线程数: 3 | 是否开启代理录制: 是 | 是否生成时间文件: 否 | 录制视频质量为: 原画 | 录制视频格式为: TS | 目前瞬时错误数为: 1 | 当前时间: 2024-05-08 14:06:33
没有正在录制的直播 14:06:33
</code>
</details>

**Comment by ihmily** [comment]
`2024-05-08 14:06:15.969 | ERROR    | utils:wrapper:18 - 错误信息: type: RuntimeError, TwitCasting登录失败,请检查配置文件中的账号密码是否正确 in function get_twitcasting_stream_url at line: 1500`

正如错误所示，你是否有在config.ini配置你的witCasting账号密码呢？

![image](https://github.com/ihmily/DouyinLiveRecorder/assets/114978440/52de3b80-8270-4681-995b-2f43bc7a9074)

配置好，会进行自动登录并且更新cookie到配置文件中，无需你自己填写cookie。

**Comment by theandychung** [comment]
了解
我的config.ini裡面是空的
可能是因系統只有英文造成
明天我從git下載config.ini後試試



#307 #309 提到URL_config.ini的問題很可能跟我建立container時也找不到URL_config.ini有關

**Comment by theandychung** [comment]
不曉得為什麼今天repull後看config.ini竟然不是空的
之前不曉得為什麼是空的
照著 #349 做使用email來登入twitcast
但好像無法成功
用cookies的方式有成功登入錄製
謝謝
