### ISSUE TITLE
您好博主，在使用说明里有一段话我不太理解。

### ISSUE THREAD

**Issue by misslinasffgg** [ihmily/DouyinLiveRecorder#350]
“如果要长时间挂着软件循环监测直播，最好循环时间设置长一点（咱也不差没记录到那几分钟），避免因请求间歇导致被官方封禁IP”  
我是萌新，我比较笨，遇事喜欢钻牛角尖。假设 我录制一个抖音直播，主播因为卡了自动关播了。这时候这个循环监测就开始运行了？我能这么理解吗？这个循环检测是打开录制时全程触发，还是只有主播网络卡顿断波才会触发？能给一个检测间隔参考值吗？

**Comment by misslinasffgg** [comment]
能给我一个检测间隔参考值吗

**Comment by ihmily** [comment]
> 假设 我录制一个抖音直播，主播因为卡了自动关播了。这时候这个循环监测就开始运行了？我能这么理解吗？

1、可以这么理解。如果主播下播了，这个循环检测时间就是请求抖音获取主播是否开播的频率。如果设置为0，那么当主播因为网络或者其他问题中断了录制，程序会瞬间重新检测主播是否开播，如果主播此时在播那么会开始进行录制。

2、这个检测值说实话不太好定，正常使用默认值就好

**Comment by ihmily** [comment]
3、循环检测是针对检测判断主播是否正在直播的，已经在录制中，就不会去检测，当主播下播，这个循环检测又会开始检测了，如果设置为120，那么就表示每隔120秒，检测一下主播是否开播，开播就自动启动录制。

**Comment by misslinasffgg** [comment]
> 3、循环检测是针对检测判断主播是否正在直播的，已经在录制中，就不会去检测，当主播下播时，这个循环检测又会开始检测了，如果设置为120，那么就表示每次120秒，检测一下主播是否开播，开播就自动启动录制。

好的我明白了，十分感谢！
