### ISSUE TITLE
returned non-zero exit status

### ISSUE THREAD

**Issue by AiTurLing** [ihmily/DouyinLiveRecorder#351]
发生在main.py;
ffmpeg_command.extend(command)
_output = subprocess.check_output(ffmpeg_command, stderr=subprocess.STDOUT)
record_finished = True
except subprocess.CalledProcessError as e:
logger.error(f"错误信息: {e} 发生错误的行数: {e.__traceback__.tb_lineno}")

其中行数对应着ffmpeg_command.extend(command)这一行，切换录制格式报错行数变化

returned non-zero exit status 4294967158. 发生错误的行数: 1309

Command '['ffmpeg', '-y', '-v', 'verbose', '-rw_timeout', '30000000', '-loglevel', 'error', '-hide_banner', '-user_agent', 'Mozilla/5.0 (Linux; Android 11; SAMSUNG SM-G973U) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/14.2 Chrome/87.0.4280.141 Mobile Safari/537.36', '-protocol_whitelist', 'rtmp,crypto,file,http,https,tcp,tls,udp,rtp', '-thread_queue_size', '1024', '-analyzeduration', '20000000', '-probesize', '10000000', '-fflags', '+discardcorrupt', '-i', 'http://pull-hls-l26.douyincdn.com/third/stream-691563734398665190/index.m3u8?expire=6644b334&sign=8119ec76a608e6d443ba2b9dab40524b', '-bufsize', '8000k', '-sn', '-dn', '-reconnect_delay_max', '60', '-reconnect_streamed', '-reconnect_at_eof', '-max_muxing_queue_size', '1024', '-correct_ts_overflow', '1', '-c:v', 'copy', '-c:a', 'aac', '-map', '0', '-f', 'segment', '-segment_time', '1800', '-segment_format', 'mp4', '-reset_timestamps', '1', 'F:/DouyinLiveRecorder.v3.0.4/downloads/抖音直播/摸鱼奎恩/摸鱼奎恩_2024-05-08_21-05-56_%03d.mp4']'

**Comment by ihmily** [comment]
重启软件，重试一下

**Comment by AiTurLing** [comment]
> 重启软件，重试一下

重试了，用管理员权限也没有好

**Comment by AiTurLing** [comment]
并且刚开始是ok，我在另一个盘里开启了另一个直播间的录制，用ctrl+c关掉第一个后发生报错，之后一直无法录制
并且仅限这个直播间一直无法录制

**Comment by ihmily** [comment]
@AiTurLing 使用最新3.0.5版本，已修复该问题。

**Comment by AiTurLing** [comment]
> @AiTurLing 使用最新3.0.5版本，已修复该问题。

感谢大佬，好快的修复！
