### ISSUE TITLE
日志文件太大

### ISSUE THREAD

**Issue by JeffersonYoung** [ihmily/DouyinLiveRecorder#352]
作者您好，项目在后台录制的时候5秒就输出一个日志项，几天就十几兆了，文本编辑器打开都很困难，是否可以考虑降低日志输出的频率

**Comment by ihmily** [comment]
@JeffersonYoung 已修改为 按日志文件大小进行文件分割， 300KB和500KB 分割一个文件，超过2个文件自动删除。
