### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by MysticalY** [ihmily/DouyinLiveRecorder#353]
你好直播地址复制完运行报错
![7ccc5afef279fd74df44abb6e56350f](https://github.com/ihmily/DouyinLiveRecorder/assets/94030032/5c82cfb7-0406-4d30-9b5b-9102734820f3)

**Comment by ihmily** [comment]
@MysticalY  我这是正常的，和你同样的直播间地址

![image](https://github.com/ihmily/DouyinLiveRecorder/assets/114978440/ace03d12-2925-4e82-9822-bfe45ae9aa69)
![image](https://github.com/ihmily/DouyinLiveRecorder/assets/114978440/d90a485c-ca14-4f0e-bdc2-14379a47e4c9)
![image](https://github.com/ihmily/DouyinLiveRecorder/assets/114978440/6406a885-03df-43f0-86ad-4a8f7c292969)

**Comment by MysticalY** [comment]
好嘞我又重新下载了一遍可以录制了谢谢

**Comment by ihmily** [comment]
> 好嘞我又重新下载了一遍可以录制了谢谢

有部分直播间还是会这样报错，这是一个bug，请重新下载最新3.0.5修复版 
https://github.com/ihmily/DouyinLiveRecorder/releases/tag/v3.0.5
