### ISSUE TITLE
afreeecatv的cookie和账号密码登录问题

### ISSUE THREAD

**Issue by fqyy10** [ihmily/DouyinLiveRecorder#358]
请教，账号密码登录和cookie是两个任意选一个填写到con
![屏幕截图 2024-05-10 162218](https://github.com/ihmily/DouyinLiveRecorder/assets/168750978/fc3533b9-f283-4c5b-862c-3c6820ae9638)
fig文件里面吗   然后。cookie的获取的话不知道现在版本获取啥   我是利用登录账号获取的，自动填写的cookie，就成这样了

**Comment by ihmily** [comment]
> 请教，账号密码登录和cookie是两个任意选一个填写到con ![屏幕截图 2024-05-10 162218](https://private-user-images.githubusercontent.com/168750978/329527069-fc3533b9-f283-4c5b-862c-3c6820ae9638.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzMzI0NzEsIm5iZiI6MTcxNTMzMjE3MSwicGF0aCI6Ii8xNjg3NTA5NzgvMzI5NTI3MDY5LWZjMzUzM2I5LWYyODMtNGM1Yi04NjJjLTNjNjgyMGFlOTYzOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMFQwOTA5MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNzQyNWMwZGM5ZWU5YjQxNDgxZjk4YWVkYTBiNmI5ZTExOTlkN2VlNTk5ZDEzOWZjOWM4ZmExM2U1MjJmMThhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.U--HsGoqXy9Xq6xJd4BWjWSrzQlEtWDIcQHLATorTOo) fig文件里面吗 然后。cookie的获取的话不知道现在版本获取啥 我是利用登录账号获取的，自动填写的cookie，就成这样了

配置好账号密码，程序会自动登录获取cookie，当然你也可以自己在网页获取登录账号后的cookie。你这个应该已经正常登录并获取到了cookie，而且已经解析到了直播源地址，但是在开始录制的过程中出错了。

**这个直播间地址是什么？方便发一下吗？**

**Comment by fqyy10** [comment]
对，cookie已经获取到了，直播地址换了好几个都是这样。。我也不清楚为什么这是
