### ISSUE TITLE
抖音录制画质似乎只能高清（1280*720）

### ISSUE THREAD

**Issue by ln-233** [ihmily/DouyinLiveRecorder#360]
浏览器登陆抖音最高画质显示为原画，但是软件录制后的视频只有高清，抖音cookies已经配置，软件配置项如下:
![image](https://github.com/ihmily/DouyinLiveRecorder/assets/116275655/00e49b4b-c2f7-4d6a-825b-3c9f6e13ada2)
![image](https://github.com/ihmily/DouyinLiveRecorder/assets/116275655/bc05517b-64f3-4703-9da7-24bf4bfcb546)

**Comment by ihmily** [comment]
是最新3.0.5版本吗？试试其他直播间，游戏直播间试试。

**Comment by ihmily** [comment]
试了一下其他csgo直播间，可以正常录制原画的 

![image](https://github.com/ihmily/DouyinLiveRecorder/assets/114978440/061d29fa-e26a-4635-b405-cfd2b635ab67)

![image](https://github.com/ihmily/DouyinLiveRecorder/assets/114978440/7615c90b-405e-4a54-8358-9dc5b4b72bb6)

![image](https://github.com/ihmily/DouyinLiveRecorder/assets/114978440/26d89567-451e-42bf-ac49-600adbd8de9d)
