### ISSUE TITLE
希望支援twitcast登錄的另一個入口

### ISSUE THREAD

**Issue by brina60602** [ihmily/DouyinLiveRecorder#365]
一般登錄
https://twitcasting.tv/indexcaslogin.php
第三方登錄(推特註冊的帳號可登入)
https://twitcasting.tv/indexpasswordlogin.php
希望設定檔能支援這個第三方登錄的入口,用cookie太容易失效了

**Comment by ihmily** [comment]
下个版本更新这个功能
