### ISSUE TITLE
大佬直接报错了是怎么回事

### ISSUE THREAD

**Issue by Guan-jinquan** [ihmily/DouyinLiveRecorder#370]
![QQ截图20240516231255](https://github.com/ihmily/DouyinLiveRecorder/assets/60465438/ee3cb585-88de-41ec-90c7-212bf33c84b0)

**Comment by qazgp** [comment]
ip被ban了 不知道咋搞 我也是，你用浏览器进下快手呢，估计要输验证码

**Comment by ihmily** [comment]
快手风控这个问题暂时解决不了，频繁一点就这样了
