### ISSUE TITLE
pandatv 录制   输入cookie后还是  一直显示 “未知链接，已跳过” 

### ISSUE THREAD

**Issue by misslinasffgg** [ihmily/DouyinLiveRecorder#383]
![QQ截图20240527221115](https://github.com/ihmily/DouyinLiveRecorder/assets/153790355/27331c48-25b0-4f58-8b72-52ed27db203f)
![QQ截图20240527221535](https://github.com/ihmily/DouyinLiveRecorder/assets/153790355/1138d97b-3deb-4b3e-a887-74ce6749b485)
我是小白，第一次接触cookie，我跟着网上的获取cookie教程 成功看到pandatv的cookie值，但我输入config.ini里面后还是未能识别网站。在此请教博主，解答疑惑。

**Comment by misslinasffgg** [comment]
多次输入屡次失败，不知道是哪个步骤出了差错或漏了哪些操作

**Comment by ihmily** [comment]
你改一下地址，把其中的m.pandalive.co.kr 改成 www.pandalive.co.kr

**Comment by misslinasffgg** [comment]
> 你改一下地址，把其中的m.pandalive.co.kr改成[www.pandalive.co.kr](http://www.pandalive.co.kr)

很感谢博主，更换部分地址后成功检测并录制。十分感谢。

**Comment by xueli12** [comment]
你的cookie泄露了
