### ISSUE TITLE
TikTok录制检测到主播，开始录制，但过了几秒后提示请检查网络。

### ISSUE THREAD

**Issue by d5f4sd6f84dfa** [ihmily/DouyinLiveRecorder#388]
![1](https://github.com/ihmily/DouyinLiveRecorder/assets/168329204/60893989-2eba-45cb-ae8a-f4c17bba160c)
都已经检测到了，网络是可以访问TIKTOK的啊，怎么直接不录了。

**Comment by pcxjsl** [comment]
最近才出现的我也是这个错误，tiktok平台肯定更新了什么，这个就需要作者更新了唉。坐等大佬看一下

**Comment by catfish1112322** [comment]
我也不行，修改画质也没用

**Comment by 2013Ming** [comment]
同问，有解决办法了吗
