### ISSUE TITLE
启动后一直报错，无法录制直播。

### ISSUE THREAD

**Issue by ilikeulinux** [ihmily/DouyinLiveRecorder#39]
![QQ截图20230912185252](https://github.com/ihmily/DouyinLiveRecorder/assets/41497656/60ef0152-c0da-4dcf-93b8-188f3a5f1776)
![QQ截图20230912185650](https://github.com/ihmily/DouyinLiveRecorder/assets/41497656/c970975e-25f5-4c3e-8bfb-719e7b91e779)

**Comment by C222ZZZ** [comment]
我也是一样这个错误，感觉好像读取分析链接的方法报的错误
