### ISSUE TITLE
pandatv如何強制1080P?

### ISSUE THREAD

**Issue by yuka46** [ihmily/DouyinLiveRecorder#392]
各位前輩好
pandatv某些主播剛開台 只能抓取到720P
但實際上是可以抓取1080P 這樣導致要關掉再重開
請問如何單關或重新獲取單一主播的直播間源?
如果掛50台以上 關掉重開會導致某些主播直播間要排隊才能接續著錄製
因為 我不太懂"超清 高清"的區別 1080P ? 720P?
"超清 高清"我都試過了 最後都是720P 只有"原画"才能抓取1080P
我知道這是免費的 不要要求太多 但我希望有KBJ同好能解決我這小問題
有償的

**Comment by ihmily** [comment]
正常来说 填写原画或者蓝光就是录制程序约定的最高画质，
画质按下面排名依次降低：
原画>超清>高清>标清>流畅

**Comment by ihmily** [comment]
另外，以1080p和720p为清晰度标准并不准确，经测试平台有时候会出现1080p 30fps的码率 比 720p fps的码率 更低的情况，那么此时原画可能就是720P的，而超清是1080P的，录制程序按码率排名为准，并且是否为1080p也要看主播开播的设置，如果开播并未设置1080P，也是无法录制到1080P的，这样强制1080P没有意义。

**Comment by yuka46** [comment]
> 另外，以1080p和720p为清晰度标准并不准确，经测试平台有时候会出现1080p 30fps的码率 比 720p fps的码率 更低的情况，那么此时原画可能就是720P的，而超清是1080P的，录制程序按码率排名为准，并且是否为1080p也要看主播开播的设置，如果开播并未设置1080P，也是无法录制到1080P的，这样强制1080P没有意义。
ihmily 謝謝你的回覆 我知道問題在哪 也自行解決了
