### ISSUE TITLE
tiktok cookies

### ISSUE THREAD

**Issue by broklin48** [ihmily/DouyinLiveRecorder#393]
where should i put tiktok cookie? 1 or 2?
and what is that in the green box?

**Comment by ihmily** [comment]
If there are no issues with recording, you can skip adding cookies

If you want to add a cookie, please fill it out in `DouyinLiveRecorder/config/config.ini`

![image](https://github.com/ihmily/DouyinLiveRecorder/assets/114978440/91317d47-7d66-4a6a-bcdb-a9ed619133bc)
