### ISSUE TITLE
错误信息644:list index out of range

### ISSUE THREAD

**Issue by 20082010** [ihmily/DouyinLiveRecorder#40]
下午发现又开始报错了。同时还发现一个bug。同一时间进程数，会在每次刷新时重置。辛苦这个一起看一下吧。
![image](https://github.com/ihmily/DouyinLiveRecorder/assets/3966324/f4b2984b-147a-4db9-8a2c-2ec29d0c7eeb)

**Comment by zhangqweb** [comment]
get_douyin_stream_data方法改下抓取就可以
