### ISSUE TITLE
TikTok Error

### ISSUE THREAD

**Issue by Amarin2244** [ihmily/DouyinLiveRecorder#403]
Error when starting
![2024-06-08_011808](https://github.com/ihmily/DouyinLiveRecorder/assets/62793341/782c35a1-8b8b-4c42-9c46-b57c49dc7909)

**Comment by X-oliver** [comment]
i got the same error,但是浏览器可以访问

**Comment by d5f4sd6f84dfa** [comment]
i got the same error，作者表示测试过没有问题可以正常录制

**Comment by Andy8r0X** [comment]
設置cookies

**Comment by ihmily** [comment]
下载 https://github.com/ihmily/DouyinLiveRecorder/releases/download/v3.0.5/DouyinLiveRecorder.v3.0.5-fix.zip

**Comment by prov3it** [comment]
> 下载 https://github.com/ihmily/DouyinLiveRecorder/releases/download/v3.0.5/DouyinLiveRecorder.v3.0.5-fix.zip

Docker image still has this issue.

**Comment by Amarin2244** [comment]
The Solution is : Cookies ( you need new cookie from other acc to replace when it get error)
when i replace cookies it worked!!
And i also tested on new reased : Work smooth
Thanks Devs

**Comment by d5f4sd6f84dfa** [comment]
> The Solution is : Cookies ( you need new cookie from other acc to replace when it get error) when i replace cookies it worked!! And i also tested on new reased : Work smooth Thanks Devs

 你的意思是要登录自己的tiktok账号，再把登录好的cookies添加？

**Comment by prov3it** [comment]
> The Solution is : Cookies ( you need new cookie from other acc to replace when it get error) when i replace cookies it worked!! And i also tested on new reased : Work smooth Thanks Devs

translated: Do you mean to log in to your tiktok account and then add the logged-in cookies?

Could you share your config.ini?

**Comment by d5f4sd6f84dfa** [comment]
> > The Solution is : Cookies ( you need new cookie from other acc to replace when it get error) when i replace cookies it worked!! And i also tested on new reased : Work smooth Thanks Devs
> 
> translated: Do you mean to log in to your tiktok account and then add the logged-in cookies?
> 
> Could you share your config.ini?

![image](https://github.com/ihmily/DouyinLiveRecorder/assets/168329204/5c88f253-36b8-4d2a-a4ba-d9d93aaadbd0)

**Comment by Amarin2244** [comment]
> > > The Solution is : Cookies ( you need new cookie from other acc to replace when it get error) when i replace cookies it worked!! And i also tested on new reased : Work smooth Thanks Devs
> > 
> > 
> > translated: Do you mean to log in to your tiktok account and then add the logged-in cookies?
> > Could you share your config.ini?
> 
> ![image](https://private-user-images.githubusercontent.com/168329204/340758005-5c88f253-36b8-4d2a-a4ba-d9d93aaadbd0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4NDQ1MjMsIm5iZiI6MTcxODg0NDIyMywicGF0aCI6Ii8xNjgzMjkyMDQvMzQwNzU4MDA1LTVjODhmMjUzLTM2YjgtNGQyYS1hNGJhLWQ5ZDkzYWFhZGJkMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyMFQwMDQzNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYWE0ODNjNmZlMzY4NTYyYTI3ZGIzZTBjZGRiZjQ4YmQ2M2MyODY2YTQ4Y2RkYzI1ZGViMDg2NDg1NmQxMjRjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CN-1XLpwXdTvCOBMtYQRyOinayQqRkDsRr726EwtFJQ)

Yes!
![test](https://github.com/ihmily/DouyinLiveRecorder/assets/62793341/8649fa09-cfec-495a-b94b-db0b37a08f36)

**Comment by d5f4sd6f84dfa** [comment]
> > > > 解决方案是：Cookies（当它出现错误时，您需要来自其他帐户的新cookie来替换）当我替换cookie时，它起作用了！我还测试了新的reased：工作顺利，谢谢开发人员
> > > 
> > > 
> > > 翻译：您的意思是登录您的 tiktok 帐户，然后添加登录的 cookie 吗？你能分享一下你config.ini吗？
> > 
> > 
> > ![图像](https://private-user-images.githubusercontent.com/168329204/340758005-5c88f253-36b8-4d2a-a4ba-d9d93aaadbd0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4NDQ1MjMsIm5iZiI6MTcxODg0NDIyMywicGF0aCI6Ii8xNjgzMjkyMDQvMzQwNzU4MDA1LTVjODhmMjUzLTM2YjgtNGQyYS1hNGJhLWQ5ZDkzYWFhZGJkMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyMFQwMDQzNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYWE0ODNjNmZlMzY4NTYyYTI3ZGIzZTBjZGRiZjQ4YmQ2M2MyODY2YTQ4Y2RkYzI1ZGViMDg2NDg1NmQxMjRjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CN-1XLpwXdTvCOBMtYQRyOinayQqRkDsRr726EwtFJQ)
> 
> 是的！ ![测试](https://private-user-images.githubusercontent.com/62793341/341234506-8649fa09-cfec-495a-b94b-db0b37a08f36.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4NDkzNzgsIm5iZiI6MTcxODg0OTA3OCwicGF0aCI6Ii82Mjc5MzM0MS8zNDEyMzQ1MDYtODY0OWZhMDktY2ZlYy00OTVhLWI5NGItZGIwYjM3YTA4ZjM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIwVDAyMDQzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExYmY0Y2Q1YjFmNDAwYjQ4MDYxNDU2NjBhMmJhYjFiNmJiNGNjNjg3ZDhkOGYzYzYyNzczMGRlYzc1ODA2N2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Od3QXy4CohTGXpLEdgORAgNvUKPnR0gHPP1G7kTKySQ)

![image](https://github.com/ihmily/DouyinLiveRecorder/assets/168329204/e42c4d6b-3237-4e11-ae77-a93cd67aa54d)
请问一下你的cookies是用什么浏览器，如何添加，我是从Network里的ZH-HANT-TW里添加的

**Comment by d5f4sd6f84dfa** [comment]
![image](https://github.com/ihmily/DouyinLiveRecorder/assets/168329204/a645dc6e-d304-4fa4-8c29-26bc86a6ff73)
我确认是从这里面加的cookies，但是加了没有用

**Comment by Amarin2244** [comment]
![2024-06-20_112947](https://github.com/ihmily/DouyinLiveRecorder/assets/62793341/68afa9c7-4551-4671-b78e-039cf723de20)

**Comment by d5f4sd6f84dfa** [comment]
![image](https://github.com/ihmily/DouyinLiveRecorder/assets/168329204/0bb27364-112c-4f99-b712-19d307770700)
我有好多条这个check，哪一条才是？还是随便一条都可以？

**Comment by Amarin2244** [comment]
> ![image](https://private-user-images.githubusercontent.com/168329204/341273861-0bb27364-112c-4f99-b712-19d307770700.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4NTkzNzAsIm5iZiI6MTcxODg1OTA3MCwicGF0aCI6Ii8xNjgzMjkyMDQvMzQxMjczODYxLTBiYjI3MzY0LTExMmMtNGY5OS1iNzEyLTE5ZDMwNzc3MDcwMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyMFQwNDUxMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NTRiZDUwZDIyMGEyNzc2NmFiZjM3YmQzNjE2Y2FjN2VmZjFiODRhZWE0NDg2YTVhMjkxY2UzZWI2MTIyZDM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nSKkkp2yZxQJMRdxfWYDqyTqRG_oLkc4-KKdvRv9qG0) I have multiple checks like this, which one should I use? Or any one will do?

It's the same cookie, Don't worry
Just choose one

**Comment by d5f4sd6f84dfa** [comment]
> > ![图像](https://private-user-images.githubusercontent.com/168329204/341273861-0bb27364-112c-4f99-b712-19d307770700.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4NTkzNzAsIm5iZiI6MTcxODg1OTA3MCwicGF0aCI6Ii8xNjgzMjkyMDQvMzQxMjczODYxLTBiYjI3MzY0LTExMmMtNGY5OS1iNzEyLTE5ZDMwNzc3MDcwMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyMFQwNDUxMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NTRiZDUwZDIyMGEyNzc2NmFiZjM3YmQzNjE2Y2FjN2VmZjFiODRhZWE0NDg2YTVhMjkxY2UzZWI2MTIyZDM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nSKkkp2yZxQJMRdxfWYDqyTqRG_oLkc4-KKdvRv9qG0)我有多个这样的支票，我应该使用哪一个？或者有人会做？
> 
> 是一样的饼干，不用担心，随便选一个

![image](https://github.com/ihmily/DouyinLiveRecorder/assets/168329204/c86b01a2-5a4c-47e7-b6fa-741f03dad0fa)
太棒了！真的可以，太感谢你了。
