### ISSUE TITLE
tiktok录屏还是不能用

### ISSUE THREAD

**Issue by wuxiongxiong805** [ihmily/DouyinLiveRecorder#405]
tiktok录屏还是不能用，还是一样的问题，外网是正常的，一开就提示错误

**Comment by ihmily** [comment]
我测试是正常的

![1718104158241](https://github.com/ihmily/DouyinLiveRecorder/assets/114978440/ce8b3675-8449-4deb-aa4c-55f6a0cbc4b6)

**Comment by Andy8r0X** [comment]
设置tiktok_cookie

**Comment by wuxiongxiong805** [comment]
> 设置tiktok_cookie

现在要设置了吗？

**Comment by wuxiongxiong805** [comment]
> 我测试是正常的
> 
> ![1718104158241](https://private-user-images.githubusercontent.com/114978440/338557507-ce8b3675-8449-4deb-aa4c-55f6a0cbc4b6.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxNzcxODYsIm5iZiI6MTcxODE3Njg4NiwicGF0aCI6Ii8xMTQ5Nzg0NDAvMzM4NTU3NTA3LWNlOGIzNjc1LTg0NDktNGRlYi1hYTRjLTU1ZjZhMGNiYzRiNi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMlQwNzIxMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MDU1NGI2ODFhYjM1ZjQwMGMwMTQ0OWI4M2JiYTY3ZGI1OGUxODdlNzFjMjRmNTA3ZjI1ZDU1MzZhY2E4MTZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Ku4IMxi36vkqhDyonpgVUeCHpPvN23B95Y8uYlLtyr0)

你那是如何设置的

**Comment by Andy8r0X** [comment]
> > 设置tiktok_cookie
> 
> 现在要设置了吗？

config\config.ini
同一时间访问网络的线程数，降为1
循环时间(秒)，降低速率超过200以上
tiktok_cookie填上浏览器无痕访客的cookie值

**Comment by d5f4sd6f84dfa** [comment]
![11](https://github.com/ihmily/DouyinLiveRecorder/assets/168329204/bbb3ed43-6f5f-4155-b145-99851eadd873)
jie'l
借楼，cookies怎么获取，我是google浏览器无痕F12，但是不知道哪一个是

**Comment by d5f4sd6f84dfa** [comment]
借楼，已经用EDGE无痕模式打开（没有登录账号），选取了cookies并设置，但还是提示录制错误，请检查网络（网络正常）
![11](https://github.com/ihmily/DouyinLiveRecorder/assets/168329204/25613703-c77b-4232-8e7f-a78b70130dbf)

**Comment by Andy8r0X** [comment]
> 借楼，已经用EDGE无痕模式打开（没有登录账号），选取了cookies并设置，但还是提示录制错误，请检查网络（网络正常） 
太多请求ip被风控，电脑换ip，降低循环时间可以解决问题

**Comment by d5f4sd6f84dfa** [comment]
> > 借楼，已经用EDGE无痕模式打开（没有登录账号），选取了cookies并设置，但还是提示录制错误，请检查网络（网络正常）
> 
> 太多请求ip被风控，电脑换ip，降低循环时间可以解决问题

换的是本地网络的IP还是梯子的IP？

**Comment by Andy8r0X** [comment]
> > > 借楼，已经用EDGE无痕模式打开（没有登录账号），选取了cookies并设置，但还是提示录制错误，请检查网络（网络正常）
> > 
> > 
> > 太多请求ip被风控，电脑换ip，降低循环时间可以解决问题
> 
> 换的是本地网络的IP还是梯子的IP？

换梯子IP

先试试新版本 V3.0.5-fix
https://github.com/ihmily/DouyinLiveRecorder/releases/download/v3.0.5/DouyinLiveRecorder.v3.0.5-fix.zip

**Comment by d5f4sd6f84dfa** [comment]
2024-06-14 18:40:12.174 | ERROR    | __main__:start_record:1328 - 错误信息: Command '['ffmpeg', '-y', '-v', 'verbose', '-rw_timeout', '30000000', '-loglevel', 'error', '-hide_banner', '-user_agent', 'Mozilla/5.0 (Linux; Android 11; SAMSUNG SM-G973U) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/14.2 Chrome/87.0.4280.141 Mobile Safari/537.36', '-protocol_whitelist', 'rtmp,crypto,file,http,https,tcp,tls,udp,rtp', '-thread_queue_size', '1024', '-analyzeduration', '40000000', '-probesize', '20000000', '-fflags', '+discardcorrupt', '-i', 'http://pull-f5-tt01.tiktokcdn-us.com/stage/stream-3574081738877436848_or4.flv?expire=1719571204&sign=17bf1776040b559eae267bcad43e1c34', '-bufsize', '15000k', '-sn', '-dn', '-reconnect_delay_max', '60', '-reconnect_streamed', '-reconnect_at_eof', '-max_muxing_queue_size', '2048', '-correct_ts_overflow', '1', '-c:v', 'copy', '-c:a', 'aac', '-map', '0', '-f', 'segment', '-segment_time', '1200', '-segment_format', 'mp4', '-reset_timestamps', '1', 'D:/Software installation/DouyinLiveRecorder v3.0.5-fix/DouyinLiveRecorder.v3.0.5-fix/downloads/TikTok直播/HappyAbellaGrace-happyabellagrace/HappyAbellaGrace-happyabellagrace_2024-06-14_18-40-06_%03d.mp4']' returned non-zero exit status 4294967158. 发生错误的行数: 1325
求解答，这个报错是什么意思？

**Comment by ihmily** [comment]
可以看到你已经获取到了直播源地址：http://pull-f5-tt01.tiktokcdn-us.com/stage/stream-3574081738877436848_or4.flv?expire=1719571204&sign=17bf1776040b559eae267bcad43e1c34

录制的时候出错了，还是网络问题，我拿你获取到的直播源链接到在线播放器 是正常播放的
![image](https://github.com/ihmily/DouyinLiveRecorder/assets/114978440/0b563935-3a5c-43a3-a60e-55e2742a11a3)

且我拿你获取的直播源 录制正常
![image](https://github.com/ihmily/DouyinLiveRecorder/assets/114978440/33466ce1-9c0c-46c5-a8c4-09d377afed96)

节点延迟以及网速、协议等相关

**Comment by d5f4sd6f84dfa** [comment]
> 可以看到你已经获取到了直播源地址：http://pull-f5-tt01.tiktokcdn-us.com/stage/stream-3574081738877436848_or4.flv?expire=1719571204&sign=17bf1776040b559eae267bcad43e1c34
> 
> 录制的时候出错了，还是网络问题，我拿你获取到的直播源链接到在线播放器 是正常播放的 ![image](https://private-user-images.githubusercontent.com/114978440/339738951-0b563935-3a5c-43a3-a60e-55e2742a11a3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNjM5OTIsIm5iZiI6MTcxODM2MzY5MiwicGF0aCI6Ii8xMTQ5Nzg0NDAvMzM5NzM4OTUxLTBiNTYzOTM1LTNhNWMtNDNhMy1hNjBlLTU1ZTI3NDJhMTFhMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNFQxMTE0NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NmJiNGVhZjdkMTZiYmU4ZGQ4OTk4OTE5OTE5ZDdmMDRmMDcyZDI1NGM2ZDc3Y2ZiZjNjZmNhMDIxNTgxNTY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rPydBUnNSZn_klfoHxa_SI-Q2P10SyzrEqhTqLW1XPo)
> 
> 且我拿你获取的直播源 录制正常 ![image](https://private-user-images.githubusercontent.com/114978440/339739920-33466ce1-9c0c-46c5-a8c4-09d377afed96.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNjM5OTIsIm5iZiI6MTcxODM2MzY5MiwicGF0aCI6Ii8xMTQ5Nzg0NDAvMzM5NzM5OTIwLTMzNDY2Y2UxLTljMGMtNDZjNS1hOGM0LTA5ZDM3N2FmZWQ5Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNFQxMTE0NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NzY5NDk4MTMyOWFlY2Q1NDhmMjAzNDM5ZjI4YjkwOTcyNTIzYjdlOTc0Njg4MGU5NmI0NDU0OWIxNzY0NGIwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.f8nOfob6u-sJZu_Syde0q3y1LXKCOoXKgmNjuzgaC_w)
> 
> 节点延迟以及网速、协议等相关

作者有好用的梯子推荐吗，因为我录不了是从5月23日开始的，期间一直没有换其他节点和梯子软件，所以应该和风控没关系

**Comment by d5f4sd6f84dfa** [comment]
> 可以看到你已经获取到了直播源地址：http://pull-f5-tt01.tiktokcdn-us.com/stage/stream-3574081738877436848_or4.flv?expire=1719571204&sign=17bf1776040b559eae267bcad43e1c34
> 
> 录制的时候出错了，还是网络问题，我拿你获取到的直播源链接到在线播放器 是正常播放的 ![image](https://private-user-images.githubusercontent.com/114978440/339738951-0b563935-3a5c-43a3-a60e-55e2742a11a3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNzM3NzksIm5iZiI6MTcxODM3MzQ3OSwicGF0aCI6Ii8xMTQ5Nzg0NDAvMzM5NzM4OTUxLTBiNTYzOTM1LTNhNWMtNDNhMy1hNjBlLTU1ZTI3NDJhMTFhMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNFQxMzU3NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YzU3MTZkYTRkNTE0ODM3ZGUyNzFmYWMwMTcwODE0M2E0ZDc0ZDY3NmRlOGFmYjU4OWQ2MzA1MzJjNjVlZGYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.iq_O9OWbHlRfmgFUMr9d7VDuPKkgRdgd5GCztSkrPcE)
> 
> 且我拿你获取的直播源 录制正常 ![image](https://private-user-images.githubusercontent.com/114978440/339739920-33466ce1-9c0c-46c5-a8c4-09d377afed96.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNzM3NzksIm5iZiI6MTcxODM3MzQ3OSwicGF0aCI6Ii8xMTQ5Nzg0NDAvMzM5NzM5OTIwLTMzNDY2Y2UxLTljMGMtNDZjNS1hOGM0LTA5ZDM3N2FmZWQ5Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNFQxMzU3NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YmE5ZjAzOTU2ZmE0YWY2YjdiMWVmY2VhN2JmNWIyNjc1ZWFkNmYyMzc2NTJiNmFhYTE4NTExMDBmZWRjNDc3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vyoJyI62Lk4zY3u6nuSnxQn0o06nlYpkf6GEuoTnuDk)
> 
> 节点延迟以及网速、协议等相关

已经更换梯子和节点，还是老样子

**Comment by d5f4sd6f84dfa** [comment]
![image](https://github.com/ihmily/DouyinLiveRecorder/assets/168329204/6e881dff-2ca1-45ac-a19e-ecb08992e12e)
我换其他平台为什么可以录，换TIKTOK直接录不了，我破防了
