### ISSUE TITLE
Tik Tok录制不了

### ISSUE THREAD

**Issue by hellotanggege** [ihmily/DouyinLiveRecorder#406]
使用的VPN，配置代理之后总是提示错误，无法抓取直播间。
![微信图片_20240612092827](https://github.com/ihmily/DouyinLiveRecorder/assets/152941295/50f36516-7dac-491e-84a5-b1c96bdd3086)

**Comment by Andy8r0X** [comment]
设置tiktok_cookie

**Comment by bagusmu** [comment]
> 设置tiktok_cookie

如何设置cookies

**Comment by Andy8r0X** [comment]
> > 设置tiktok_cookie
> 
> 如何设置cookies


config\config.ini
同一时间访问网络的线程数，降为1
循环时间(秒)，降低速率超过200以上
tiktok_cookie填上浏览器无痕访客的cookie值

**Comment by ihmily** [comment]
https://github.com/ihmily/DouyinLiveRecorder/issues/414#issuecomment-2166006401 **到这下载最新的版本**
