### ISSUE TITLE
降低视频录制质量

### ISSUE THREAD

**Issue by data-cc** [ihmily/DouyinLiveRecorder#408]
您好请问怎么可以降低录制的视频质量，现在已经选择用ts格式了但是每天录制的文件还是很大，录制的视频质量怎么可以再降低一下，望请您给与答复，谢谢。

**Comment by Andy8r0X** [comment]
买更大更多的硬盘，就不必担心文件大

**Comment by data-cc** [comment]
您好，您的邮件我已收到，谢谢！

**Comment by theandychung** [comment]
我也有一樣的問題，請問如何降低twitcast的畫質？
謝謝

**Comment by ihmily** [comment]
> 您好请问怎么可以降低录制的视频质量，现在已经选择用ts格式了但是每天录制的文件还是很大，录制的视频质量怎么可以再降低一下，望请您给与答复，谢谢。

@data-cc 
ts只是录制的视频保存格式，并不能降低画质。如果要降低录制的清晰度，你可以在config/config.ini配置文件中录制的地址前面加上清晰度 ，支持的清晰度包括 蓝光(原画)、超清、高清、标清、流畅 等，清晰度依次降低，

配置如下图
![image](https://github.com/ihmily/DouyinLiveRecorder/assets/114978440/8ae8ca23-5012-4bdb-96c8-29137393c8c8)

**Comment by ihmily** [comment]
> 我也有一樣的問題，請問如何降低twitcast的畫質？ 謝謝

twitcast目前只有一种画质，暂时无法更改

**Comment by data-cc** [comment]
如果已经设置流畅了还能再降低吗，每30分钟大概200-300mb，一天的储存很大。能降低文件大小吗视频质量差也可以。
&nbsp;


陈工
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年6月13日(星期四) 晚上6:14
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ihmily/DouyinLiveRecorder] 降低视频录制质量 (Issue #408)














  
您好请问怎么可以降低录制的视频质量，现在已经选择用ts格式了但是每天录制的文件还是很大，录制的视频质量怎么可以再降低一下，望请您给与答复，谢谢。
  
@data-cc
 ts只是录制的视频保存格式，并不能降低画质。如果要降低录制的清晰度，你可以在config/config.ini配置文件中录制的地址前面加上清晰度 ，支持的清晰度包括 蓝光(原画)、超清、高清、标清、流畅 等，清晰度依次降低，
 
配置如下图
 image.png (view on web)

**Comment by data-cc** [comment]
陈工
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ihmily/DouyinLiveRecorder"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月13日(星期四) 晚上6:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ihmily/DouyinLiveRecorder] 降低视频录制质量 (Issue #408)





  
您好请问怎么可以降低录制的视频质量，现在已经选择用ts格式了但是每天录制的文件还是很大，录制的视频质量怎么可以再降低一下，望请您给与答复，谢谢。
  
@data-cc
 ts只是录制的视频保存格式，并不能降低画质。如果要降低录制的清晰度，你可以在config/config.ini配置文件中录制的地址前面加上清晰度 ，支持的清晰度包括 蓝光(原画)、超清、高清、标清、流畅 等，清晰度依次降低，
 
配置如下图
 image.png (view on web)
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***&gt;


从QQ邮箱发来的超大附件

截图.jpg (38.8K, 无限期)进入下载页面：https://mail.qq.com/cgi-bin/ftnExs_download?k=58343564ee50c9cf8307c14a1234041f1d40540002010f094857065351190107065718505651531d0657045005070e0350520d51343c368dbdf9894a5e44513058&t=exs_ftn_download&code=e45d4460

**Comment by data-cc** [comment]
您好，您的邮件我已收到，谢谢！
