### ISSUE TITLE
3.05版本遇到个奇怪事情URL_config.ini  被自动清空了

### ISSUE THREAD

**Issue by douying2334** [ihmily/DouyinLiveRecorder#410]
就是自动打开后 提示无主播地址 打开URL_config.ini 才发现 里面地址全空白了 为啥呀 你们遇到过吗

不知道和这个有没有关系 就是昨晚忘记关闭了 于是 自启又多开了一个录制 相当于2个录制软件一起录制

**Comment by d5f4sd6f84dfa** [comment]
不正常关闭或者打开会有这种情况，有备份的
![11](https://github.com/ihmily/DouyinLiveRecorder/assets/168329204/2cd5417d-9495-4bdd-bc81-415228a82949)
![11](https://github.com/ihmily/DouyinLiveRecorder/assets/168329204/2cd5417d-9495-4bdd-bc81-415228a82949)
![11](https://github.com/ihmily/DouyinLiveRecorder/assets/168329204/2cd5417d-9495-4bdd-bc81-415228a82949)
![11](https://github.com/ihmily/DouyinLiveRecorder/assets/168329204/2cd5417d-9495-4bdd-bc81-415228a82949)

**Comment by douying2334** [comment]
> 不正常关闭或者打开会有这种情况，有备份的 ![11](https://private-user-images.githubusercontent.com/168329204/338989101-2cd5417d-9495-4bdd-bc81-415228a82949.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyMzg4MzQsIm5iZiI6MTcxODIzODUzNCwicGF0aCI6Ii8xNjgzMjkyMDQvMzM4OTg5MTAxLTJjZDU0MTdkLTk0OTUtNGJkZC1iYzgxLTQxNTIyOGE4Mjk0OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxM1QwMDI4NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MTVjYmVjY2IxZDQ3NjAwOWZjMDFjMzVjNjE4NzdkYjA2YzFjY2Q0MDRhM2Q5MjljMTEwMmE0NzBhNzkzMzNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kvfTHWvSti9rLBsCjDXhGuxjw9xAfFutHzT01eU7X00) ![11](https://private-user-images.githubusercontent.com/168329204/338989101-2cd5417d-9495-4bdd-bc81-415228a82949.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyMzg4MzQsIm5iZiI6MTcxODIzODUzNCwicGF0aCI6Ii8xNjgzMjkyMDQvMzM4OTg5MTAxLTJjZDU0MTdkLTk0OTUtNGJkZC1iYzgxLTQxNTIyOGE4Mjk0OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxM1QwMDI4NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MTVjYmVjY2IxZDQ3NjAwOWZjMDFjMzVjNjE4NzdkYjA2YzFjY2Q0MDRhM2Q5MjljMTEwMmE0NzBhNzkzMzNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kvfTHWvSti9rLBsCjDXhGuxjw9xAfFutHzT01eU7X00) ![11](https://private-user-images.githubusercontent.com/168329204/338989101-2cd5417d-9495-4bdd-bc81-415228a82949.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyMzg4MzQsIm5iZiI6MTcxODIzODUzNCwicGF0aCI6Ii8xNjgzMjkyMDQvMzM4OTg5MTAxLTJjZDU0MTdkLTk0OTUtNGJkZC1iYzgxLTQxNTIyOGE4Mjk0OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxM1QwMDI4NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MTVjYmVjY2IxZDQ3NjAwOWZjMDFjMzVjNjE4NzdkYjA2YzFjY2Q0MDRhM2Q5MjljMTEwMmE0NzBhNzkzMzNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kvfTHWvSti9rLBsCjDXhGuxjw9xAfFutHzT01eU7X00) ![11](https://private-user-images.githubusercontent.com/168329204/338989101-2cd5417d-9495-4bdd-bc81-415228a82949.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyMzg4MzQsIm5iZiI6MTcxODIzODUzNCwicGF0aCI6Ii8xNjgzMjkyMDQvMzM4OTg5MTAxLTJjZDU0MTdkLTk0OTUtNGJkZC1iYzgxLTQxNTIyOGE4Mjk0OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxM1QwMDI4NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MTVjYmVjY2IxZDQ3NjAwOWZjMDFjMzVjNjE4NzdkYjA2YzFjY2Q0MDRhM2Q5MjljMTEwMmE0NzBhNzkzMzNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kvfTHWvSti9rLBsCjDXhGuxjw9xAfFutHzT01eU7X00)



> 不正常关闭或者打开会有这种情况，有备份的 ![11](https://private-user-images.githubusercontent.com/168329204/338989101-2cd5417d-9495-4bdd-bc81-415228a82949.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyMzg4MzQsIm5iZiI6MTcxODIzODUzNCwicGF0aCI6Ii8xNjgzMjkyMDQvMzM4OTg5MTAxLTJjZDU0MTdkLTk0OTUtNGJkZC1iYzgxLTQxNTIyOGE4Mjk0OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxM1QwMDI4NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MTVjYmVjY2IxZDQ3NjAwOWZjMDFjMzVjNjE4NzdkYjA2YzFjY2Q0MDRhM2Q5MjljMTEwMmE0NzBhNzkzMzNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kvfTHWvSti9rLBsCjDXhGuxjw9xAfFutHzT01eU7X00) ![11](https://private-user-images.githubusercontent.com/168329204/338989101-2cd5417d-9495-4bdd-bc81-415228a82949.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyMzg4MzQsIm5iZiI6MTcxODIzODUzNCwicGF0aCI6Ii8xNjgzMjkyMDQvMzM4OTg5MTAxLTJjZDU0MTdkLTk0OTUtNGJkZC1iYzgxLTQxNTIyOGE4Mjk0OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxM1QwMDI4NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MTVjYmVjY2IxZDQ3NjAwOWZjMDFjMzVjNjE4NzdkYjA2YzFjY2Q0MDRhM2Q5MjljMTEwMmE0NzBhNzkzMzNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kvfTHWvSti9rLBsCjDXhGuxjw9xAfFutHzT01eU7X00) ![11](https://private-user-images.githubusercontent.com/168329204/338989101-2cd5417d-9495-4bdd-bc81-415228a82949.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyMzg4MzQsIm5iZiI6MTcxODIzODUzNCwicGF0aCI6Ii8xNjgzMjkyMDQvMzM4OTg5MTAxLTJjZDU0MTdkLTk0OTUtNGJkZC1iYzgxLTQxNTIyOGE4Mjk0OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxM1QwMDI4NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MTVjYmVjY2IxZDQ3NjAwOWZjMDFjMzVjNjE4NzdkYjA2YzFjY2Q0MDRhM2Q5MjljMTEwMmE0NzBhNzkzMzNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kvfTHWvSti9rLBsCjDXhGuxjw9xAfFutHzT01eU7X00) ![11](https://private-user-images.githubusercontent.com/168329204/338989101-2cd5417d-9495-4bdd-bc81-415228a82949.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyMzg4MzQsIm5iZiI6MTcxODIzODUzNCwicGF0aCI6Ii8xNjgzMjkyMDQvMzM4OTg5MTAxLTJjZDU0MTdkLTk0OTUtNGJkZC1iYzgxLTQxNTIyOGE4Mjk0OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxM1QwMDI4NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MTVjYmVjY2IxZDQ3NjAwOWZjMDFjMzVjNjE4NzdkYjA2YzFjY2Q0MDRhM2Q5MjljMTEwMmE0NzBhNzkzMzNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kvfTHWvSti9rLBsCjDXhGuxjw9xAfFutHzT01eU7X00)

是这样啊 ，请问怎么避免被清空呀  我是设置定时开启的，  关闭也是正常手动关的，或者之前注销一键关闭电脑所有程序，之前好好的 用了很久，昨天才这样，好险发现了  要是没发现错误提示 估计就错过录制直播了。。

**Comment by douying2334** [comment]
> 不正常关闭或者打开会有这种情况，有备份的 ![11](https://private-user-images.githubusercontent.com/168329204/338989101-2cd5417d-9495-4bdd-bc81-415228a82949.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNTA3NzYsIm5iZiI6MTcxODI1MDQ3NiwicGF0aCI6Ii8xNjgzMjkyMDQvMzM4OTg5MTAxLTJjZDU0MTdkLTk0OTUtNGJkZC1iYzgxLTQxNTIyOGE4Mjk0OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxM1QwMzQ3NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lODUzOThjZjU4Y2E4ZDQ0OTM2MGExMTA4NmQwZTUzNjUwODQ0NGRiNmNiNTQ2YzFmYTQ3YTE5MzliMTgwODM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DjFKaJEniet3mVgL6UfXcvXDcqMd9l6U-Dh3YRBFEOQ) ![11](https://private-user-images.githubusercontent.com/168329204/338989101-2cd5417d-9495-4bdd-bc81-415228a82949.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNTA3NzYsIm5iZiI6MTcxODI1MDQ3NiwicGF0aCI6Ii8xNjgzMjkyMDQvMzM4OTg5MTAxLTJjZDU0MTdkLTk0OTUtNGJkZC1iYzgxLTQxNTIyOGE4Mjk0OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxM1QwMzQ3NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lODUzOThjZjU4Y2E4ZDQ0OTM2MGExMTA4NmQwZTUzNjUwODQ0NGRiNmNiNTQ2YzFmYTQ3YTE5MzliMTgwODM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DjFKaJEniet3mVgL6UfXcvXDcqMd9l6U-Dh3YRBFEOQ) ![11](https://private-user-images.githubusercontent.com/168329204/338989101-2cd5417d-9495-4bdd-bc81-415228a82949.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNTA3NzYsIm5iZiI6MTcxODI1MDQ3NiwicGF0aCI6Ii8xNjgzMjkyMDQvMzM4OTg5MTAxLTJjZDU0MTdkLTk0OTUtNGJkZC1iYzgxLTQxNTIyOGE4Mjk0OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxM1QwMzQ3NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lODUzOThjZjU4Y2E4ZDQ0OTM2MGExMTA4NmQwZTUzNjUwODQ0NGRiNmNiNTQ2YzFmYTQ3YTE5MzliMTgwODM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DjFKaJEniet3mVgL6UfXcvXDcqMd9l6U-Dh3YRBFEOQ) ![11](https://private-user-images.githubusercontent.com/168329204/338989101-2cd5417d-9495-4bdd-bc81-415228a82949.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNTA3NzYsIm5iZiI6MTcxODI1MDQ3NiwicGF0aCI6Ii8xNjgzMjkyMDQvMzM4OTg5MTAxLTJjZDU0MTdkLTk0OTUtNGJkZC1iYzgxLTQxNTIyOGE4Mjk0OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxM1QwMzQ3NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lODUzOThjZjU4Y2E4ZDQ0OTM2MGExMTA4NmQwZTUzNjUwODQ0NGRiNmNiNTQ2YzFmYTQ3YTE5MzliMTgwODM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DjFKaJEniet3mVgL6UfXcvXDcqMd9l6U-Dh3YRBFEOQ)

说明下 不是config.ini 清空 图片里面文件夹是 config.ini  而不是URL_config.ini   ，URL_config.ini 是主播链接， URL_config.ini 被清空了 ，但是config.ini  没有被清空

**Comment by d5f4sd6f84dfa** [comment]
![11](https://github.com/ihmily/DouyinLiveRecorder/assets/168329204/0ca268bc-961a-4f48-9489-338b2d145efd)
我试了好多次，Ctrl+C关闭最稳定，不要直接关闭程序
