### ISSUE TITLE
小红书直播链接需要开播一次更换一次.

### ISSUE THREAD

**Issue by ruoyan0718** [ihmily/DouyinLiveRecorder#411]
添加小红书直播间链接主播下播后这个链接就失效了，需要重新添加更换该主播的链接，不知道你们有没有个情况。

**Comment by douying2334** [comment]
> 每次小红书直播都生成一次唯一的直播ID，像是YouTube 影片ID那样，不像抖音每次都同一个直播号

太恐怖了 要是抖音这样 就完了 没法录了

**Comment by ihmily** [comment]
已修复，3.0.9版本支持使用“小红书作者主页地址”录制，会自动获取最新直播间地址
