### ISSUE TITLE
B站录制失败

### ISSUE THREAD

**Issue by chendali8** [ihmily/DouyinLiveRecorder#412]
![image](https://github.com/ihmily/DouyinLiveRecorder/assets/70122941/a1976491-1d44-4b49-814e-11b4015f52f7)

URL_config.ini配置

![image](https://github.com/ihmily/DouyinLiveRecorder/assets/70122941/9756a975-8f16-4530-b945-2de6c84110da)

执行python3 main.py 
![image](https://github.com/ihmily/DouyinLiveRecorder/assets/70122941/2112c5be-87b5-4006-92c1-2f25a822ce3d)

2024-06-12 23:39:51.700 | ERROR    | utils:wrapper:18 - 错误信息: type: IndexError, list index out of range in function get_bilibili_stream_url at line: 540
2024-06-12 23:39:51.701 | ERROR    | __main__:start_record:1499 - 错误信息: 'list' object has no attribute 'get' 发生错误的行数: 1065

**Comment by ihmily** [comment]
其他直播间可以正常录制吗？

**Comment by BlackDog-ZJ** [comment]
使用最新下载的包试图录制，无法正常录制
![1718297288970](https://github.com/ihmily/DouyinLiveRecorder/assets/172627978/28b13bf5-c6c7-44c7-8243-68940e9569fe)

返回的m3u8的连接与浏览器捕获的连接出入很大
![(F7I0Z7%4_D$3RUJCOMLAFO](https://github.com/ihmily/DouyinLiveRecorder/assets/172627978/b4431623-47ca-4a30-8b07-83fcd620cd96)

**Comment by ihmily** [comment]
@BlackDog-ZJ 

你怎么还在用2.0.7版本，最新的是3.0.5版本 
下载这个 https://github.com/ihmily/DouyinLiveRecorder/releases/download/v3.0.5/DouyinLiveRecorder.v3.0.5-fix.zip

![image](https://github.com/ihmily/DouyinLiveRecorder/assets/114978440/4e70d6c5-380a-4de4-8022-2d5221591632)

![image](https://github.com/ihmily/DouyinLiveRecorder/assets/114978440/262f6d70-f137-41bf-8d24-ac6c216a9b26)
