### ISSUE TITLE
设置录制ts格式，自动转码mp4后的文件命名问题

### ISSUE THREAD

**Issue by bitA23187** [ihmily/DouyinLiveRecorder#413]
您好，设置ts格式录制，并设定“ts录制完成后自动转为mp4格式”，此时mp4文件名自动设置为“DouyinLiveRecorder v3”，而非原ts文件名称。
如果主播多次开播，这将导致转码后的mp4文件被逐个覆盖，请问这是应用特性，还是我的操作有问题呢？谢谢

**Comment by ihmily** [comment]
正常是不会出现这种情况的，你是否自己有更改保存路径配置？

**Comment by bitA23187** [comment]
感谢您的回复，我没有更改保存路径配置，下面是我的config文件，我仅仅修改了[录制设置]中的部分内容，其余均保持默认（包括[推送配置]、[Cookie]等）

```
[录制设置]
直播保存路径（不填则默认） = 
保存文件夹是否以作者区分 = 是
视频保存格式ts|mkv|flv|mp4|ts音频|mkv音频 = ts
原画|超清|高清|标清|流畅 = 原画
是否使用代理ip（是/否） = 否
代理地址 = 
同一时间访问网络的线程数 = 3
循环时间(秒) = 152
排队读取网址时间(秒) = 0
是否显示循环秒数 = 是
是否显示直播源地址 = 否
分段录制是否开启 = 否
视频分段时间(秒) = 1800
ts录制完成后自动转为mp4格式 = 是
ts录制完成后自动增加生成m4a格式 = 否
音频录制完成后自动转为mp3格式 = 否
追加格式后删除原文件 = 否
生成时间文件 = 否
使用代理录制的平台（逗号分隔） = tiktok, afreecatv, pandalive, winktv, flextv, popkontv, twitch
额外使用代理录制的平台（逗号分隔） = 
```

我只录制抖音直播，在录制结束后，ts文件自动保存在“downloads/抖音直播/直播id“文件夹中；而令人疑惑的是，自动转码的mp4文件 被保存在该应用的根目录下，如下图。
其中红圈标注了自动转码的，命名为”DouyinLiveRecorder v3“的mp4文件（其余是我手动修改的文件名）。该特性在v3.0.2和v3.0.5中均存在。

![image](https://github.com/ihmily/DouyinLiveRecorder/assets/41949733/7027548a-0fea-4da7-8861-a3f41ed3761e)

再次感谢您的回复！我另上传了使用v3.0.5以来的logs文件，希望这能有所帮助。

[DouyinLiveRecorder.log](https://github.com/user-attachments/files/15821639/DouyinLiveRecorder.log)

**Comment by ihmily** [comment]
已修复
