### ISSUE TITLE
TIKTOK无法录制

### ISSUE THREAD

**Issue by d5f4sd6f84dfa** [ihmily/DouyinLiveRecorder#414]
![11](https://github.com/ihmily/DouyinLiveRecorder/assets/168329204/deacc0bc-42ac-4f78-8fbf-997334c5a83e)
![11](https://github.com/ihmily/DouyinLiveRecorder/assets/168329204/d1ab2a89-4d63-4458-8853-63ee608083d7)
更换IP，设置cookies（使用EDGE、Chrome均为无痕模式），检测网络正常能上TIKTOK，但换来的是能检测到开播，但无法录制（会报错，请检查网络）

**Comment by ihmily** [comment]
@d5f4sd6f84dfa 

下载 https://github.com/ihmily/DouyinLiveRecorder/releases/download/v3.0.5/DouyinLiveRecorder.v3.0.5-fix.zip 这个fix修复版试试

**Comment by d5f4sd6f84dfa** [comment]
> @d5f4sd6f84dfa
> 
> 下载 https://github.com/ihmily/DouyinLiveRecorder/releases/download/v3.0.5/DouyinLiveRecorder.v3.0.5-fix.zip 这个fix修复版试试

打开主程序会直接闪退，打不开

**Comment by d5f4sd6f84dfa** [comment]
![11](https://github.com/ihmily/DouyinLiveRecorder/assets/168329204/4c8c781e-ce25-4aca-b6db-b9704aa0f520)

**Comment by ihmily** [comment]
现在重新下载试试

**Comment by ihmily** [comment]
@d5f4sd6f84dfa 

### 别自己添加tiktok cookie，你们添加的很多时候是错误的。你这连直播源都没获取到。

**Comment by ihmily** [comment]
### 只需要配置一个代理就行，代理地址尝试加上协议头 http://
![image](https://github.com/ihmily/DouyinLiveRecorder/assets/114978440/0a57ed39-43a0-49df-bf11-c9ccf53c6dc9)
![image](https://github.com/ihmily/DouyinLiveRecorder/assets/114978440/9dfcede9-4123-4c6e-b9bb-07830d4accbb)

**Comment by ihmily** [comment]
### 正常录制
![image](https://github.com/ihmily/DouyinLiveRecorder/assets/114978440/557d524b-adf4-475b-adef-ca911fb6d9ff)

**Comment by d5f4sd6f84dfa** [comment]
> ### 只需要配置一个代理就行，代理地址尝试加上协议头 http://
> ![image](https://private-user-images.githubusercontent.com/114978440/339645721-0a57ed39-43a0-49df-bf11-c9ccf53c6dc9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNDMzOTMsIm5iZiI6MTcxODM0MzA5MywicGF0aCI6Ii8xMTQ5Nzg0NDAvMzM5NjQ1NzIxLTBhNTdlZDM5LTQzYTAtNDlkZi1iZjExLWM5Y2NmNTNjNmRjOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNFQwNTMxMzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xM2E5ODU3MmU4MDczM2I5YjViMDdhZjMwMTkxNTMzZDNiMDdkNjlhN2NlZThmMGIxYTY2Nzk4NzEzMDQyOTBjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.AO3whsmY2q9HqfhTq59WUXjERA7KQXnz4luS45EaMrU) ![image](https://private-user-images.githubusercontent.com/114978440/339645856-9dfcede9-4123-4c6e-b9bb-07830d4accbb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNDMzOTMsIm5iZiI6MTcxODM0MzA5MywicGF0aCI6Ii8xMTQ5Nzg0NDAvMzM5NjQ1ODU2LTlkZmNlZGU5LTQxMjMtNGM2ZS1iOWJiLTA3ODMwZDRhY2NiYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNFQwNTMxMzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YWM0ZGMzYzEyOThmOTMwZGJiOTI1YjkyOTc3MGU0YTgxZGNjMzJjN2M4YTk0ODk0OWJhMThjOGM3NjdhNDc3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CP6UCdB2jOdCOvCYsz9IpKY9Cbe2E1s9IU5qQDszNuw)

![image](https://github.com/ihmily/DouyinLiveRecorder/assets/168329204/73f53ff9-16f7-4fa7-ae98-5e45e7cb4b9b)
![11](https://github.com/ihmily/DouyinLiveRecorder/assets/168329204/f1a81c47-8686-4b19-943d-b521d8f59a5a)
![11](https://github.com/ihmily/DouyinLiveRecorder/assets/168329204/54c65378-6f2a-41ec-bc93-d66f92235296)
跟着楼主走，还是一样...

**Comment by ihmily** [comment]
试一下开全局代理，不配置代理地址，把代理地址删掉

**Comment by d5f4sd6f84dfa** [comment]
> 开全局代理，不配置代理地址，把代理地址删掉

![11](https://github.com/ihmily/DouyinLiveRecorder/assets/168329204/682f3d5a-b63d-44b0-a9f8-7a650ba93c02)
这样？

**Comment by d5f4sd6f84dfa** [comment]
> 试一下开全局代理，不配置代理地址，把代理地址删掉

全局代理直接没有检测到开播

**Comment by ihmily** [comment]
如果配置正确的话，应该是你代理的原因，我测试了3台机器都是正常录制的。

**Comment by d5f4sd6f84dfa** [comment]
> 如果配置正确的话，应该是你代理的原因，我测试了3台机器都是正常录制的。

意思是换个梯子或者是梯子换个节点？

**Comment by ihmily** [comment]
> > 如果配置正确的话，应该是你代理的原因，我测试了3台机器都是正常录制的。
> 
> 意思是换个梯子或者是梯子换个节点？

是的 你的机器重启也可以试试
