### ISSUE TITLE
docker里不可以正常访问TikTok网站

### ISSUE THREAD

**Issue by grass107** [ihmily/DouyinLiveRecorder#418]
挂服务器上 直接python可以访问 但是在docker里面不行
2024-06-14 21:11:25.659 | ERROR    | utils:wrapper:18 - 错误信息: type: ConnectionError, 请检查你的网络是否可以正常访问TikTok网站 in function get_tiktok_stream_data at line: 237
2024-06-14 21:11:25.660 | ERROR    | __main__:start_record:1499 - 错误信息: expected string or bytes-like object, got 'NoneType' 发生错误的行数: 1071
2024-06-14 21:11:25.867 | ERROR    | utils:wrapper:18 - 错误信息: type: ConnectionError, 请检查你的网络是否可以正常访问TikTok网站 in function get_tiktok_stream_data at line: 237

**Comment by d5f4sd6f84dfa** [comment]
我也是一直提示检查网络，我怀疑是代理服务器的问题

**Comment by grass107** [comment]
> 我也是一直提示检查网络，我怀疑是代理服务器的问题

windows吗？ config.ini里面的代理地址有填吗 我换了代理后得填才能用

**Comment by d5f4sd6f84dfa** [comment]
> > 我也是一直提示检查网络，我怀疑是代理服务器的问题
> 
> windows吗？ config.ini里面的代理地址有填吗 我换了代理后得填才能用
是Windows，我都填好了，但就是录制不下来（检测到开播了）
![image](https://github.com/ihmily/DouyinLiveRecorder/assets/168329204/e192f4f8-b27f-4e28-8e9b-67dc3efdbe05)
![11](https://github.com/ihmily/DouyinLiveRecorder/assets/168329204/829fa395-5cf6-4ff5-836e-1c1a99bc1695)
![11](https://github.com/ihmily/DouyinLiveRecorder/assets/168329204/8f587505-fd0b-4dfa-b158-ee90a4c47f20)

**Comment by grass107** [comment]
> > > 我也是一直提示检查网络，我怀疑是代理服务器的问题
> > 
> > 
> > windows吗？ config.ini里面的代理地址有填吗 我换了代理后得填才能用
> > 是Windows，我都填好了，但就是录制不下来（检测到开播了）
> > ![11](https://private-user-images.githubusercontent.com/168329204/339787834-eca1bc15-17e7-47f7-b9e0-3d57caa0809b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNzM3MzEsIm5iZiI6MTcxODM3MzQzMSwicGF0aCI6Ii8xNjgzMjkyMDQvMzM5Nzg3ODM0LWVjYTFiYzE1LTE3ZTctNDdmNy1iOWUwLTNkNTdjYWEwODA5Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNFQxMzU3MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mOTYyYTAzMjNmNjA4MjJmMzRlMDIwYjgyMWQwM2IxMTZkM2FiYTU2ZDk1NThhMGIyMmVhOTBlM2IxMjViOWJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.N9UBgKen2G5gpk5TGIBOm0NA723CRquG2cRaRkchPY4)
> > ![11](https://private-user-images.githubusercontent.com/168329204/339786969-829fa395-5cf6-4ff5-836e-1c1a99bc1695.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNzM3MzEsIm5iZiI6MTcxODM3MzQzMSwicGF0aCI6Ii8xNjgzMjkyMDQvMzM5Nzg2OTY5LTgyOWZhMzk1LTVjZjYtNGZmNS04MzZlLTFjMWE5OWJjMTY5NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNFQxMzU3MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NTQzNDk2MzRjNmY4MmQ2MmRiMjk5MGQwY2QwOGQ0MjJiMDBmM2Q4MjkzNWEyM2NhMDA5MjBjYzc5MWRlZWM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.L2KdK9EjGxcwirMZdjSblY80yXwz-gYS-SFtnw23KGo)
> > ![11](https://private-user-images.githubusercontent.com/168329204/339787433-8f587505-fd0b-4dfa-b158-ee90a4c47f20.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNzM3MzEsIm5iZiI6MTcxODM3MzQzMSwicGF0aCI6Ii8xNjgzMjkyMDQvMzM5Nzg3NDMzLThmNTg3NTA1LWZkMGItNGRmYS1iMTU4LWVlOTBhNGM0N2YyMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNFQxMzU3MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZjUwYWEzYzY5M2E2YzVlNTU1OTM5NDE2ZWY0MTZhZjY3N2I2NzQzZmU4MjJjMmY2ZDZhZTM1ZDk0ODU2YmZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.G1D45xGd33utF4uDu1-mt4UflUeDcYUO1iWo1FXu_sw)

127前面加http:// 试试看

**Comment by d5f4sd6f84dfa** [comment]
> > > > 我也是一直提示检查网络，我怀疑是代理服务器的问题
> > > 
> > > 
> > > windows吗？ config.ini里面的代理地址有填吗 我换了代理后得填才能用
> > > 是Windows，我都填好了，但就是录制不下来（检测到开播了）
> > > ![11](https://private-user-images.githubusercontent.com/168329204/339787834-eca1bc15-17e7-47f7-b9e0-3d57caa0809b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNzM3MzEsIm5iZiI6MTcxODM3MzQzMSwicGF0aCI6Ii8xNjgzMjkyMDQvMzM5Nzg3ODM0LWVjYTFiYzE1LTE3ZTctNDdmNy1iOWUwLTNkNTdjYWEwODA5Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNFQxMzU3MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mOTYyYTAzMjNmNjA4MjJmMzRlMDIwYjgyMWQwM2IxMTZkM2FiYTU2ZDk1NThhMGIyMmVhOTBlM2IxMjViOWJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.N9UBgKen2G5gpk5TGIBOm0NA723CRquG2cRaRkchPY4)
> > > ![11](https://private-user-images.githubusercontent.com/168329204/339786969-829fa395-5cf6-4ff5-836e-1c1a99bc1695.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNzM3MzEsIm5iZiI6MTcxODM3MzQzMSwicGF0aCI6Ii8xNjgzMjkyMDQvMzM5Nzg2OTY5LTgyOWZhMzk1LTVjZjYtNGZmNS04MzZlLTFjMWE5OWJjMTY5NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNFQxMzU3MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NTQzNDk2MzRjNmY4MmQ2MmRiMjk5MGQwY2QwOGQ0MjJiMDBmM2Q4MjkzNWEyM2NhMDA5MjBjYzc5MWRlZWM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.L2KdK9EjGxcwirMZdjSblY80yXwz-gYS-SFtnw23KGo)
> > > ![11](https://private-user-images.githubusercontent.com/168329204/339787433-8f587505-fd0b-4dfa-b158-ee90a4c47f20.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNzM3MzEsIm5iZiI6MTcxODM3MzQzMSwicGF0aCI6Ii8xNjgzMjkyMDQvMzM5Nzg3NDMzLThmNTg3NTA1LWZkMGItNGRmYS1iMTU4LWVlOTBhNGM0N2YyMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNFQxMzU3MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZjUwYWEzYzY5M2E2YzVlNTU1OTM5NDE2ZWY0MTZhZjY3N2I2NzQzZmU4MjJjMmY2ZDZhZTM1ZDk0ODU2YmZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.G1D45xGd33utF4uDu1-mt4UflUeDcYUO1iWo1FXu_sw)
> 
> 127前面加http:// 试试看

尝试加过，还有整段代理地址都删除，都是一样

**Comment by ihmily** [comment]
Docker里如果你是直接想用宿主机的代理 不能直接用127网段 @grass107

**Comment by grass107** [comment]
> Docker里如果你是直接想用宿主机的代理 不能直接用127网段 @grass107

docker里面没设置代理 上星期还能用 今天就用不了了

**Comment by ihmily** [comment]
> > Docker里如果你是直接想用宿主机的代理 不能直接用127网段 @grass107
> 
> docker里面没设置代理 上星期还能用 今天就用不了了

网络问题
