### ISSUE TITLE
录制微博的时候不能录制原画

### ISSUE THREAD

**Issue by 2314860760** [ihmily/DouyinLiveRecorder#419]
据我所知 微博大部分直播不提供原画（人少的），但是微博的直播源地址是没有防盗链和加密认证的，它的二压逻辑是直播链接后面加_wb720avc/wb540avc这样，只需要去掉就可以录制原画，建议加入正则表达式，检测到链接扩展名前有“_wb”（比如https://plwb0.live.weibo.com/alicdn/5045506054816686_wb720avc.flv），就直接去掉，如：（https://plwb0.live.weibo.com/alicdn/5045506054816686.flv），这样就能强制录制原画了

**Comment by 2314860760** [comment]
建议加上，这个机制应该很简单，获取链接以后加个检测，检测到有后缀就直接去掉就好，微博flv不太稳定，人多的时候容易录制不了，建议优先m3u8（同理，修改api返回的链接后缀就行，十分简单粗暴，但刚开播不一定有m3u8，可以类似B站那样等待一段时间还不出现再录flv）

**Comment by ihmily** [comment]
最新版已加入
