### ISSUE TITLE
花了6美元的代价，TIKTOK可以录制了

### ISSUE THREAD

**Issue by d5f4sd6f84dfa** [ihmily/DouyinLiveRecorder#422]
![image](https://github.com/ihmily/DouyinLiveRecorder/assets/168329204/81eee2e9-ad5e-4f70-a253-aa59dd78cebd)
![image](https://github.com/ihmily/DouyinLiveRecorder/assets/168329204/1da24575-af7c-4eac-8fe8-68756c1c6455)

**Comment by linshen6868** [comment]
怎么弄的啊  兄弟
