### ISSUE TITLE
推送配置怎么填？

### ISSUE THREAD

**Issue by 4KAForever11** [ihmily/DouyinLiveRecorder#426]
我想用微信通知直播状态，或者用server酱的方糖公众号推送通知。有没有大佬教我，求！！！

**Comment by ihmily** [comment]
使用API推送，`推送方式`填写 微信 ，`微信推送接口链接` 填写 你的API地址

如：
https://sctapi.ftqq.com/****************.send

其中****************修改为你的Key

**Comment by 4KAForever11** [comment]
谢谢作者大大！！
