### ISSUE TITLE
突然出现这个错误 重启电脑几次还是这样  

### ISSUE THREAD

**Issue by douying2334** [ihmily/DouyinLiveRecorder#427]
开启程序就弹出这个备份配置文件 K:\FlFilFF\DouyinLiveRecorder v3.0.5\DouyinLiveRecorder.v3.0.5/config/config.ini 失败：[WinError 5] 拒绝访 问。: 'K:\\FlFilFF\\DouyinLiveRecorder v3.0.5\\DouyinLiveRecorder.v3.0.5/backup_config\\URL_config.ini_2024-06-12_21-12-22'
备份配置文件 K:\FlFilFF\DouyinLiveRecorder v3.0.5\DouyinLiveRecorder.v3.0.5/config/URL_config.ini 失败：[WinError 5] 拒 绝访问。: 'K:\\FlFilFF\\DouyinLiveRecorder v3.0.5\\DouyinLiveRecorder.v3.0.5/backup_config\\URL_config.ini_2024-06-12_21-12-22'
、

我看了 DouyinLiveRecorder.v3.0.5/config/config.ini   没有设置只读模式啊 为啥拒绝  ，  然后过会好了 显示传入主播地址 ，但是没多久又弹出2024-06-17 21:00:02.613 | ERROR    | utils:wrapper:18 - 错误信息: type: KeyError, 'stream_url' in function get_douyin_stream_data at line: 198
2024-06-17 21:00:02.620 | ERROR    | utils:wrapper:18 - 错误信息: type: AttributeError, 'list' object has no attribute 'get' in function get_douyin_stream_url at line: 279
2024-06-17 21:00:02.621 | ERROR    | __main__:start_record:1499 - 错误信息: 'list' object has no attribute 'get' 发生错误的行数: 1063

然后 又好了。。。不知道会不会录制不成功 啊    现在主播还没在直播

**Comment by douying2334** [comment]
求ihmily大神保佑 程序 永生  离不开  ihmily  了  用不了世界就黑暗了

**Comment by d5f4sd6f84dfa** [comment]
抖音的随便都能录的上，要代理才能录才叫麻烦

**Comment by douying2334** [comment]
我把backup_config  文件夹里面文件全删了 好像就不 弹错误了 ，，估计好了。。。

**Comment by d5f4sd6f84dfa** [comment]
> 我把backup_config 文件夹里面文件全删了 好像就不 弹错误了 ，，估计好了。。。

解决了就好，有没有好用不封控的梯子介绍

**Comment by douying2334** [comment]
之前买的淘宝都不稳定  经常访问不了 现在GFW太厉害了

**Comment by d5f4sd6f84dfa** [comment]
> 之前买的淘宝都不稳定 经常访问不了 现在GFW太厉害了

GFW是什么？介绍下，贵不贵

**Comment by d5f4sd6f84dfa** [comment]
![image](https://github.com/ihmily/DouyinLiveRecorder/assets/168329204/d486e588-df32-4d58-9c4a-8af890012275)
这？

**Comment by douying2334** [comment]
> ![image](https://private-user-images.githubusercontent.com/168329204/340345527-d486e588-df32-4d58-9c4a-8af890012275.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3MDcwODgsIm5iZiI6MTcxODcwNjc4OCwicGF0aCI6Ii8xNjgzMjkyMDQvMzQwMzQ1NTI3LWQ0ODZlNTg4LWRmMzItNGQ1OC05YzRhLThhZjg5MDAxMjI3NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxOFQxMDMzMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05Y2UzYThkYzQ4ZDYzNzIyMGZmNGIwOTNmODU1NmNjYTQ1OGRlMjk3YjgwZGQzODVmZWYwOTE3Y2U0ODRkMzdjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qG9-Fvnefyo-77EJilIuXamAcXP4lzox3S7NQ6SrRLY) 这？



> > 之前买的淘宝都不稳定 经常访问不了 现在GFW太厉害了
> 
> GFW是什么？介绍下，贵不贵

gfw不是梯子 就是gfw越来越严导致总是封锁
