### ISSUE TITLE
无法录制部分douyin直播流，且无法检测开播状态，因其仅支持手机端app观看。

### ISSUE THREAD

**Issue by bytype** [ihmily/DouyinLiveRecorder#429]
能通过手机浏览器直接播放流畅画质的直播流，通过手机上的X浏览器直接嗅探到stream*****_ld.flv的直播流，此【流畅】画质直播流或许能作为一个替代方案。
        更改成手机端user_agent进行直播流抓取，或许能用于临时补全 完全无法录制的空缺。
        提供一个此种情况的直播间/ijThJ2fU

**Comment by bytype** [comment]
v.douyin.com/ijThJ2fU

**Comment by bytype** [comment]
v.douyin.com/ijTkpTWH
这个也是一样，简单归纳一下，就是付费连线型的直播间无法录制，其实这种直播间如果只能抓取到流畅画质的直播流，也差不多能满足要求了，一般是听各种问题和解答。不注重画质。
因此我觉得还是有的补全录制价值。

**Comment by ihmily** [comment]
嗯简单查看了一下确实无法正常录制连麦直播，禁止pc网页端观看，但是移动端可以获取，画质的话也是有方法获取到蓝光、超清等画质的，这两天我更新一下。
