### ISSUE TITLE
录制的视频无法打开要怎么修复

### ISSUE THREAD

**Issue by forever180159** [ihmily/DouyinLiveRecorder#43]
录制的时候可能因为网络中断导致录制的视频无法打开，这个录制的视频要怎么修复呢
![Screenshot 2023-09-18 105712](https://github.com/ihmily/DouyinLiveRecorder/assets/89833571/373dca1a-a31b-4e62-a6ed-d42fbe7fad7f)

**Comment by ihmily** [comment]
> 录制的时候可能因为网络中断导致录制的视频无法打开，这个录制的视频要怎么修复呢 ![Screenshot 2023-09-18 105712](https://user-images.githubusercontent.com/89833571/268547195-373dca1a-a31b-4e62-a6ed-d42fbe7fad7f.png)

目前这种情况，无法修复。
