### ISSUE TITLE
现在是不支持监控TIKTOK了吗？

### ISSUE THREAD

**Issue by linshen6868** [ihmily/DouyinLiveRecorder#432]
现在是不支持监控TIKTOK了吗？为何总是报错，我用了很多种方式都是报错！作者是否有联系方式

**Comment by Andy8r0X** [comment]
你连接tiktok的IP被风控了，更换IP或更换代理

config.ini 改成
同一时间访问网络的线程数 = 1
循环时间(秒) = 300

**Comment by Yeadon8888** [comment]
换一下代理节点或者网络
