### ISSUE TITLE
抖音地址不能识别

### ISSUE THREAD

**Issue by kblzj8** [ihmily/DouyinLiveRecorder#433]
抖音地址不能识别

想要录个喜欢的主播，但是一般逮不住开播时间

看项目主页介绍是可以用https://v.douyin.com/iQFeBnt/这种格式

在抖音选择【分享主页】然后获取这个v.douyin.com/xxxx的链接，贴上去之后软件报错

请问有什么头绪吗

<img width="866" alt="微信图片_20240618232504" src="https://github.com/ihmily/DouyinLiveRecorder/assets/32565933/38bd5d2b-6310-426f-aa50-59feea399f30">

**Comment by ihmily** [comment]
>看项目主页介绍是可以用[https://v.douyin.com/iQFeBnt/这种格式](https://v.douyin.com/iQFeBnt/%E8%BF%99%E7%A7%8D%E6%A0%BC%E5%BC%8F)

你的地址格式写错了，你贴图中的地址是作者主页地址，这个是不支持的，你需要输入主播直播页面地址

比如你贴图中的正确地址应该是：https://live.douyin.com/ijKMPHh6 

具体参考：https://github.com/ihmily/DouyinLiveRecorder/issues/231#issuecomment-2095262691
