### ISSUE TITLE
请教下可以跳过开头30s左右的系统代理检测中，请耐心等待过程吗

### ISSUE THREAD

**Issue by xueocean** [ihmily/DouyinLiveRecorder#435]
请教下可以跳过开头30s左右的系统代理检测中，请耐心等待过程吗，有时候主播开播才想起来录制，要等待一会就错过了些内容

**Comment by sysdefault** [comment]
你是源码运行的话，注释掉main.py的代理检测那一段代码

**Comment by 1nhandsome** [comment]
> 你是源码运行的话，注释掉main.py的代理检测那一段代码

怎么注释啊 大佬

**Comment by sysdefault** [comment]
> > 你是源码运行的话，注释掉main.py的代理检测那一段代码
> 
> 怎么注释啊 大佬

main.py的大概第1536行开始这里这一段，前后两行都加上"""像这样：
"""
try:
    # 录制国外平台时，如果开启了电脑全局/规则代理，可以正常录制，但强烈建议还是配置一下代理地址，否则非常不稳定
    # 检测电脑是否开启了全局/规则代理（如果身处国外请忽略）
    print('系统代理检测中，请耐心等待...')
    response_g = urllib.request.urlopen("https://www.google.com/", timeout=15)
    global_proxy = True
    print('\r全局/规则网络代理已开启√')
except HTTPError as err:
    print(f"HTTP error occurred: {err.code} - {err.reason}")
except URLError as err:
    # print("URLError:", err.reason)
    print('INFO：未检测到全局/规则网络代理，请检查代理配置（若无需录制海外直播请忽略此条提示）')
except Exception as err:
    print("An unexpected error occurred:", err)
"""

**Comment by 1nhandsome** [comment]
感谢

**Comment by ihmily** [comment]
下载最新版，可以在config/config.ini配置文件中 设置，将下面的配置改为是，即可以跳过检查

>﻿[录制设置]
>是否跳过代理检测（是/否） = 是
