### ISSUE TITLE
想请教一下，如何通过live.douyin.com/xxx链接得到room_id

### ISSUE THREAD

**Issue by Eternity999** [ihmily/DouyinLiveRecorder#439]
尝试在msg_push.py加入了iOS端的Bark推送，想实现点击消息推送通过抖音URL Scheme（dypay1128://live?room_id={{room_id}}）跳转进入直播间。

发现只有通过requests.get抖音短链（v.douyin.com/iQLgKSj/）跳转（webcast.amemv.com/douyin）才能匹配出room_id。

而平时没开播时，通过抖音ID，只能得到live.douyin.com/xxx的链接，而没有短链。而且url_config.ini也是储存live.douyin.com/xxx。

想请教下有没有什么办法通过live.douyin.com/xxx链接得到room_id，进而实现通过消息推送跳转进入直播间。

**Comment by Max-Tortoise** [comment]
您好，请问一下没开播的时候，如何通过抖音ID(MS开头的那种)，得到直播链接(`https://live.douyin.com/xxxx`)

**Comment by Eternity999** [comment]
你说的抖音ID，是浏览器打开主页显示的那个自定义或默认抖音号吗？直接填在xxxx那里，用浏览器访问，是能进入未开播的直播间的，只是显示直播已结束

Max-Tortoise ***@***.***>于2024年7月10日 周三下午2:00写道：

**Comment by Max-Tortoise** [comment]
好的谢谢，我明白了。那个抖音号确实是能进入直播间。这对我来说就足够了，因为抖音不像b站那样，不开播的时候也有个进入直播间的入口。
M开头的是URL中的用户ID，那个是应该是没法变的。

**Comment by PengOvO** [comment]
大佬你好，我看 issues 里你有提到关于 Bark 推送的问题，所以想请教一下，不知是否有空？

就是我将微信推送接口链接改成了 Bark 的：

![Snipaste_2024-07-29_19-58-35](https://github.com/user-attachments/assets/be08cae3-4895-4dbd-ac3d-53091561b714)

但是开播通知推送后，却没有具体直播间信息，只显示"NoContent"。

![IMG_2379](https://github.com/user-attachments/assets/e8e74978-4bbc-42a5-bcd6-a10b491ec026)

所以想请教下该如何解决或者告诉我您是如何设置的呢？如果有空回答的话，非常感谢！
