### ISSUE TITLE
Tiktok录制条数

### ISSUE THREAD

**Issue by d5f4sd6f84dfa** [ihmily/DouyinLiveRecorder#440]
![image](https://github.com/ihmily/DouyinLiveRecorder/assets/168329204/b29cd453-d3f0-45ce-92da-6a08c46a716f)
兄弟们，别添加太多，不然会挂壁

**Comment by Andy8r0X** [comment]
config.ini 改成 
同一时间访问网络的线程数 = 1
循环时间(秒) = 300

亲测200个直播间不卡，循环时间调更高会更保险，但是会少录

**Comment by d5f4sd6f84dfa** [comment]
> 试试用浏览器无痕模式找到tiktok cooies，循环时间改500， 无痕模式是未登入的cookies可以经常换，比较不容易被封，用登入账号的cookies比较危险 未登入cookies缺点是看不见被系统锁18+直播(DouyinLiveRecorder会跳过该直播间)，也看不见付费订阅者限定直播

我现在只改到了400秒，怕被封，不敢改低

**Comment by yuka46** [comment]
這個配置 pandatv也適用 保證不會被IP封控
用默認 3 120秒 很快就會被封控了
