### ISSUE TITLE
文件名称如何自定义

### ISSUE THREAD

**Issue by weakeng** [ihmily/DouyinLiveRecorder#443]
请问怎么自定义文件名称，还有window版本，我改了主播名称但是录制的视频主播还是原来的名字

**Comment by ihmily** [comment]
修改后重新启动程序后生效

**Comment by weakeng** [comment]
有时不成功的，有没有自定义文件输出的名称，如：主播id+自定义时间格式

**Comment by weakeng** [comment]
还有bigo有些直播间录制失败，
其他bigo在播直播间正常录制（并没有达到最大录制数，mie.1012也在播）
这个直播间失败：
https://www.bigo.tv/cn/mie.1012,主播: 欢迎来到Mie_🍑的直播间
