### ISSUE TITLE
虎牙录制直播有问题

### ISSUE THREAD

**Issue by mo00-stack** [ihmily/DouyinLiveRecorder#446]
昨天开始录制虎牙直播时每次录到两分钟就录制完成，然后又开始录制，这个是怎么回事？

**Comment by whitepaper-y** [comment]
同问，老哥解决了吗

**Comment by ihmily** [comment]
直播间地址提供一下

**Comment by NALEUY0716** [comment]
https://www.huya.com/729176
大佬星秀区都是这样，别的区什么游戏区都还正常

**Comment by ihmily** [comment]
> 昨天开始录制虎牙直播时每次录到两分钟就录制完成，然后又开始录制，这个是怎么回事？

已发布最新3.0.6版本，其中有修复该问题 https://github.com/ihmily/DouyinLiveRecorder/releases/tag/v3.0.6
