### ISSUE TITLE
抖音直播地址可以支持用抖音号吗

### ISSUE THREAD

**Issue by m13056992816** [ihmily/DouyinLiveRecorder#447]
https://live.douyin.com/数字
这个格式的地址会不会因为主播修改抖音号而变化呢？

可以增加备注或者分组功能吗 @ ihmily

**Comment by ihmily** [comment]
>https://live.douyin.com/数字
>这个格式的地址会不会因为主播修改抖音号而变化呢？

这个数字不是抖音号，也不是用户ID，也不是房间ID，是WebID，至于是否会因为修改抖音号而改变，这个我也没测试过

支持抖音号，你能用地址打开主播直播页面，应该就可以

具体地址形式请参考：
https://github.com/ihmily/DouyinLiveRecorder/issues/231#issuecomment-2095262691
