### ISSUE TITLE
大佬，这个抖音的有个别的不能录制，不知道怎么回事，cookies换了自己的，也不行！帮忙抽时间看看！

### ISSUE THREAD

**Issue by 0zxcvbnm0** [ihmily/DouyinLiveRecorder#45]
![IMG_20230919_233041](https://github.com/ihmily/DouyinLiveRecorder/assets/144042768/b50c3e34-0d47-4c2a-b2c4-238b53f2c07d)
这是自带的，显示错误！下面这个是自己的cookies，也显示错误！
![IMG_20230919_233009](https://github.com/ihmily/DouyinLiveRecorder/assets/144042768/1720962d-5bbf-484f-bdf5-dfd68593ffd3)
这是自己的cookies，请求大佬抽时间帮忙看一下！

**Comment by ihmily** [comment]
能获取到数据，但在解析的时候遇到了特殊字符，反序列化失败了导致报错。下个版本更新

**Comment by ihmily** [comment]
已在v2.0.1版本解决
