### ISSUE TITLE
斗鱼平台的直播码率较低

### ISSUE THREAD

**Issue by leow44** [ihmily/DouyinLiveRecorder#455]
你好开发者！在开头感谢你付出，但是在使用的过程中发现不管斗鱼直播间中码率是多少，下载下来的视频码率不会大于2000kbps。

**Comment by ihmily** [comment]
### 正常录制60帧原画 

![image](https://github.com/ihmily/DouyinLiveRecorder/assets/114978440/f95a851f-0bdf-43cc-994b-0cb93818483a)
![image](https://github.com/ihmily/DouyinLiveRecorder/assets/114978440/6a4d509d-e74c-42b0-b6a7-fe549f7f0b16)
![image](https://github.com/ihmily/DouyinLiveRecorder/assets/114978440/b70a5870-976a-4cd5-b294-3ee650563050)

**Comment by leow44** [comment]
你好开发者 我使用的版本是3.0.5不确定这是不是由于版本的问题引起的
 以下是相关设置的截图以及视频码率的信息

**Comment by leow44** [comment]
![Uploading Snipaste_2024-07-05_16-45-54.png…]()

**Comment by leow44** [comment]
![Snipaste_2024-07-05_16-46-44](https://github.com/ihmily/DouyinLiveRecorder/assets/174618152/6c1a1cba-2574-40ee-a6b1-9c11440dd10b)

**Comment by leow44** [comment]
![Snipaste_2024-07-05_16-45-54](https://github.com/ihmily/DouyinLiveRecorder/assets/174618152/27b7b074-7dbc-4dee-83da-cc8dc1802f5c)

**Comment by leow44** [comment]
![Uploading Snipaste_2024-07-05_17-14-06.png…]()

**Comment by ihmily** [comment]
用最新3.0.6版本 下载 https://github.com/ihmily/DouyinLiveRecorder/releases/tag/v3.0.6
