### ISSUE TITLE
时光直播加入-听说流星合并

### ISSUE THREAD

**Issue by weakeng** [ihmily/DouyinLiveRecorder#456]
![Uploading 微信图片_20240704100418.jpg…]()
可以加入时光直播嘛，流星的和cc直播的跑这
![微信图片_20240704100412](https://github.com/ihmily/DouyinLiveRecorder/assets/44659969/f71a02fe-aaed-4cfa-8d59-b07c3455b0bf)
里来了

**Comment by ihmily** [comment]
代码已更新该直播录制
