### ISSUE TITLE
快手直播录制不了

### ISSUE THREAD

**Issue by 1032740078** [ihmily/DouyinLiveRecorder#457]
快手直播录制不了,一直提示ip被封了,但是我打开web页面的快手直播是可以正常播放的

**Comment by ilikeulinux** [comment]
我和你一模一样的问题，太苦恼了。

**Comment by mao527147880** [comment]
加入cookie就可以了

**Comment by ilikeulinux** [comment]
> 加入cookie就可以了

加了cookie一样也会出现这样的提示。

**Comment by mao527147880** [comment]
需要websockt那个cookie

**Comment by ilikeulinux** [comment]
> 需要websockt那个cookie

![QQ截图20240712121313](https://github.com/user-attachments/assets/b2838c2b-8e78-4d66-ab50-6145ec50f043)
我一直用的是这个cookie，是你说的那个吗？

**Comment by ihmily** [comment]
快手录制目前只能说是 直播的时候去手动添加直播间地址录制，录制完后将直播间地址删掉或者开头加#，以防程序循环检查，检查几次就异常了。
