### ISSUE TITLE
求帮助T-T  ！winktv有一堆cookie，实在找不到哪个是录制需要的。。。穷举法试了半天

### ISSUE THREAD

**Issue by zhao511117** [ihmily/DouyinLiveRecorder#459]
![微信截图_20240705025456](https://github.com/ihmily/DouyinLiveRecorder/assets/20245151/c911d93e-5375-4c71-b250-e74be194a1d1)
![image](https://github.com/ihmily/DouyinLiveRecorder/assets/20245151/ab9800ca-b111-4ee4-8833-b6716274a8b4)
书写格式是要写成 winktv_cookie = xxx = yyy 这样的格式吗

**Comment by zhao511117** [comment]
![image](https://github.com/ihmily/DouyinLiveRecorder/assets/20245151/e1ea97b3-ea30-4b2c-8681-d245de170f8f)
仿照tiktok的cookies写成这样也不行

**Comment by yyhyyhhyy** [comment]
在请求头中找到Cookie项然后直接全部复制到配置文件中
