### ISSUE TITLE
大佬，我看你快手更新了，今天测试了一下，还是报错啊

### ISSUE THREAD

**Issue by 0zxcvbnm0** [ihmily/DouyinLiveRecorder#46]
![IMG_20230920_180544](https://github.com/ihmily/DouyinLiveRecorder/assets/144042768/7dd436e3-5768-4325-9d3e-3af922bed0ed)
快手链接还是报错！更新到1.0.9了！大佬看下，怎么回事！

**Comment by ihmily** [comment]
你这个链接在我这是正常的

![image](https://github.com/ihmily/DouyinLiveRecorder/assets/114978440/818e5c09-c605-4946-bb8d-6272b9983942)
