### ISSUE TITLE
时光直播录不了

### ISSUE THREAD

**Issue by mo00-stack** [ihmily/DouyinLiveRecorder#469]
大佬，时光直播录不了，直播链接放进去就显示未知链接，此条跳过
时光直播：https://www.rengzu.com/181873

**Comment by whitepaper-y** [comment]
一样需求，大佬看下

**Comment by ihmily** [comment]
该平台需要等下个版本3.0.7发布，或者如果会打包程序的话，自己打包最新版也可以，仓库里该录制代码已经有了。

**Comment by whitepaper-y** [comment]
大佬能尽快更新3.0.7吗，谢谢了
