### ISSUE TITLE
作者大大辛苦！

### ISSUE THREAD

**Issue by TaXueYingChuXia** [ihmily/DouyinLiveRecorder#478]
作者大大等吧录制程序 添加帧数设置吗？最近录制出来的抖音原画都是30帧 ，之前几个版本出来都是60，人比较笨，不会搞，或许作者大大有这个功能

**Comment by ihmily** [comment]
### 原画不代表一定60帧！

录制是没问题的，至于录制多少帧，得看直播间最高支持多少帧，如果最高就30帧，那么录制原画出来也不可能60帧呀，具体帧数取决于主播的开播设置，开播设置最高只有30帧，那么录制原画就只有30帧。

比如下面直播间是有60帧的，原画录制出来也是60帧
https://live.douyin.com/510417936910

![image](https://github.com/user-attachments/assets/71f1095b-0087-4462-a9d3-b763d38a02c9)
