### ISSUE TITLE
PandaTV error

### ISSUE THREAD

**Issue by renanzaii** [ihmily/DouyinLiveRecorder#479]
| ERROR    | utils:wrapper:18 - 错误信息: type: KeyError, 'bjInfo' in function get_pandatv_stream_data at line: 1024
想请问这是出了什么问题才会有这个错误

**Comment by ihmily** [comment]
### 两种可能

1网络不稳定
2如果直播需要登录才能观看，那么你要自己获取登录后的cookie，填写在config配置文件中对应位置

**Comment by renanzaii** [comment]
那应该是我网络不太稳定 感谢回答
