### ISSUE TITLE
快手直播录制异常

### ISSUE THREAD

**Issue by SxitDark** [ihmily/DouyinLiveRecorder#486]
软件提示IP被封禁并显示错误信息
实际上能观看网页直播
由于没有提供导入快手cookie方法，暂时无法排除是否需要登录才能录制的可能
![擷取](https://github.com/user-attachments/assets/26be3057-18b1-4cd6-9d1d-bee3c4573652)

**Comment by Aysch** [comment]
我也用不了

**Comment by SxitDark** [comment]
需要手动导入cookie，然后就能正常录制
[参考教程](https://www.bilibili.com/video/av688317045/)

**Comment by sidazhang123** [comment]
快手封控模型都神了，我改用原生requests+浏览器正常访问的全部headers，1秒1次while了一个小时，偶尔封但重试又解了。但放上服务器5分钟调一下没俩小时就封死了。绝对是行为检测不是简单的死规则。
