### ISSUE TITLE
试了下最新版，B站还是有录制双文件夹BUG 

### ISSUE THREAD

**Issue by fgo1212** [ihmily/DouyinLiveRecorder#489]
测试直播间https://www.douyu.com/1607787，最新版配置文件URL_config.ini有些可以正常识别主播名字了，有些不能比如https://live.bilibili.com/11739194,主播: 房间号11739194的直播，还有录制还是会出现双文件夹bug，录制会自动分段然后录像会保存在2个不同名文件夹里
![QQ截图20240719140354](https://github.com/user-attachments/assets/cce961e1-8c66-496b-b062-a195a80f9900)

**Comment by Hertz221** [comment]
是不是你自己修改过主播名字，然后启动后主播已经在播了？如果是的话就老BUG了，修改名字后启动时正在直播就生效，中途断了或者开播你自定义名字就不生效。

**Comment by fgo1212** [comment]
> 是不是你自己修改过主播名字，然后启动后主播已经在播了？如果是的话就老BUG了，修改名字后启动时正在直播就生效，中途断了或者开播你自定义名字就不生效。

没有手动改过，名字是软件自动生成的

**Comment by ihmily** [comment]
已修复
