### ISSUE TITLE
抖音直播录制，直播结束后程序还在录制

### ISSUE THREAD

**Issue by Fairykingslan** [ihmily/DouyinLiveRecorder#506]
抖音直播录制，直播结束后程序还在录制
![image](https://github.com/user-attachments/assets/b59fabfa-f82a-4265-b1ed-67f6364e62b0)
直播结束截图
![image](https://github.com/user-attachments/assets/d87490e5-a582-417f-bd36-28f9c4f8627e)

**Comment by antonio65421** [comment]
之前的版本也会.录出来的东西会不完整 只能定期重开程式避免

**Comment by ihmily** [comment]
因为录制流有延迟，直播间结束了 ，但是流还没录制完，就会出现没有同时结束的情况，如果此时关闭录制程序，录制的视频就是不完整的。

**Comment by icysaintdx** [comment]
> 因为录制流有延迟，直播间结束了 ，但是流还没录制完，就会出现没有同时结束的情况，如果此时关闭录制程序，录制的视频就是不完整的。

这个判断应该是有问题的，我这网页已经直播结束1个多小时了，服务器上还在录制。。。。服务器上怎么中止  杀进程？

**Comment by icysaintdx** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。
