### ISSUE TITLE
抖音录制保存文件夹和文件名问题反馈

### ISSUE THREAD

**Issue by slmepipi** [ihmily/DouyinLiveRecorder#530]
目前版本：3.0.6版本
问题反馈：有主播名称有特殊符合如：♥ - 角标 能否格式化仅保留正常字符，例如主播名称：slme皮皮♥格式化为slme皮皮

**Comment by liwangdong** [comment]
可以通过自定义主播名解决

**Comment by slmepipi** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
