### ISSUE TITLE
录制抖音原画画质异常

### ISSUE THREAD

**Issue by ransxd** [ihmily/DouyinLiveRecorder#54]
问题描述：
config画质设置为原画，录制后画质与原画不同，通过IDM直接下载原画flv流帧率为60，DouyinLiveRecorder录制的流帧率为45

![image](https://github.com/ihmily/DouyinLiveRecorder/assets/17682131/f8cc6297-e51e-47ab-983e-c8f97f71e3f4)
此为IDM下载的流（和隔壁Bililive-go录制的流一致）
![image](https://github.com/ihmily/DouyinLiveRecorder/assets/17682131/9c880d66-f154-43ca-82f7-64a3582be28b)
此为DouyinLiveRecorder录制的流

环境：
腾讯云广州S6 8C16G 400Mbps

配置文件：
[录制设置]
直播保存路径（不填则默认） = 
视频保存格式ts|mkv|flv|mp4|ts音频|mkv音频 = flv
原画|超清|高清|标清 = 原画
是否使用代理ip（是/否） = 否
代理地址 = 
同一时间访问网络的线程数 = 3
循环时间(秒) = 30
排队读取网址时间(秒) = 0
是否显示循环秒数 = 否
ts格式分段录制是否开启 = 否
视频分段大小(兆) = 10000
ts录制完成后自动增加生成mp4格式 = 否
ts录制完成后自动增加生成m4a格式 = 否
追加格式后删除原文件 = 否
生成时间文件 = 否

[推送配置]
直播状态通知(可选微信|钉钉或者两个都填) = 
钉钉推送接口链接 = 
微信推送接口链接 = 
钉钉通知@对象(填手机号) = 

[Cookie]
抖音cookie(录制抖音必须要有) = ttwid=1......IsDouyinActive=false
快手cookie = 
tiktok_cookie = 
虎牙cookie = 
斗鱼cookie = 
yy_cookie = 
b站cookie =

**Comment by ihmily** [comment]
麻烦提供一下你录制的直播间地址

**Comment by DingKuiqing** [comment]
> 麻烦提供一下你录制的直播间地址

https://live.douyin.com/zbcll0715
