### ISSUE TITLE
抖音錄製BUG

### ISSUE THREAD

**Issue by ghost** [ihmily/DouyinLiveRecorder#541]
請問抖音錄製完成，只有聲音沒有畫面是什麼問題呢，用的MP4

**Comment by GD2021** [comment]
你是语音直播间把

**Comment by AR-444** [comment]
> 你是语音直播间把

不是的，原本的是mp4檔有畫面的，但是那天不知為何突然出BUG了

**Comment by AR-444** [comment]
> 請問抖音錄製完成，只有聲音沒有畫面是什麼問題呢，用的MP4

**Comment by ihmily** [comment]
可能是播放器不支持对应视频编码，使用其他播放器如potplayer试试
