### ISSUE TITLE
抖音和小红书公司和家里电脑无法录制直播，提示检查网络

### ISSUE THREAD

**Issue by anlisi** [ihmily/DouyinLiveRecorder#542]
![微信图片_20240808203601](https://github.com/user-attachments/assets/161fa15b-0f54-4500-bd8e-64097539333e)

家里电脑无法录制直播，提示检查网络 。唯一一样的是同样的 clash verge
提示如下：
main :start record:1229 -错误信息:Command’['ffmpeg’,verbose，Mozilla/5.0(Linux; Android 11.rw timeout，30000000-hide bannerSAMSUNG-loglevelerroruser agentSM-G973U) ApplewebKit/537.36 (kHTM, like Gecko) SamsungBrowser/14.2 chrome/87.0. 4280. 141 Mobile Safari/537.36'prot20000col whitelist’rtmp, crypto,file,http, https, tcp, tls, udp, rtp ,-thread queue size,，1024’,-analyzeduration，10000000http://live-play.xhscdn.com/live/569341072244950106.probesize-fflags +discardcorruptf1v?uid=5eld9ce20000000001003d32’,reconnect_delay max ,'-bufsize ,8000kdn60，reconnect streamesncopy,’’reconnect at eof'max muxing queue size1024correctts overflow ,c:atc'yaacE:/软件/录屏软segment’,-segment time，1800’,segment formatmp4reset timestamps真播求制软代/De yinsivepecorder.v3.0.6 _5/DouvinliveRecorder v3.0.6/bouvinliveRecordcr:v3.0.6/downloads/小红书直播/吴returned non-zero exit status 3419392776.发生错误的行数:1226
吴言 2024-08-08 20:34:23 直播录制出错,请检查网络

**Comment by anlisi** [comment]
@Hmily 希望得到帮助，谢谢

**Comment by ihmily** [comment]
会不会是小红书直播间地址失效了？目前小红书直播间地址都是一次性的，每次主播开播都会变化

**Comment by ihmily** [comment]
麻烦提供一些你无法录制的直播间地址，正在直播的
