### ISSUE TITLE
Problem of not being able to register with account names marked with dots in bigo live

### ISSUE THREAD

**Issue by strongerr1234** [ihmily/DouyinLiveRecorder#547]
Problem of not being able to register with account names marked with dots in bigo live. not recording if account id has marked with dots. thx

**Comment by ihmily** [comment]
What does this mean? Could you please explain it more clearly?

**Comment by ihmily** [comment]
I get it, I will fix the bug.

**Comment by ihmily** [comment]
please download the latest version https://github.com/ihmily/DouyinLiveRecorder/releases/tag/v3.0.7, it work normally

**Comment by strongerr1234** [comment]
> please download the latest version https://github.com/ihmily/DouyinLiveRecorder/releases/tag/v3.0.7, it work normally

same. issue still going on with v3.0.7 :(

**Comment by ihmily** [comment]
can you provide the address of the live streaming room ？I just try "https://slink.bigovideo.tv/C7Ur6l" , the account ID has dots, but it works on 3.0.7

**Comment by strongerr1234** [comment]
> can you provide the address of the live streaming room ？I just try "https://slink.bigovideo.tv/C7Ur6l" , the account ID has dots, but it works on 3.0.7

but my url link like this : https://www.bigo.tv/cn/H.5656 so not working with this url can u fix it? cause my playlist full with these as link url

thx

**Comment by strongerr1234** [comment]
> can you provide the address of the live streaming room ？I just try "https://slink.bigovideo.tv/C7Ur6l" , the account ID has dots, but it works on 3.0.7

and also Permanent registration is not possible with your method. Because those URLs are given randomly and change when online. Thus, the registrations are missed. :( i hope to fix
