### ISSUE TITLE
无法录制afreecatv 请求作者大大帮帮忙

### ISSUE THREAD

**Issue by lucky-666666** [ihmily/DouyinLiveRecorder#550]
![屏幕截图 2024-08-16 165943](https://github.com/user-attachments/assets/140eb04b-637f-49a8-a6b3-b61e0148e089)

**Comment by ken59755** [comment]
同问

**Comment by ken59755** [comment]
刚找到,在配置文件中代理地址栏 前加http://
示例:代理地址 = http://127.0.0.1:7890
