### ISSUE TITLE
关于twitch录制

### ISSUE THREAD

**Issue by JK1245165** [ihmily/DouyinLiveRecorder#559]
虽说默认设置的是原画画质 但实际录完 视频清晰度画质要比直播画质来的差些 其他平台像afreecatv到没什么问题 
![QQ图片20240821171903](https://github.com/user-attachments/assets/338a3746-42ed-4f0e-90b7-1b05b1318ff6)
![QQ图片20240821171923](https://github.com/user-attachments/assets/8c0eb96c-c832-49ea-9387-0bea6f986c38)
画质对比

**Comment by ningsibuqu** [comment]
@ihmily

**Comment by ihmily** [comment]
最新3.0.9版已修复 支持1080 60P录制
