### ISSUE TITLE
有些主播会显示解析错误

### ISSUE THREAD

**Issue by 2413181638** [ihmily/DouyinLiveRecorder#561]
![1724269674867](https://github.com/user-attachments/assets/fb8c0a30-91a9-47ed-9b5b-96c246bb268d)

**Comment by 2413181638** [comment]
是手机版直播，电脑上不能看的，

**Comment by hugepower** [comment]
> 是手机版直播，电脑上看不了的，

不仅看不了，而且电脑端直播页面还不显示直播源信息，所以这个问题基本上无解。

**Comment by 2413181638** [comment]
> > 是手机版直播，电脑上看不了的，
> 
> 不仅看不了，而且电脑端直播页面还不显示直播源信息，所以这个问题基本上无解。

好吧，可能是app里面内置的链接，还是希望能有其他办法获取到就好了
