### ISSUE TITLE
v3.0.6  运行报错反馈

### ISSUE THREAD

**Issue by slmepipi** [ihmily/DouyinLiveRecorder#569]
运行新线程,传入地址 https://live.douyin.com/745964462470
URL Error: <urlopen error [Errno 11004] getaddrinfo failed>
第一次获取数据失败：https://live.douyin.com/745964462470 准备切换解析方法'NoneType' object has no attribute 'group'
URL Error: <urlopen error [Errno 11004] getaddrinfo failed>
错误信息: Expecting value: line 1 column 1 (char 0) 发生错误的行数: 191
序号1 网址内容获取失败,进行重试中...获取失败的地址是:('原画', 'https://live.douyin.com/745964462470', '')

如何解决呀

**Comment by AR-444** [comment]
我最近三天也有類似錯誤，不過開播時錄製正常

**Comment by ihmily** [comment]
大概率是网络的问题 可以重启电脑解决
