### ISSUE TITLE
出现如下错误提示是什么原因？

### ISSUE THREAD

**Issue by ilikeulinux** [ihmily/DouyinLiveRecorder#57]
![QQ截图20231009075345](https://github.com/ihmily/DouyinLiveRecorder/assets/41497656/339647e8-f6cf-4ef7-9595-296c4bd7c4bf)
![QQ截图20231009075406](https://github.com/ihmily/DouyinLiveRecorder/assets/41497656/e5b2eefa-571e-40f2-9ab7-efa0d2b32384)

**Comment by Hertz221** [comment]
我也一样，不过也能录
