### ISSUE TITLE
抖音能否支持录制HEVC编码

### ISSUE THREAD

**Issue by jiuqianyuan** [ihmily/DouyinLiveRecorder#570]
发现工具录制的视频都是264编码，但在网页端看直播是265编码的

**Comment by jiuqianyuan** [comment]
> 

>

**Comment by jiuqianyuan** [comment]
> 理论上可以获取HEVC编码的 但h264的通用一点，而且大部分播放器都支持播放， 像HEVC编码的Windows系统自带播放器都无法解码播放，所以没有用h265的流。

都知道去下载了，怎么也得用上potplayer播放器了，265理论不是画质和体积更优吗，建议大佬考虑下

**Comment by ningsibuqu** [comment]
> 理论上可以获取HEVC编码的 但h264的通用一点，而且大部分播放器都支持播放， 像HEVC编码的Windows系统自带播放器都无法解码播放，所以没有用h265的流。

3.0.8开始使用h265了吗 发现一个电脑直播的主播录制下来是h265 怎么更改为264呢？

**Comment by jiuqianyuan** [comment]
> > Bot detected the issue body's language is not English, translate it automatically.
> 
> > Theoretically, it is possible to obtain HEVC encoded data, but h264 is more general, and most players support playback. For example, the built-in player of Windows system cannot decode and play HEVC encoded data, so there is no h265 stream.
> 
> Have you started using h265 in 3.0.8? I found that a computer live broadcast host recorded h265. How to change it to 264?

No, there is no change, the format generated by the recording is still h.264 in v3.0.8

**Comment by jiuqianyuan** [comment]
> > 理论上可以获取HEVC编码的 但h264的通用一点，而且大部分播放器都支持播放， 像HEVC编码的Windows系统自带播放器都无法解码播放，所以没有用h265的流。
> 
> 3.0.8开始使用h265了吗 发现一个电脑直播的主播录制下来是h265 怎么更改为264呢？

没有 还是264
