### ISSUE TITLE
pandatv 平台源又升级还是加密 全线崩溃

### ISSUE THREAD

**Issue by Wzybnzy** [ihmily/DouyinLiveRecorder#575]
pandatv 平台源又升级还是加密 全线崩溃 求修复

**Comment by kyung0427** [comment]
> pandatv 平台源又升级还是加密 全线崩溃 求修复

**Comment by kyung0427** [comment]
Panda TV好像在酱汁里添加了什么东西

**Comment by Brother632** [comment]
+1我现在用potplayer添加直播流都没有用

**Comment by yuka46** [comment]
pandatv现在直播源加个防盗链设置会检测来源
不是 www.pandalive.co.kr就会限制访问

**Comment by lucky-666666** [comment]
+1 无法录制

**Comment by idweini** [comment]
能加请求头？

**Comment by yuka46** [comment]
> 能加请求头？

對的 加上header就可以正常錄製了

**Comment by Brother632** [comment]
我想知道用PotPlayer怎么加请求头！

**Comment by lucky-666666** [comment]
> > 能加请求头？
> 
> 對的 加上header就可以正常錄製了

求教，怎么加

**Comment by Shi-PengSheng** [comment]
> > 能加请求头？
> 
> 對的 加上header就可以正常錄製了

请问怎么加header呢？

**Comment by Brother632** [comment]
不是，就没有一个人说一下怎么加请求头吗？

**Comment by ihmily** [comment]
最新版已修复 https://github.com/ihmily/DouyinLiveRecorder/releases/tag/v3.0.7-beta
