### ISSUE TITLE
小红书直播链接不固定

### ISSUE THREAD

**Issue by SameForYou** [ihmily/DouyinLiveRecorder#576]
小红书同一主播直播链接每次都要重新设置过，请问有没有获取固定地址的方法？

**Comment by ihmily** [comment]
这个暂时没找到可行的方案，目前也只能录制时手动输入进行录制

**Comment by ihmily** [comment]
@SameForYou 最新3.0.9版本已支持使用主播主页地址进行直播录制，这样可自定获取最新直播间地址。

**Comment by SameForYou** [comment]
厉害啊，什么原理啊



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年10月30日(周三) 中午12:15
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ihmily/DouyinLiveRecorder] 小红书直播链接不固定 (Issue #576)




 
@SameForYou 最新3.0.9版本已支持使用主播主页地址进行直播录制，这样可自定获取最新直播间地址。
