### ISSUE TITLE
快手录制出错

### ISSUE THREAD

**Issue by 0zxcvbnm0** [ihmily/DouyinLiveRecorder#58]
![IMG_20231011_162406](https://github.com/ihmily/DouyinLiveRecorder/assets/144042768/56820d09-4980-41d1-be38-9e0a8036164f)
快手录制出错，cookie已获取！
![Uploading IMG_20231011_163119.jpg…]()

**Comment by liujianglc** [comment]
我这也是这个错误

**Comment by liujianglc** [comment]
{"result":2,"error_msg":"操作太快了，请稍微休息一下","host-name":"public-bjdy-c11-553.idchb1az1.hb1.kwaidc.com"}
