### ISSUE TITLE
可以整一个界面吗，类似于这样，谢谢，

### ISSUE THREAD

**Issue by Ju9aad** [ihmily/DouyinLiveRecorder#583]
![image](https://github.com/user-attachments/assets/426cb833-a117-4d37-b2af-423ba53c373d)
![QQ20240902-153353](https://github.com/user-attachments/assets/f900c21c-724a-4db6-a716-db501de9bc65)
类似于这个，

**Comment by ihmily** [comment]
emmm...一直有想法 做一个带UI客户端 以及 WEB ，目前来看暂时没有时间搞这个，后续有时间空闲下来再考虑吧。
