### ISSUE TITLE
抖音直播断续问题

### ISSUE THREAD

**Issue by Timothyeee111** [ihmily/DouyinLiveRecorder#589]
主播因信号不好会断开几秒或者苹果手机直播切换到其他页面，直播页面会显示“主播暂时离开“
这时候，录制的文件就会停止，隔一段时间再自动刷新直播间开始新的录制，有时候会隔一个循环时间。
请问可否调整成：录制结束后，持续30秒反复刷新直播间继续检测录制呢？
===============
大佬，我发现用IDM[Internet Download Manager]在浏览器上的抖音直播页面可以抓到链接下载，且不存在上面的断续问题，不知道大佬可不可以整合进去，提供多一个下载源🫶❤️

**Comment by ihmily** [comment]
下载新版本https://github.com/ihmily/DouyinLiveRecorder/releases/tag/v3.0.7 看是否还有此情况，另外  你可以在配置文件中 设置 循环检测时间

**Comment by Sunshinerainbowlittlehorse** [comment]
目前一直到3.0.8还是存在这个问题，不知道是不是网络问题，有些时候能够完整录制下来，有时侯断续

**Comment by ldl2179** [comment]
相同的问题. 4.0.1还是存在

**Comment by ihmily** [comment]
>主播因信号不好会断开几秒或者苹果手机直播切换到其他页面，直播页面会显示“主播暂时离开“
这时候，录制的文件就会停止，隔一段时间再自动刷新直播间开始新的录制，有时候会隔一个循环时间。
请问可否调整成：录制结束后，持续30秒反复刷新直播间继续检测录制呢？

循环时间默认是300秒，自己在配置文件中可以设置的呀。
![image](https://github.com/user-attachments/assets/78d5312f-ff84-48b0-b986-3043f1ca214b)


>大佬，我发现用IDM[Internet Download Manager]在浏览器上的抖音直播页面可以抓到链接下载，且不存在上面的断续问题，不知道大佬可不可以整合进去，提供多一个下载源

嗅探的地址 本项目获取的地址本身就包括IDM嗅探的地址。

**Comment by ldl2179** [comment]
> > 主播因信号不好会中断几秒苹果手机直播切换到其他页面，直播页面会显示“主播暂时离开”或者
> > 这个时候，录制的文件就会停止，隔一段时间再自动刷新直播间开始新的录制，有时会隔一个循环时间。
> > 请问可否调整成：录制结束后，持续30秒反复刷新直播间继续检测录制呢？
> 
> 循环时间默认是300秒，自己在配置文件中可以设置的呀。 ![图像](https://private-user-images.githubusercontent.com/114978440/391943413-78d5312f-ff84-48b0-b986-3043f1ca214b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyMjU2MTQsIm5iZiI6MTczMzIyNTMxNCwicGF0aCI6Ii8xMTQ5Nzg0NDAvMzkxOTQzNDEzLTc4ZDUzMTJmLWZmODQtNDhiMC1iOTg2LTMwNDNmMWNhMjE0Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwM1QxMTI4MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZjY0YzhlNWNmN2U5MmY2ZjJlNzg4NzJhNmMwYjQ3MjQzNjIxZTE0YTE0ZGM1MTUxMmZiMWM5MTM5YzhiY2UxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.48mSLdM7k1PQBzANnS2y_C2n7X2Gy8G6PmCBGV24UcM)
> 
> > 大佬，我发现用IDM[Internet Download Manager]在浏览器上的音直播页面可以抓到链接下载，且不存在上面的断续问题，不知道大佬可以不整合进去，提供多一个下载源
> 
> 嗅探的地址本项目获取的地址本身就包括IDM嗅探的地址。

监测的地址较多，循环设置短了会有大量未开播的账号被反复重新拉取。。。很容易被限IP
