### ISSUE TITLE
v3.0.7-beta - 修复更新 抖音bug 抖音录制不完全

### ISSUE THREAD

**Issue by antonio65421** [ihmily/DouyinLiveRecorder#590]
新版抖音录制不完全 主播开播2小时的话 档案只有30几分钟画面 中间画面 断断续续跳过或不见了 不只一个主播这样 侧试过了 @ihmily

**Comment by wody11** [comment]
我最近试了抖音flv的直播视频源都播放不了，说是编码问题

**Comment by ihmily** [comment]
新发布了稳定版 https://github.com/ihmily/DouyinLiveRecorder/releases/tag/v3.0.7
