### ISSUE TITLE
抖音录播主播下播后停止 最后一个录制文件无法打开 

### ISSUE THREAD

**Issue by GitHub-HUI-rgb** [ihmily/DouyinLiveRecorder#591]

**Comment by ihmily** [comment]
请使用最新版3.0.9版本 ，如果停止录制程序，可以运行文件夹内的 `StopRecording.vbs` 脚本文件，如果需要停止其中某个直播间的录制，可在URL_config.ini文件中将其直播间地址最前面加上 `#` 停止对应直播间录制。
