### ISSUE TITLE
斗鱼解析地址的url应该怎么写

### ISSUE THREAD

**Issue by jiuwuerqidian** [ihmily/DouyinLiveRecorder#61]
我按照你的范例他显示”暂不支持该平台，请检查链接是否正确“T T

**Comment by ihmily** [comment]
API接口只作为演示，并没有添加斗鱼直播流解析，我只添加了抖音、快手和虎牙直播流解析，如果需要其他直播平台解析，请自己根据代码修改添加，或者有可能哪天我有时间的话会加上。
