### ISSUE TITLE
是否可以新增邮箱推送功能呢

### ISSUE THREAD

**Issue by outline-x** [ihmily/DouyinLiveRecorder#620]
是否可以新增邮箱推送功能呢

**Comment by dhbxs** [comment]
已增加 [https://github.com/ihmily/DouyinLiveRecorder/commit/dbf77669d0c4126af1e20c0eb117a3747e1674d2](https://github.com/ihmily/DouyinLiveRecorder/commit/dbf77669d0c4126af1e20c0eb117a3747e1674d2)

**Comment by dhbxs** [comment]
> 是否可以新增邮箱推送功能呢

已增加 [https://github.com/ihmily/DouyinLiveRecorder/commit/dbf77669d0c4126af1e20c0eb117a3747e1674d2](https://github.com/ihmily/DouyinLiveRecorder/commit/dbf77669d0c4126af1e20c0eb117a3747e1674d2)
