### ISSUE TITLE
建议添加抖音新网址格式

### ISSUE THREAD

**Issue by jiuqianyuan** [ihmily/DouyinLiveRecorder#627]
从关注页面-进入直播间的网址如下
`https://www.douyin.com/follow/live/973688429059`

但软件不支持该网址直接录制，浏览器访问以上网址时也会自动跳转到如下地址
`https://live.douyin.com/973688429059`

建议添加网址格式支持，
另建议支持H.265格式录制，理论上265格式文件更小，画质更高，对能够使用本项目的用户来说，播放也不是问题

**Comment by ihmily** [comment]
>建议添加网址格式支持 

已添加
