### ISSUE TITLE
请问为什么panda录制的视频总是两三分钟就结束了然后重新录制  抖音等其他都没有这个问题     是cookie的问题吗

### ISSUE THREAD

**Issue by charemdamumu** [ihmily/DouyinLiveRecorder#630]
![6a27b99a-8afa-445a-94b4-fdeda0d81a21](https://github.com/user-attachments/assets/7de0ec10-dbff-4846-8327-cd6194911f47)
![b86e8b28-4045-4df6-9e66-0f98c7563f03](https://github.com/user-attachments/assets/120e59ef-840a-4940-888a-c0e8d0291cfa)

**Comment by knight0908** [comment]
你好，哥们 你的cookie值是从哪里提取到的  谢谢~

**Comment by ihmily** [comment]
访问外网网络不稳定就这样，毕竟是下载视频流，对网络要求比较大
