### ISSUE TITLE
小红书一些直播间录制会出错

### ISSUE THREAD

**Issue by yubo205** [ihmily/DouyinLiveRecorder#633]
ERROR    | __main__:start_record:1305 - 错误信息: Command '['ffmpeg', '-y', '-v', 'verbose', '-rw_timeout', '30000000', '-loglevel', 'error', '-hide_banner', '-user_agent', 'Mozilla/5.0 (Linux; Android 11; SAMSUNG SM-G973U) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/14.2 Chrome/87.0.4280.141 Mobile Safari/537.36', '-protocol_whitelist', 'rtmp,crypto,file,http,https,tcp,tls,udp,rtp', '-thread_queue_size', '1024', '-analyzeduration', '20000000', '-probesize', '10000000', '-fflags', '+discardcorrupt', '-i', 'http://live-play.xhscdn.com/live/569400478812444892.flv?uid=66934df9000000000f03754d', '-bufsize', '8000k', '-sn', '-dn', '-reconnect_delay_max', '60', '-reconnect_streamed', '-reconnect_at_eof', '-max_muxing_queue_size', '1024', '-correct_ts_overflow', '1', '-c:v', 'copy', '-c:a', 'aac', '-map', '0', '-f', 'segment', '-segment_time', '1800', '-segment_format', 'mp4', '-reset_timestamps', '1', 'D:/Downloads/ 小红书直播/家家有好货/家家有好货_2024-09-21_12-45-29_%03d.mp4']' returned non-zero exit status 3419392776. 发生错误的行 数: 1302

**Comment by HangTao** [comment]
这个问题，我这里也出现了。作者能解决吗？

**Comment by ihmily** [comment]
最新3.0.9版本已修复小红书录制，请使用小红书作者主页地址进行录制，可持续监控。
