### ISSUE TITLE
电脑进入休眠之后发现程序就会结束录制，在电脑睡眠期间的主播开播也检测不到

### ISSUE THREAD

**Issue by WindyMelodies** [ihmily/DouyinLiveRecorder#636]
作者您好，电脑进入休眠之后发现程序就会结束录制，在电脑睡眠期间的主播开播也检测不到。是我电脑设置的问题吗

**Comment by hugepower** [comment]
### 1. **睡眠模式**（Sleep）
- **工作原理**：睡眠模式是一种低功耗状态，电脑将当前的运行状态（如打开的应用程序和文件）保存在内存中，但大部分硬件（如CPU、显示器、硬盘等）进入低功耗或待机状态，保持最低的能耗。
- **网络和程序行为**：在睡眠模式下，网络连接通常会断开，程序也会暂停运行。大部分情况下，程序无法执行任何操作（例如录制、下载等），直到电脑从睡眠中被唤醒。

### 2. **休眠模式**（Hibernate）
- **工作原理**：休眠模式比睡眠模式更加彻底，电脑将当前的工作状态保存到硬盘，并完全关闭电源。再次启动时，电脑会从保存的状态恢复，但它完全断电，无法继续处理任何任务。
- **网络和程序行为**：由于休眠模式完全断电，网络连接会中断，所有程序都无法继续运行，直到电脑重新开机恢复状态。

---

### 针对问题的解释：

#### 问题 1：**电脑进入休眠后，发现程序结束录制**
- 当电脑进入**睡眠**或**休眠**模式时，程序会暂停或停止运行，因为 CPU 和内存等关键硬件组件停止活动。
- 如果你在录制内容时电脑进入了休眠模式，程序将无法继续处理数据，录制也会因此终止。当电脑恢复后，程序可能不会自动恢复录制，除非有特殊设计。

#### 问题 2：**睡眠期间主播开播检测不到**
- 在电脑**睡眠**模式下，网络连接被断开，导致任何依赖网络的程序（如直播平台的检测程序）无法继续运行。
- 因为电脑处于低功耗状态，无法接收网络数据，也就无法检测到直播通知或网络事件，例如主播开始直播。

简而言之，**睡眠和休眠模式**下电脑会暂停或停止程序的运行，导致录制程序停止工作，网络无法连接，因此也就无法检测到主播的开播。请确保在录制期间设置电脑**不进入睡眠或休眠模式**。

**Comment by ihmily** [comment]
这个要看你设置，如果电脑设置休眠后断网，那就无法检测直播状态了。
