### ISSUE TITLE
抖音录屏无法录制礼物特效

### ISSUE THREAD

**Issue by Joshua-Liu** [ihmily/DouyinLiveRecorder#637]
请问抖音录屏出来的结果只有灯牌，那个不算礼物特效。其他的特效有没有相关参数能配置到config.ini中，进行修改。谢谢啦！

**Comment by OOOOAOOOO** [comment]
礼物特效应该是在客户端渲染的，软件下载的是服务器的视频流，没办法录制礼物特效。灯牌应该比较特殊，是在主播端渲染的

**Comment by ihmily** [comment]
无法支持
