### ISSUE TITLE
更新后报错了,在录制但是没有文件

### ISSUE THREAD

**Issue by weakeng** [ihmily/DouyinLiveRecorder#646]
![2024-09-27_093102](https://github.com/user-attachments/assets/04679236-e38b-4c7c-8e6a-e34ff4911615)

ffmpeg_command
['ffmpeg', '-y', '-v', 'verbose', '-rw_timeout', '15000000', '-loglevel', 'error', '-hide_banner', '-user_agent', 'Mozilla/5.0 (Linux; Android 11; SAMSUNG SM-G973U) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/14.2 Chrome/87.0.4280.141 Mobile Safari/537.36', '-protocol_whitelist', 'rtmp,crypto,file,http,https,tcp,tls,udp,rtp', '-thread_queue_size', '1024', '-analyzeduration', '20000000', '-probesize', '10000000', '-fflags', '+discardcorrupt', '-i', 'https://txpull1.5see.com/live/3619250927090423.flv', '-bufsize', '8000k', '-sn', '-dn', '-reconnect_delay_max', '60', '-reconnect_streamed', '-reconnect_at_eof', '-max_muxing_queue_size', '1024', '-correct_ts_overflow', '1', '-c:v', 'copy', '-c:a', 'copy', '-map', '0', '-f', 'segment', '-segment_time', '1800', '-segment_format', 'mpegts', '-reset_timestamps', '1', 'D:/download/LiveRecorder/时光直播/宝宝星/宝宝星_2024-09-27_09-31-48_%03d.ts']

回滚到5a9ac795e65973a098283e342482f2a9b1fd1123这个commit就好了, 哥你这个有问题2834508509df74be3999adc002cc20439a76b5c5

**Comment by ihmily** [comment]
已修复

貌似是因为你的环境中subprocess.Popen不支持text参数，你的python版本是多少？
