### ISSUE TITLE
请求增加VV星球直播录制

### ISSUE THREAD

**Issue by pinkzhang** [ihmily/DouyinLiveRecorder#648]
此平台APP端的直播间分享链接差不多是这样的：
https://h5webcdn-pro.vvxqiu.com//activity/videoShare/videoShare.html?h5Server=https://h5p.vvxqiu.com&roomId=LP116297158&platformId=vvstar

**Comment by hazzahl** [comment]
同求

**Comment by hfuthippop** [comment]
+1
