### ISSUE TITLE
liveme咨询

### ISSUE THREAD

**Issue by hong9587** [ihmily/DouyinLiveRecorder#652]
按照博主的链接示例也添加了链接，但是检测不到主播正在直播

**Comment by hong9587** [comment]
https://www.liveme.com/us/v/17275272808921912544/index.html?navkey=game&filter=all
https://www.liveme.com/us/v/17275272808921912544/index.html

两种链接都试过了，cookie也添加试过，都不能录制

**Comment by ihmily** [comment]
因为liveme好像最近禁止了国内大陆、香港等地区网络访问
你需要在配置文件中开启代理并填写代理地址
```
是否使用代理ip（是/否） = 是
代理地址 = 
```
然后修改如下配置
```
使用代理录制的平台（逗号分隔） = tiktok, afreecatv, pandalive, winktv, flextv, popkontv, twitch, showroom, liveme
```
即在原始配置的基础上加上了liveme

### 下个版本会将其更新为海外平台，默认使用代理录制
