### ISSUE TITLE
To stop recording

### ISSUE THREAD

**Issue by ebtemesk5** [ihmily/DouyinLiveRecorder#656]
To stop liverecording,  Is it correct to add # before the address of the URL_config.ini file??

ex)  #https://www.pandalive.co.kr/live/play/bara0109, # https://www.pandalive.co.kr/live/play/bara0109

I've tried it, but the recording doesn't stop

I need your help

**Comment by ihmily** [comment]
@ebtemesk5 This feature will be available in version 3.0.8, it will be released soon. :)

**Comment by ebtemesk5** [comment]
> @ebtemesk5 This feature will be available in version 3.0.8, it will be released soon. :)

thx

 I'm always using DouyinLiveRecorder well
