### ISSUE TITLE
execjs相关报错

### ISSUE THREAD

**Issue by heluo1798** [ihmily/DouyinLiveRecorder#659]
(venv) root@Ubuntu:/opt/DouyinLiveRecorder# pip install execjs
ERROR: Could not find a version that satisfies the requirement execjs (from versions: none)
ERROR: No matching distribution found for execjs
(venv) root@Ubuntu:/opt/DouyinLiveRecorder# deactivate
root@Ubuntu:/opt/DouyinLiveRecorder# python3 main.py
Traceback (most recent call last):
  File "/opt/DouyinLiveRecorder/main.py", line 31, in <module>
    from spider import (
  File "/opt/DouyinLiveRecorder/spider.py", line 24, in <module>
    import execjs
ModuleNotFoundError: No module named 'execjs'
请问这个报错应该如何解决

**Comment by ihmily** [comment]
缺少PyExecJS这个第三方库，执行 `pip install PyExecJS` 安装
