### ISSUE TITLE
已安装requests 但是还报错：ModuleNotFoundError: No module named 'requests'

### ISSUE THREAD

**Issue by photkey** [ihmily/DouyinLiveRecorder#66]
![image](https://github.com/ihmily/DouyinLiveRecorder/assets/60434581/d0324598-4bc6-41b4-81f0-ec0784f47d9a)

确认已安装requests，但是还会报这个错误，这个是什么情况？

**Comment by ihmily** [comment]
1、会不会是使用的不同解释器，可以使用下面命令在PowerShell查看使用的python解释器路径
```
(Get-Command python).Source
```
2、查看安装的requests包路径
```
pip show requests
```
如果显示的python.exe路径和Lib包路径不在同目录下，请重新配置一下环境。
