### ISSUE TITLE
录制小红书，直播停了，录制不停，手动关闭软件，最后生成视频录制时间只有几秒

### ISSUE THREAD

**Issue by sylvielee0730** [ihmily/DouyinLiveRecorder#660]
录制小红书，直播停了，录制不停，手动关闭软件，最后生成视频录制时间只有几秒。

**Comment by sylvielee0730** [comment]
@ihmily 请问是我操作有问题，还是有bug，从3.0.5用到3.0.6都存在这个问题，直播停止了，它一直不停，一直显示在录制…手动把软件关了，结果生成视频只有几秒。😓

**Comment by SAOJSM** [comment]
尝试按Ctrl+C停止，而不是关闭软件
直接关闭软件会导致录制不完全或档案毁损等问题

**Comment by ihmily** [comment]
@sylvielee0730 最新3.0.9版本 你可以运行StopRecording.vbs 文件 停止直播录制，可安全保存文件。
