### ISSUE TITLE
代理正常运行但无法被检测

### ISSUE THREAD

**Issue by Etherrrr** [ihmily/DouyinLiveRecorder#664]
我在本地的20171端口配置了http代理，并在配置文件中添加了`代理地址=http://127.0.0.1:20171`
使用curl等工具是可以正常走代理，录制tiktok直播也是正常的
但运行main.py时检测是否使用代理始终提示未检测到代理
![image](https://github.com/user-attachments/assets/9dd97899-76bc-4632-b24d-cfc413d21573)

**Comment by ihmily** [comment]
@Etherrrr 能正常录制就行，那个只是检测全局代理的，你也可以在配置文件中把那个检测关掉。

**Comment by Etherrrr** [comment]
了解了，感谢解答

**Comment by GHNature** [comment]
你好，我再服务器上配置了v2ray-a,在命令行通过curl https://www.google.com可以正常获取返回数据，我在config文件配置代理地址http://127.0.0.1:20171，额外录制程序写了tiktok，一运行程序还是会报错·ERROR    - 错误信息: Please check if your network can access the TikTok website normally 发生
错误的行数: 531·。相同配置我在本地windows通过v2ray代理可以正常录制的？可以指导下吗？
