### ISSUE TITLE
3.0.8版本 钉钉 推送失效

### ISSUE THREAD

**Issue by justdoiting** [ihmily/DouyinLiveRecorder#665]
### ⚠️ 确认是否已存在类似问题

- [X] 我已经搜索过issues，没有找到类似问题

### 🔧 运行方式

直接运行的exe文件

### 🐍 如果是使用源代码运行，请选择你的Python环境版本

None

### ⚠️ 确认是否已经重试多次

- [X] 我已经尝试过多次，仍然出现问题

### 🕹 复现步骤

同样配置，3.0.8版本无效，3.0.7正常

### 😯 问题描述

今天更新到3.0.8版本后，发现钉钉推送失效，同样配置情况下3.0.7版本正常推送
<img src="https://p.sda1.dev/19/d3315eebf29776e21a90010665bea1bb/image.png" />

### 📜 错误信息

设置  只通知不录制，未生成日志，界面滚动日志无异常

**Comment by ihmily** [comment]
输入链接的有问题 access_token为什么换行了呢？
![image](https://github.com/user-attachments/assets/26dd9e8e-38da-460e-9b3b-06b54171a595)

**Comment by justdoiting** [comment]
> 输入链接的有问题 access_token为什么换行了呢？ ![image](https://private-user-images.githubusercontent.com/114978440/373835933-26dd9e8e-38da-460e-9b3b-06b54171a595.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgwOTMxMjUsIm5iZiI6MTcyODA5MjgyNSwicGF0aCI6Ii8xMTQ5Nzg0NDAvMzczODM1OTMzLTI2ZGQ5ZThlLTM4ZGEtNDYwZS05YjNiLTA2YjU0MTcxYTU5NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwNVQwMTQ3MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MThiZTdiNDI3MjkxMjQ4MGU4NjI5OGY4ZTQxYzJmNDgxNTA3Nzg5YTJkMWVlNzRjM2I3OTc1YTAwYWJjOTdlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Z5Kl4-TAnjrs8qJ9jdVga91q4AeTGZ2ouSZw99qBacw)

因为窗口不是最大化，实际是没有换行的

**Comment by ihmily** [comment]
刚测试是正常能推送成功的

**Comment by ihmily** [comment]
>{"errcode":310000,"errmsg":"错误描述:关键词不匹配;解决方案:请联系群管理员查看此机器人的关键词，并在发送的信息中包含此关键词;"}

或许你是因为没有匹配成功匹配到关键词才没能发送成功。

注意 `自定义开播推送内容 = [直播间名称] 开播了！时间：[时间]`  其中括号内的不能算在关键词内，只是作为变量名，程序内会将其替换为具体主播名称，如果你的机器人设置的关键词是直播 ，那就匹配不上了，至少要包含直播两个字。

**Comment by justdoiting** [comment]
> > {"errcode":310000,"errmsg":"错误描述:关键词不匹配;解决方案:请联系群管理员查看此机器人的关键词，并在发送的信息中包含此关键词;"}
> 
> 或许你是因为没有匹配成功匹配到关键词才没能发送成功。
> 
> 注意 `自定义开播推送内容 = [直播间名称] 开播了！时间：[时间]` 其中括号内的不能算在关键词内，只是作为变量名，程序内会将其替换为具体主播名称，如果你的机器人设置的关键词是直播 ，那就匹配不上了，至少要包含直播两个字。

对的，确实是关键词匹配的原因，我的机器人关键词是 “直播”，然后自定义开播推送内容改成 “[直播间名称] 正在直播！时间：[时间]” 就成功推送了
