### ISSUE TITLE
作者求救~ 我把直播地址在文档输入了，但没有反应

### ISSUE THREAD

**Issue by blibala** [ihmily/DouyinLiveRecorder#668]
### ⚠️ 确认是否已存在类似问题

- [X] 我已经搜索过issues，没有找到类似问题

### 🔧 运行方式

直接运行的exe文件

### 🐍 如果是使用源代码运行，请选择你的Python环境版本

None

### ⚠️ 确认是否已经重试多次

- [X] 我已经尝试过多次，仍然出现问题

### 🕹 复现步骤

1.https://live.douyin.com/76655970446
2.TS

### 😯 问题描述

如题，在文本里输入了所有地址但打开程式却没有任何反应，一直停留在这个介面
![WeChat 截圖_20241006060905](https://github.com/user-attachments/assets/d65caebf-c83f-4408-b8d1-093237055848)

**Comment by SAOJSM** [comment]
您好，您没贴您网址的文档，要怎么帮您看呢？
