### ISSUE TITLE
Panda  TV录制问题

### ISSUE THREAD

**Issue by knight0908** [ihmily/DouyinLiveRecorder#669]
### ⚠️ 确认是否已存在类似问题

- [X] 我已经搜索过issues，没有找到类似问题

### 🔧 运行方式

直接运行的exe文件

### 🐍 如果是使用源代码运行，请选择你的Python环境版本

None

### ⚠️ 确认是否已经重试多次

- [X] 我已经尝试过多次，仍然出现问题

### 🕹 复现步骤

录制的是Panda TV直播间，在网页中可以正常观看浏览，录制提示以下报错

### 😯 问题描述

请问一下panda Tv录制是否需要填写cookie值，具体的cookie值在哪可以看到？

### 📜 错误信息

![微信截图_20241006150841](https://github.com/user-attachments/assets/444c418e-b44b-46db-9d00-9fbd20d7791c)

**Comment by SAOJSM** [comment]
PandaTV的cookie請先開啟pandalive.co.kr，之後開啟開發者模式，搜索login，複製response裡的cookies貼到config.ini就可以了

Please open pandalive.co.kr, then open dev mode. Search login on search bar. Then paste cookies from response to config.ini

**Comment by knight0908** [comment]
你好，请问是图片中红色这里的cookie值吗
![微信截图_20241020131429](https://github.com/user-attachments/assets/ce2584c6-5974-4322-9102-0925006e5732)

**Comment by ihmily** [comment]
已修复

**Comment by knight0908** [comment]
PANDA TV 录制以下报错，没有开启代理IP录制  已经填写好cookie值

2024-10-31 16:14:44.622 | ERROR    | douyinliverecorder.utils:wrapper:25 - 错误信息: type: JSONDecodeError, Expecting value: line 1 column 1 (char 0) in function get_pandatv_stream_data at line: 362
2024-10-31 16:14:44.623 | ERROR    | __main__:start_record:1228 - 错误信息: list indices must be integers or slices, not str 发生错误的行数: 537
