### ISSUE TITLE
快手直播录制还是不行啊

### ISSUE THREAD

**Issue by 0zxcvbnm0** [ihmily/DouyinLiveRecorder#67]
![IMG_20231030_084257_1](https://github.com/ihmily/DouyinLiveRecorder/assets/144042768/76079fdf-bcaf-4c3f-9193-81d327c9810e)
![Uploading IMG_20231030_084241.jpg…]()

**Comment by ihmily** [comment]
你把自己添加的Cookie去掉，就可以录制了。你们抓的cookie都不正确，你添加后反而不能录制了。

因为改用接口获取数据，现在Cookie失效，快手录制就会出错。过两天我在软件内部添加的这个默认Cookie又失效后，你们需要自己更新Cookie ，注意这个Cookie是移动端的。

**Comment by 0zxcvbnm0** [comment]
![IMG_20231030_092811](https://github.com/ihmily/DouyinLiveRecorder/assets/144042768/dab8e032-62de-41ab-a6ba-455faa3daed2)
删了也不行！

**Comment by ihmily** [comment]
发生错误的直播间地址：
错误信息：
多发几个

**Comment by 0zxcvbnm0** [comment]
![IMG_20231030_114401](https://github.com/ihmily/DouyinLiveRecorder/assets/144042768/0291ec4b-7e6d-4abe-855c-a854852b0ca7)
![IMG_20231030_114055](https://github.com/ihmily/DouyinLiveRecorder/assets/144042768/f10855b6-81ed-4294-8dde-f2e7f93be23d)
总共找了11个直播，只有4个在录制，剩下的都有问题

**Comment by ihmily** [comment]
已经重新发布了2.0.2版本。如果遇到访问太快过频繁的错误信息，请打开快手网页端随便进入一个直播间正常观看，即可解除访问频繁限制。

**Comment by callmezhan** [comment]
失败地址：https://live.kuaishou.com/u/5201314dd 错误信息: 请求过快，请稍后重试浏览其他内容
提示信息：请打开快手直播页面正常随机进入一个直播间，即可解除频繁访问限制
序号2 网址内容获取失败,进行重试中...获取失败的地址是:('https://live.kuaishou.com/u/5201314dd', '主播: 阳')

后台挂上软件，快手 的错误大概这样，必须到点盯着开播，然后尝试作者的方法（不用自己的cookies），才能录制上。我在想有没有一种方法能不被系统监测频繁，或者配合js啥的
