### ISSUE TITLE
3.0.8 录制抖音电脑开播的主播视频能否为 H264 AVC 格式

### ISSUE THREAD

**Issue by ningsibuqu** [ihmily/DouyinLiveRecorder#672]
现在录制电脑开播的主播发现都是HEVC

**Comment by ningsibuqu** [comment]
3.0.6是可以录制h264的 3.0.7开始就不行了

**Comment by ihmily** [comment]
这个是看主播开播设置的，并不是都是HEVC，随机测试了三个电脑游戏直播间，录制出来都是H264

**Comment by ningsibuqu** [comment]
> 这个是看主播开播设置的，并不是都是HEVC，随机测试了三个电脑游戏直播间，录制出来都是H264

https://live.douyin.com/853724007534

随便找了一个现在在播的 3.0.6 h264 
3.0.8 hevc

**Comment by ihmily** [comment]
> 这个是看主播开播设置的，并不是都是HEVC，随机测试了三个电脑游戏直播间，录制出来都是H264

![image](https://github.com/user-attachments/assets/e1b9a168-b8e8-4716-a993-0fb13d1a7e2c)

**跟主播开播设置和设备有关，如果你非要h264，你可以不选择原画录制，选择超清录制，除了原画，其他画质都是抖音官方重新h264编码过的，（至于之前版本的程序为什么可以录制h264，因为之前的bug 有时会出现并没有录制的真正的原画，而录制的其实是超清）。**

![image](https://github.com/user-attachments/assets/63f68be0-a8b6-4111-bee5-04373c86ef63)
