### ISSUE TITLE
bilibili报错

### ISSUE THREAD

**Issue by kkk-aii** [ihmily/DouyinLiveRecorder#673]
### ⚠️ 确认是否已存在类似问题

- [X] 我已经搜索过issues，没有找到类似问题

### 🔧 运行方式

直接运行的exe文件

### 🐍 如果是使用源代码运行，请选择你的Python环境版本

None

### ⚠️ 确认是否已经重试多次

- [X] 我已经尝试过多次，仍然出现问题

### 🕹 复现步骤

Key Takeaways. A 403 Forbidden Error signifies you lack permission to access a certain part of a website – it's like being refused entry by a bouncer. Misconfigured file permissions, .htaccess file errors, and WordPress plugin conflicts are common causes of 403 errors.

### 😯 问题描述

有文件没视频

### 📜 错误信息

Key Takeaways. A 403 Forbidden Error signifies you lack permission to access a certain part of a website – it's like being refused entry by a bouncer. Misconfigured file permissions, .htaccess file errors, and WordPress plugin conflicts are common causes of 403 errors.

**Comment by ihmily** [comment]
你的网络问题
