### ISSUE TITLE
抖音通过作者主页链接即可录制直播间

### ISSUE THREAD

**Issue by JDZhao** [ihmily/DouyinLiveRecorder#674]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues，没有发现相似issue

### 📜 功能描述

抖音通过作者主页链接即可录制直播间，在配置中填写作者主页的链接等开播以后可以自动录制。

### 🌐 举例(可选)

抖音作者链接 https://v.douyin.com/iBmtAF8F/ 
是通过这里获取的![微信图片_20241008093324](https://github.com/user-attachments/assets/4edae2a6-5448-4dde-af9e-cfb0e2ddd9c0)

### 💡 动机

不用等着主播开播的时候才能把地址获取到，可以直接放到配置中，开播自动录制

### 📚 附加信息

无

**Comment by hfuthippop** [comment]
抖音的主页ID和直播ID是两个不同的ID，且不能通过加载主页获取到

**Comment by ihmily** [comment]
支持通过抖音号构造直播间地址，使用方法请参考 https://github.com/ihmily/DouyinLiveRecorder/issues/231#issuecomment-2095262691

**Comment by ihmily** [comment]
主分支代码现已支持主页地址录制，exe打包程序在下个版本更新，此issue关闭
