### ISSUE TITLE
请求新增VV星球与嗨秀直播平台的录制

### ISSUE THREAD

**Issue by mo00-stack** [ihmily/DouyinLiveRecorder#675]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues，没有发现相似issue

### 🌐 举例(可选)

vv星球：https://h5webcdn-pro.vvxqiu.com//activity/videoShare/videoShare.html?h5Server=https://h5p.vvxqiu.com&roomId=LP116198255&platformId=vvstar

嗨秀直播：https://www.haixiutv.com/6093526

**Comment by hfuthippop** [comment]
确实需要这两个平台的录制，感谢大佬

**Comment by ihmily** [comment]
VV星球直播不行，它比较特殊，使用的是TRTC建立连接传输的直播流。嗨秀直播的话下个版本更新

**Comment by ihmily** [comment]
> VV星球直播不行，它比较特殊，使用的是TRTC建立连接传输的直播流。嗨秀直播的话下个版本更新

VV星球直播录制已解决，同样会在下个版本 3.0.9 中支持录制
