### ISSUE TITLE
Afreecatv录制遇到问题

### ISSUE THREAD

**Issue by dian-ji** [ihmily/DouyinLiveRecorder#676]
### ⚠️ 确认是否已存在类似问题

- [X] 我已经搜索过issues，没有找到类似问题

### 🔧 运行方式

直接运行的exe文件

### 🐍 如果是使用源代码运行，请选择你的Python环境版本

None

### ⚠️ 确认是否已经重试多次

- [X] 我已经尝试过多次，仍然出现问题

### 🕹 复现步骤

1.录制的直播间地址是：https://play.afreecatv.com/eunyoung1238/277560594
2.使用的录制格式是：默认

### 😯 问题描述

代理开着能看直播，录制就不行.
![1728403151655](https://github.com/user-attachments/assets/09c2354f-6005-4d12-9631-65c8e82161b2)

**Comment by ihmily** [comment]
网络问题
