### ISSUE TITLE
咨询最新版liveme不能录制

### ISSUE THREAD

**Issue by hong9587** [ihmily/DouyinLiveRecorder#681]
### ⚠️ 确认是否已存在类似问题

- [X] 我已经搜索过issues，没有找到类似问题

### 🔧 运行方式

直接运行的exe文件

### 🐍 如果是使用源代码运行，请选择你的Python环境版本

None

### ⚠️ 确认是否已经重试多次

- [X] 我已经尝试过多次，仍然出现问题

### 🕹 复现步骤

1、直播间两种格式
https://www.liveme.com/us/v/17284567060758376999/index.html?filter=featured&navkey=hot
https://www.liveme.com/us/v/17284567060758376999/index.html
2、录制格式为TS

### 😯 问题描述

链接格式两种都试过，exe运行后检测直播间为等待直播，但主播正在直播。在配置文件中配置了代理后依旧不能录制

**Comment by ihmily** [comment]
liveme官方又更新了

**Comment by hong9587** [comment]
那这块还会继续更新吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年10月9日(星期三) 下午5:04
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ihmily/DouyinLiveRecorder] 咨询最新版liveme不能录制 (Issue #681)














 
liveme官方又更新了

**Comment by ihmily** [comment]
已更新修复 最新版下载：https://wweb.lanzouv.com/iNBk32c69icf

**Comment by hong9587** [comment]
这个错误是我在哪里设置有问题吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "694264724"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月10日(星期四) 下午3:21
***@***.******@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;回复： [ihmily/DouyinLiveRecorder] 咨询最新版liveme不能录制 (Issue #681)



 
在config.ini中添加代理和使用本机全局代理都报错，不能录制




------------------ 原始邮件 ------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年10月10日(星期四) 下午2:57
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ihmily/DouyinLiveRecorder] 咨询最新版liveme不能录制 (Issue #681)














 
已更新修复 最新版下载：https://wweb.lanzouv.com/iNBk32c69icf

**Comment by ihmily** [comment]
>已更新修复 最新版下载：https://wweb.lanzouv.com/iNBk32c69icf
>
>注意，最新liveme需要node环境才能正常获取直播源， 如果没有安装过，请先下载安装nodejs
>地址：https://nodejs.org/dist/latest/node-v22.9.0-x64.msi

nodejs安装了吗？报错提示什么呢？两种情况 1是网络问题，2是node环境没配置好

**Comment by hong9587** [comment]
谢谢大佬，就是环境不对，可以正常使用了，十分感谢。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年10月10日(星期四) 下午3:34
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ihmily/DouyinLiveRecorder] 咨询最新版liveme不能录制 (Issue #681)














  
已更新修复 最新版下载：https://wweb.lanzouv.com/iNBk32c69icf
 
注意，最新liveme需要node环境才能正常获取直播源， 如果没有安装过，请先下载安装nodejs
 地址：https://nodejs.org/dist/latest/node-v22.9.0-x64.msi
  
nodejs安装了吗？报错提示什么呢？两种情况 1是网络问题，2是node环境没配置好

**Comment by hong9587** [comment]
大佬，我发现liveme录制好像还是有点问，录着录着就会断开，不知道是不是liveme平台的原因，好像直播间地址会发生改变。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ihmily/DouyinLiveRecorder"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月10日(星期四) 下午3:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ihmily/DouyinLiveRecorder] 咨询最新版liveme不能录制 (Issue #681)





  
已更新修复 最新版下载：https://wweb.lanzouv.com/iNBk32c69icf
 
注意，最新liveme需要node环境才能正常获取直播源， 如果没有安装过，请先下载安装nodejs
 地址：https://nodejs.org/dist/latest/node-v22.9.0-x64.msi
  
nodejs安装了吗？报错提示什么呢？两种情况 1是网络问题，2是node环境没配置好

**Comment by ihmily** [comment]
可能是网络问题，我这测试 录制了一个多小时，都是正常录制 视频完整的。
