### ISSUE TITLE
直播中的连接填写进去，一直显示没有正在录制的直播

### ISSUE THREAD

**Issue by Bigfengshan** [ihmily/DouyinLiveRecorder#685]
### ⚠️ 确认是否已存在类似问题

- [X] 我已经搜索过issues，没有找到类似问题

### 🔧 运行方式

使用源代码运行

### 🐍 如果是使用源代码运行，请选择你的Python环境版本

Python 3.9

### ⚠️ 确认是否已经重试多次

- [X] 我已经尝试过多次，仍然出现问题

### 🕹 复现步骤

https://www.douyin.com/follow/live/409153278978
https://www.douyin.com/root/live/678929395416?is_paidlive=0&r_id=f_678929395416&r_player=1&watch_paidlive_status=regular

### 😯 问题描述

我填入的的直播间地址，正在直播中，但是却显示没有正在录制的直播

### 📜 错误信息
第一次获取数据失败：https://www.douyin.com/root/live/678929395416?is_paidlive=0&r_id=f_678929395416&r_player=1&watch_paidlive_status=regular 准备切换解析方法'NoneType' object has no attribute 'group'
错误信息: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1123)> 发生错误的行数: 196
序号2 网址内容获取失败,进行重试中...获取失败的地址是:('原画', 'https://www.douyin.com/root/live/678929395416?is_paidlive=0&r_id=f_678929395416&r_player=1&watch_paidlive_status=regular', '')

**Comment by ihmily** [comment]
![image](https://github.com/user-attachments/assets/2edea8aa-a4a0-46f4-8be5-2d2e5a6c8542)

### 没问题呀
![image](https://github.com/user-attachments/assets/f5dbbe1b-2bc0-4674-ae74-d810e97d04db)

><urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1123)>

出现这个是你的网络的问题，有可能是你开的代理软件影响的

**Comment by Bigfengshan** [comment]
中间应该是打开了VPN，现在VPN 已经关掉了，还是咩有录制，需要我如何操作才能恢复呢
