### ISSUE TITLE
用抖音号进行监控录制

### ISSUE THREAD

**Issue by Bigfengshan** [ihmily/DouyinLiveRecorder#687]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues，没有发现相似issue

### 📜 功能描述

现在只能写直播间地址进行录制，我只能等开播后才找到直播间地址，可以不可以直接用抖音号就可以监控

### 💡 动机

直播需要提前监控

**Comment by ihmily** [comment]
![image](https://github.com/user-attachments/assets/1577eced-3031-4c9e-8d1f-638579b01ec6)

**Comment by ihmily** [comment]
3.0.8版本可以使用上面的三种地址，下个版本3.0.9支持 作者主页地址

使用抖音号录制 方法参考 https://github.com/ihmily/DouyinLiveRecorder/issues/231#issuecomment-2095262691
