### ISSUE TITLE
3.0.8版 TS录制无法自动转换成MP4格式

### ISSUE THREAD

**Issue by renanzaii** [ihmily/DouyinLiveRecorder#688]
### ⚠️ 确认是否已存在类似问题

- [X] 我已经搜索过issues，没有找到类似问题

### 🔧 运行方式

直接运行的exe文件

### 🐍 如果是使用源代码运行，请选择你的Python环境版本

Python 3.12

### ⚠️ 确认是否已经重试多次

- [X] 我已经尝试过多次，仍然出现问题

### 🕹 复现步骤

TS转MP4

### 😯 问题描述

最新版本的录制无法自动从TS格式转换为MP4， 选项已输入：是

**Comment by ihmily** [comment]
如果是开启了分段录制，那么录制完成后才会将全部分段视频进行转换为mp4

**Comment by renanzaii** [comment]
好的 我再看看 实在不行的话我用3.0.7也行 感谢回答

**Comment by Nzybwzy** [comment]
貌似没能自动转mp4
