### ISSUE TITLE
打扰，烦请能添加一个，在命名文件时，添加B站直播[题目]信息吗

### ISSUE THREAD

**Issue by dayao0101** [ihmily/DouyinLiveRecorder#691]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues，没有发现相似issue

### 📜 功能描述

打扰，烦请能添加一个，在命名文件时，添加B站直播[题目]信息吗

### 🌐 举例(可选)

无

### 💡 动机

无

### 📚 附加信息

无

**Comment by ihmily** [comment]
@dayao0101 最新版3.0.9已支持该功能，需要自己在配置文件中设置开启
