### ISSUE TITLE
pandatv又录制不了了

### ISSUE THREAD

**Issue by jkfeng6565** [ihmily/DouyinLiveRecorder#693]
### ⚠️ 确认是否已存在类似问题

- [X] 我已经搜索过issues，没有找到类似问题

### 🔧 运行方式

直接运行的exe文件

### 🐍 如果是使用源代码运行，请选择你的Python环境版本

None

### ⚠️ 确认是否已经重试多次

- [X] 我已经尝试过多次，仍然出现问题

### 🕹 复现步骤

1.18+直播间
2.TS格式
3.出现错误代码

### 😯 问题描述

![1728909980494](https://github.com/user-attachments/assets/28cf04db-acd8-46be-b4a0-5f4a124fa321)

### 📜 错误信息

![Uploading 1728909980494.png…]()

**Comment by SAOJSM** [comment]
这是IP被记录了，目前主流的VPS商都没办法录制(IP段都被封锁)

**Comment by jkfeng6565** [comment]
> 这是IP被记录了，目前主流的VPS商都没办法录制(IP段都被封锁)

如果用猫抓插件直接录制的话 反而又可以录制 不知道为什么

**Comment by ihmily** [comment]
网络无法正常访问，切换网络解决
