### ISSUE TITLE
Afreecatv 域名變更至 sooplive.co.kr

### ISSUE THREAD

**Issue by leoguan888** [ihmily/DouyinLiveRecorder#696]
### ⚠️ 确认是否已存在类似问题

- [X] 我已经搜索过issues，没有找到类似问题

### 🔧 运行方式

直接运行的exe文件

### 🐍 如果是使用源代码运行，请选择你的Python环境版本

None

### ⚠️ 确认是否已经重试多次

- [X] 我已经尝试过多次，仍然出现问题

### 🕹 复现步骤

使用sooplive.co.kr網址

### 😯 问题描述

Afreecatv改名成soop，錄製上沒有遇到問題，依然可以用af網址錄製，怕之後改變希望能兼容soop網址。

**Comment by SAOJSM** [comment]
目前用play.afreecatv.com會強制跳轉play.sooplive.co.kr，請求作者更新

**Comment by ihmily** [comment]
嗯，下个版本3.0.9兼容两种地址 :) @SAOJSM @leoguan888
