### ISSUE TITLE
录制Twitcasting的过程中提示httpproxy不在白名单内

### ISSUE THREAD

**Issue by Etherrrr** [ihmily/DouyinLiveRecorder#700]
![image](https://github.com/user-attachments/assets/10cfb9bb-beb4-49a4-9a70-acd2314e500d)
想咨询一下有什么解决办法？

**Comment by ihmily** [comment]
@Etherrrr 录制开始出现的，还是已经录制了一段时间出现的这个错误？

**Comment by Etherrrr** [comment]
刚开始录播就出现了，此后哪怕直播仍在继续，也不会检测和录制

**Comment by ihmily** [comment]
**测试暂未出现你这个问题**

![image](https://github.com/user-attachments/assets/39acb9b8-df78-4d79-962a-3ca8b6b3065b)

![image](https://github.com/user-attachments/assets/6fd578cd-30f8-4ef6-b57b-7bf496c69b68)

**Comment by Etherrrr** [comment]
在main.py#831处增加了httpproxy到白名单中，可以正常录制了
推测是因为使用规则而非全局网络代理？

**Comment by ihmily** [comment]
> 在main.py#831处增加了httpproxy到白名单中，可以正常录制了 推测是因为使用规则而非全局网络代理？

是的，你的错误是因为协议不在ffmpeg配置中。但我测试规则或者全局代理 都是一样正常录制的。

估计你的网络环境也有问题，还有twitcasting在国内网络可以直连呀，不需要开代理访问吧，而且录制程序默认是不会使用代理去访问的，除非你设置额外用代理访问。

**Comment by Etherrrr** [comment]
是这样的，我在本地配置http代理，地址是`http://127.0.0.1:20171/`，在`config.ini`中配置了
```
是否使用代理ip（是/否） = 是
代理地址 = http://127.0.0.1:20171
...
使用代理录制的平台（逗号分隔） = tiktok, afreecatv, pandalive, winktv, flextv, popkontv, twitch, liveme, showroom, chzzk
额外使用代理录制的平台（逗号分隔） = 
```
同时我在`URL_cofig.ini`中同时监测了一个tiktok房间和一个twitcasting房间。

此时我监测tiktok开播的状态是正常的，twitcasting会报这个协议不在白名单的错误，代理后台显示访问twitcasting.tv和tiktok.com都经过了代理

而将使用代理设置为否后，tiktok便无法访问了，而twitcasting的监测和录制直播都是正常的，代理后台则没有访问记录

能否可以理解为`是否使用代理ip（是/否） = *`这一选项开启时，所有监测和录制都走代理？

**Comment by ihmily** [comment]
@Etherrrr 是的，你这种情况只要开启了代理，所有请求都会经过代理过滤一遍，如果在请求地址在你的代理规则内则会使用代理ip请求出去，但这也是正常的，因为你的代理地址是**本机地址**，这属于是操作系统层面已经配置了代理，应用程序是无法决定是否使用代理的。

如果你的代理地址是别的主机IP地址而不是127.*/192.*，那么即使开启了开关和配置了代理地址，如果不额外设置`使用代理录制的平台（逗号分隔） =*` 使用代理，也就不会使用代理请求。

**出现httpproxy这个可能跟你的代理程序设置相关，我已经在代理配置中加入该参数**

**Comment by Etherrrr** [comment]
明白了 感谢解答
