### ISSUE TITLE
录制TK出现错误        错误信息: type: TypeError, unsupported operand type(s) for 

### ISSUE THREAD

**Issue by luoyuLianga** [ihmily/DouyinLiveRecorder#701]
### ⚠️ 确认是否已存在类似问题

- [X] 我已经搜索过issues，没有找到类似问题

### 🔧 运行方式

使用源代码运行

### 🐍 如果是使用源代码运行，请选择你的Python环境版本

Python 3.9

### ⚠️ 确认是否已经重试多次

- [X] 我已经尝试过多次，仍然出现问题

### 🕹 复现步骤

1. https://www.tiktok.com/@eyzxie/live
2. ts

### 😯 问题描述

![image](https://github.com/user-attachments/assets/0a7cfdd5-0417-46f1-979b-8b2e15cb9028)

**Comment by luoyuLianga** [comment]
更换直播间地址也还是有问题：
新地址: https://www.tiktok.com/@yanzkag_/live

**Comment by ihmily** [comment]
>更换直播间地址也还是有问题：
> https://www.tiktok.com/@yanzkag_/live

除了TikTok其他直播能正常录制吗？

**Comment by luoyuLianga** [comment]
> > 更换直播间地址也还是有问题：
> > https://www.tiktok.com/@yanzkag_/live
> 
> 除了TikTok其他直播能正常录制吗？

测试了抖音的，正常的

**Comment by ihmily** [comment]
大概是type hint代码的问题导致报错，python 3.10以下没有 `list[dict[str, int | Any]]` 使用 `|` 这样的写法

升级python版本 或者 将DouyinLiveRecorder/douyinliverecorder/stream.py的大概65行
```
def get_video_quality_url(stream, q_key) -> list[dict[str, int | Any]]:
```
改为
```
def get_video_quality_url(stream, q_key) -> list[dict[str, Union[int, Any]]]
```

**Comment by luoyuLianga** [comment]
> 大概是type hint代码的问题导致报错，python 3.10以下没有 `list[dict[str, int | Any]]` 使用 `|` 这样的写法
> 
> 升级python版本 或者 将DouyinLiveRecorder/douyinliverecorder/stream.py的大概65行
> 
> ```
> def get_video_quality_url(stream, q_key) -> list[dict[str, int | Any]]:
> ```
> 
> 改为
> 
> ```
> def get_video_quality_url(stream, q_key) -> list[dict[str, Union[int, Any]]]
> ```


def get_video_quality_url(stream, q_key) -> list[dict[str, int | Any]]:

改为

def get_video_quality_url(stream, q_key) -> list[dict[str, Union[int, Any]]]:

可以解决上述报错，但是录制中出现了一个新问题：
![image](https://github.com/user-attachments/assets/879260f9-fbf1-48eb-8684-74fb9e56f492)

**Comment by ihmily** [comment]
> 我也遇到了这种情况 Error opening input files:Connection reset by peer

访问外网的网络连接不稳定导致的 录制中断或者录制出错
