### ISSUE TITLE
抖音作者主页地址无法监控录制

### ISSUE THREAD

**Issue by liumuyv** [ihmily/DouyinLiveRecorder#705]
### ⚠️ 确认是否已存在类似问题

- [X] 我已经搜索过issues，没有找到类似问题

### 🔧 运行方式

直接运行的exe文件

### 🐍 如果是使用源代码运行，请选择你的Python环境版本

None

### ⚠️ 确认是否已经重试多次

- [X] 我已经尝试过多次，仍然出现问题

### 🕹 复现步骤

1.直播间地址https://v.douyin.com/iSFN2NYS/

### 😯 问题描述

主页地址添加后无法开始录制，替换成抖音号地址后正常

**Comment by ihmily** [comment]
3.0.9版本才开始支持使用  `抖音作者主页地址` 录制
