### ISSUE TITLE
请问m3u8和flv的链接有什么区别呢？

### ISSUE THREAD

**Issue by JoeanAmier** [ihmily/DouyinLiveRecorder#71]
想请教一下这两个链接的区别，以及使用m3u8而不是flv链接去录制的原因。

**Comment by ihmily** [comment]
因为有些平台使用flv录制会出问题，并且貌似m3u8实时性强一点，至于两者区别网上挺多资料的，这里就不赘述了。

**Comment by JoeanAmier** [comment]
感谢回复，我的项目参考了 DouyinLiveRecorder 调用 ffmpeg 的部分代码，已注明代码参考来源。
