### ISSUE TITLE
嗨秀出现错误

### ISSUE THREAD

**Issue by mo00-stack** [ihmily/DouyinLiveRecorder#710]
### ⚠️ 确认是否已存在类似问题

- [X] 我已经搜索过issues，没有找到类似问题

### 🔧 运行方式

使用源代码运行

### 🐍 如果是使用源代码运行，请选择你的Python环境版本

Python 3.11

### ⚠️ 确认是否已经重试多次

- [X] 我已经尝试过多次，仍然出现问题

### 🕹 复现步骤

![image](https://github.com/user-attachments/assets/4a52a7f2-da60-46cd-b6dc-77ab8460e8bb)

### 😯 问题描述

只要嗨秀直播链接放进URL.ini里面去就是直接显示报错，我也不知道怎么回事

**Comment by ihmily** [comment]
缺少nodejs环境，下载安装nodejs并配置到环境变量path中
地址：https://nodejs.org/dist/latest/node-v22.9.0-x64.msi
