### ISSUE TITLE
Twitch Tv 录制画质问题

### ISSUE THREAD

**Issue by cchen9494** [ihmily/DouyinLiveRecorder#714]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues，没有发现相似issue

### 📜 功能描述

Twitch Tv 录制不了1080p60帧 我都是分段录制的 第一段录制的画质居然是1080p  
![_cgi-bin_mmwebwx-bin_webwxgetmsgimg__ MsgID=2001202504052533041 skey=@crypt_d7110dba_05de069a84966be1acf66e6bd812402d mmweb_appid=wx_webfilehelper](https://github.com/user-attachments/assets/7eade79a-38eb-4816-9c68-1d8d22ba26ff)
![_cgi-bin_mmwebwx-bin_webwxgetmsgimg__ MsgID=8513615295951110311 skey=@crypt_d7110dba_05de069a84966be1acf66e6bd812402d mmweb_appid=wx_webfilehelper](https://github.com/user-attachments/assets/d09bfc28-65d0-41e6-9fd9-ff73976da765)
1000帧率 我用剪辑软件看的是25帧率 第二段录制的都是720P 60帧率 怎么会这样 是我哪里出了问题吗？其他平台一切正常！

### 🌐 举例(可选)

https://www.twitch.tv/woohankyung

### 📚 附加信息

我试了下登不登录了账号，填写了cookies 问题依旧！这个是bug 还是我要设置些啥 这个录制脚本
![_cgi-bin_mmwebwx-bin_webwxgetmsgimg__ MsgID=2001202504052533041 skey=@crypt_d7110dba_05de069a84966be1acf66e6bd812402d mmweb_appid=wx_webfilehelper](https://github.com/user-attachments/assets/75220b34-02e6-48d0-a2ff-23e67a5c2d5d)
![_cgi-bin_mmwebwx-bin_webwxgetmsgimg__ MsgID=8513615295951110311 skey=@crypt_d7110dba_05de069a84966be1acf66e6bd812402d mmweb_appid=wx_webfilehelper](https://github.com/user-attachments/assets/1bc80cf5-fb5f-44f1-9733-e5cf5166add6)
每个版本都不行

**Comment by ihmily** [comment]
@cchen9494 看一下最新3.0.9版本会不会有这个问题https://github.com/ihmily/DouyinLiveRecorder/releases/tag/v3.0.9

**Comment by cchen9494** [comment]
可以了现在可以都是1080p的了，非常感谢你。

**Comment by cchen9494** [comment]
对了，我还有个问题，就是twitchtv 录制的老是有广告是非常多的那种一晚10几个广告至少，是不是账号如果是会员的话，填写cookies  后，   录制的就不会有广告了。有劳你再解答一下。感谢

**Comment by ihmily** [comment]
> 对了，我还有个问题，就是twitchtv 录制的老是有广告是非常多的那种一晚10几个广告至少，是不是账号如果是会员的话，填写cookies 后， 录制的就不会有广告了。有劳你再解答一下。感谢

没有实测过，但是如果会员账号在网页上看是没有广告的话，那填写Cookie后录制的应该也是没广告的。

**Comment by Nzybwzy** [comment]
@cchen9494
测试了下  3.0.9版本 老鼠开了会员 的 cookie 也会有那个界面

**Comment by cchen9494** [comment]
如果是这样那这个问题那就真无解了  还是得感谢作者和热心网友的答复。

**Comment by JinZhaoLin** [comment]
我开了turbo会员还是有广告
