### ISSUE TITLE
[Feature] 增加直播状态通知渠道。

### ISSUE THREAD

**Issue by crpwxi85731** [ihmily/DouyinLiveRecorder#717]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues，没有发现相似issue

### 📜 功能描述

ntfy.sh
https://ntfy.sh

go-cqhttp
https://github.com/Mrs4s/go-cqhttp

**Comment by ihmily** [comment]
3.0.9已支持
