### ISSUE TITLE
录制的视频文件命名可以是直播间标题吗？

### ISSUE THREAD

**Issue by abgrund18x** [ihmily/DouyinLiveRecorder#719]
### ⚠️ 搜索是否存在类似问题

- [X] 我已经搜索过issues，没有找到相似的问题

### 🔧 运行方式

直接运行的exe文件

### 🐍 如果是使用源代码运行，请选择你的Python环境版本

None

### 💻 请选择你的系统环境

Windows 10

### 🤔 问题详情

录制的视频文件命名可以是直播间标题吗？

**Comment by ihmily** [comment]
3.0.9版本会支持
