### ISSUE TITLE
能不能在配置文件里面配置单个直播间是否录制的状态

### ISSUE THREAD

**Issue by juventusforever** [ihmily/DouyinLiveRecorder#72]
感谢大佬制作的小工具，很好用，
有个需求：比如某一天不想录某个直播间的视频，那只能把它删掉，以后想录的时候再加进去？好像不太方便

**Comment by ihmily** [comment]
我在使用说明中有提到，在配置文件中的直播间地址前面加一个＃，就不会录制该直播间了，无需删除链接。想录制的时候把＃去掉即可。

**Comment by juventusforever** [comment]
好的好的。。我漏看了不好意思
