### ISSUE TITLE
🐛[BUG] 小红书录制不了了

### ISSUE THREAD

**Issue by JusticeGu** [ihmily/DouyinLiveRecorder#720]
### ⚠️ 确认是否已存在类似问题

- [X] 我已经搜索过issues，没有找到类似问题

### 🔧 运行方式

使用docker运行

### 🐍 如果是使用源代码运行，请选择你的Python环境版本

None

### 💻 请选择你的系统环境

Ubuntu

### ⚠️ 确认是否已经重试多次

- [X] 我已经尝试过多次，仍然出现问题

### 🕹 复现步骤

1.分享小红书链接
2.加入ini文件

### 😯 问题描述

小红书好像换域名了换这个了live.xhscdn.com

### 📜 错误信息

URL Error: <urlopen error [Errno -3] Temporary failure in name resolution>
[32m2024-10-27 20:37:12.325[0m | [31m[1mERROR [0m | [36mdouyinliverecorder.utils[0m:[36mwrapper[0m:[36m22[0m - [31m[1m错误信息: type: JSONDecodeError, Expecting value: line 1 column 1 (char 0) in function get_xhs_stream_url at line: 355[0m
[32m2024-10-27 20:37:12.326[0m | [31m[1mERROR [0m | [36m__main__[0m:[36mstart_record[0m:[36m1128[0m - [31m[1m错误信息: 'list' object has no attribute 'get' 发生错误的行数: 714[0m

**Comment by ihmily** [comment]
>URL Error: <urlopen error [Errno -3] Temporary failure in name resolution>

你这个是机器网络的问题

### 刚测试是能正常录制的 
![image](https://github.com/user-attachments/assets/03623640-d59f-4a38-8b18-4e25924dd998)

**Comment by ihmily** [comment]
@JusticeGu 

3.0.8版本确实是小红书某些直播间无法录制，这个问题在之前版本也一直存在，至于新的`live.xhscdn.com` 的直播源已经在 两周前 https://github.com/ihmily/DouyinLiveRecorder/commit/d3143108c1dc7c0e90493b3d68b99d40b68f157a 被修复


另外，docker镜像仓库目前发布版本不是最新的，如果要docker运行，你可以拉取主分支代码，自行构建一下镜像。
