### ISSUE TITLE
录制直播视频获取cookie的问题

### ISSUE THREAD

**Issue by luoke123-prog** [ihmily/DouyinLiveRecorder#721]
### ⚠️ 搜索是否存在类似问题

- [X] 我已经搜索过issues，没有找到相似的问题

### 🔧 运行方式

直接运行的exe文件

### 🐍 如果是使用源代码运行，请选择你的Python环境版本

Python 3.11

### 💻 请选择你的系统环境

Windows 10

### 🤔 问题详情

我想问一下这个程序录制直播视频是否获取cookie啊？是获取本人的cookie？还是获取录制直播人的cookie啊？如果录制多个直播人的视频，多个cookie怎么换行放置啊？求解？

**Comment by ihmily** [comment]
除了快手以及海外需要登录账号才能观看的那几个平台需要你自己配置cookie，其他的平台你可以不用自己配置cookie，使用默认cookie也能录制。

>是获取本人的cookie？还是获取录制直播人的cookie啊？

当然是你自己账号的cookie，需要cookie的原因是需要维持你的账号登录状态，因为某些直播间必须登录后才能观看，这样的情况就需要配置你自己账号登录后的cookie了，因为这样录制程序才能在已登录你账号的状态去获取到直播源。

**Comment by luoke123-prog** [comment]
还有一个疑问就是小红书和抖音的cookie还需要配置吗？还是说默认就可以了啊？

**Comment by ihmily** [comment]
> 还有一个疑问就是小红书和抖音的cookie还需要配置吗？还是说默认就可以了啊？

小红书和抖音的cookie 默认就可以
