### ISSUE TITLE
v3.0.8版本出现小红书直播间无法录制视频的问题

### ISSUE THREAD

**Issue by luoke123-prog** [ihmily/DouyinLiveRecorder#724]
### ⚠️ 确认是否已存在类似问题

- [X] 我已经搜索过issues，没有找到类似问题

### 🔧 运行方式

直接运行的exe文件

### 🐍 如果是使用源代码运行，请选择你的Python环境版本

Python 3.11

### 💻 请选择你的系统环境

Windows 10

### ⚠️ 确认是否已经重试多次

- [X] 我已经尝试过多次，仍然出现问题

### 🕹 复现步骤

1、录制的小红书直播间地址是：https://www.xiaohongshu.com/hina/livestream/569455265344727101/
2、使用的录制格式是：TS
3、所有的小红书直播间地址都尝试过，反正就是不行啊，报错，录制不了，录制失败，怎么解决？求解啊！

### 😯 问题描述

[in#0 @ 000002549f69cc80] Error opening input: Server returned 404 Not Found
Error opening input file http://live-play.xhscdn.com/live/569455265344727101.flv.
Error opening input files: Server returned 404 Not Found
![屏幕截图 2024-10-28 233745](https://github.com/user-attachments/assets/ac2a3dc1-bb99-440d-9878-a3f96aa83275)

### 📜 错误信息

![屏幕截图 2024-10-28 233745](https://github.com/user-attachments/assets/0c822a16-87ba-4dbb-b71d-9d0468906aef)
[in#0 @ 000002549f69cc80] Error opening input: Server returned 404 Not Found
Error opening input file http://live-play.xhscdn.com/live/569455265344727101.flv.
Error opening input files: Server returned 404 Not Found

**Comment by Fairykingslan** [comment]
DouYin  problem
我这边抖音录制也是出现了 同样的错误  请问有没有方法解决？
![PixPin_2024-10-28_23-26-30](https://github.com/user-attachments/assets/8ce9594f-c31f-4885-ba52-cd2d04840314)
报错后本地视频分段严重（个人是设置1小时30分钟为一个分段）
![image](https://github.com/user-attachments/assets/44158217-50b7-4542-93d7-2000e0c0d526)

**Comment by ihmily** [comment]
>所有的小红书直播间地址都尝试过，反正就是不行啊，报错，录制不了，录制失败，怎么解决？求解啊！

小红书下个版本3.0.9已修复 https://github.com/ihmily/DouyinLiveRecorder/issues/720#issue-2616568111

**Comment by luoke123-prog** [comment]
3.0.9版本在哪里，为啥我看到最新版的是3.0.8版本啊？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年10月29日(周二) 上午10:18
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ihmily/DouyinLiveRecorder] v3.0.8版本出现小红书直播间无法录制视频的问题 (Issue #724)




  
所有的小红书直播间地址都尝试过，反正就是不行啊，报错，录制不了，录制失败，怎么解决？求解啊！
  
小红书下个版本3.0.9已修复 #720 (comment)

**Comment by luoke123-prog** [comment]
> > 所有的小红书直播间地址都尝试过，反正就是不行啊，报错，录制不了，录制失败，怎么解决？求解啊！
> 
> 小红书下个版本3.0.9已修复 [#720（评论）](https://github.com/ihmily/DouyinLiveRecorder/issues/720#issue-2616568111)

3.0.9版本发布了吗？为啥我没有看到？这在哪里下载啊？

**Comment by ihmily** [comment]
@luoke123-prog  已发布https://github.com/ihmily/DouyinLiveRecorder/releases/tag/v3.0.9
