### ISSUE TITLE
抖音 快手都不能录了

### ISSUE THREAD

**Issue by dai1400** [ihmily/DouyinLiveRecorder#73]
![360截图20231121195611714](https://github.com/ihmily/DouyinLiveRecorder/assets/124576931/74db404b-0f56-4a14-b574-140a0886debd)
![360截图20231121195511138](https://github.com/ihmily/DouyinLiveRecorder/assets/124576931/d4fac664-172a-4c45-952a-213981f235ae)

**Comment by ihmily** [comment]
刚测试，目前软件是能正常录制抖音和快手的。

1、看你的报错应该是你快手请求太频繁被官方暂时封ip了，换个网络或者根据提示信息，进入快手网页端，正常打开一个直播间观看几秒钟，就能解除限制。

2、看你的截图 抖音录制应该是正常的，显示切换解析方法后都正常解析了，如图中序号12 和 序号15 ，显示等待直播说明只是主播没开播，抖音能正常录制。

另 同时监测如此多个直播间 最好监控频率设置低一点，在config.ini文件中将监控时间间隔调大一些，降低被官方封禁ip的风险，并且我觉得也不差那没录到的一分钟吧。

**Comment by dai1400** [comment]
谢谢 提示
&nbsp;


我意已决！退下！！！
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年11月21日(星期二) 晚上11:35
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ihmily/DouyinLiveRecorder] 抖音 快手都不能录了 (Issue #73)





 
刚测试，目前软件是能正常录制抖音和快手的。
 
1、看你的报错应该是你快手请求太频繁被官方暂时封ip了，换个网络或者根据提示信息，进入快手网页端，正常打开一个直播间观看几秒钟，就能解除限制。
 
2、看你的截图 抖音录制应该是正常的，显示切换解析方法后都正常解析了，如图中序号12 和 序号15 ，显示等待直播说明只是主播没开播，抖音能正常录制。
 
另 同时监测如此多个直播间 最好监控频率设置低一点，在config.ini文件中将监控时间间隔调大一些，降低被官方封禁ip的风险，并且我觉得也不差那没录到的一分钟吧。
