### ISSUE TITLE
🐛[BUG] 显示已被注释线程将会退出

### ISSUE THREAD

**Issue by whyyyyTT** [ihmily/DouyinLiveRecorder#730]
### ⚠️ 确认是否已存在类似问题

- [X] 我已经搜索过issues，没有找到类似问题

### 🔧 运行方式

直接运行的exe文件

### 🐍 如果是使用源代码运行，请选择你的Python环境版本

None

### 💻 请选择你的系统环境

Windows 11

### ⚠️ 确认是否已经重试多次

- [X] 我已经尝试过多次，仍然出现问题

### 🕹 复现步骤

https://live.douyin.com/wy1994050
mp4

### 😯 问题描述

![0759D04A1264DACB1B4696196910E68D](https://github.com/user-attachments/assets/7ffc02ce-229b-432f-b8ff-e3d4c20fe44e)
并且URL_config中所有线程前都被加上了###########

**Comment by ihmily** [comment]
@whyyyyTT 只输入单个直播间地址试一下，你的URL_config.ini文件可以发出来一下吗？
