### ISSUE TITLE
🐛[BUG] 花椒 don't recording

### ISSUE THREAD

**Issue by luki4ven** [ihmily/DouyinLiveRecorder#733]
### ⚠️ Confirm if similar issues exist

- [X] I have searched the issues and found no similar problems

### 🔧 How did you run the program?

Directly running the exe file

### 🐍 If running with source code, please select your Python environment version

None

### 💻 Please select your system environment

Windows 11

### ⚠️ Confirm if you have retried multiple times

- [X] I have tried multiple times and still encounter the problem

### 🕹 Reproduction steps

2024-10-31 02:05:12.287 | ERROR    | douyinliverecorder.utils:wrapper:25 - 错误信息: type: KeyError, 'data' in function get_huajiao_stream_url at line: 2244
2024-10-31 02:05:12.287 | ERROR    | __main__:start_record:1225 - 错误信息: 'list' object has no attribute 'get' 发生错误的行数: 778

### 😯 Problem description

使用了主放送的主页地址也会发生这样的错误

**Comment by ihmily** [comment]
花椒直播支持使用 `直播间页面地址录制` 和 `作者主页地址录制` 

直播间页面地址如：https://www.huajiao.com/l/345164050
但是这种每次直播结束 直播间地址会变化，所以只能一次性录制。

如果要支持持久化录制，可以使用 `主播主页地址`, 但是这种 需要配置Cookie才能获取到直播流数据。
