### ISSUE TITLE
🚀[Feature] 能否支持一下根据硬盘容量自动暂停录制，达到指定大小时再启动录制

### ISSUE THREAD

**Issue by xueli12** [ihmily/DouyinLiveRecorder#736]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues，没有发现相似issue

### 📜 功能描述

      作者大大，希望能够每隔一段时间检测下载路径对应的那个磁盘的容量，如果这个磁盘的容量低于指定大小就停止录制。如果高于指定容量就恢复录制。

### 💡 动机

        苦于容量的限制，需要录一部分视频上传一部分视频，但是有时候上传速度没有下载的速度快，导致很容易爆盘。

**Comment by ihmily** [comment]
最新版v4.0.1已支持 , 可在配置文件中 `录制空间剩余阈值(gb) = 1.0`设置录制停止指定大小。
