### ISSUE TITLE
🐛[BUG] 主动打断录制（CTRL+C）会导致视频不转MP4

### ISSUE THREAD

**Issue by olalala10** [ihmily/DouyinLiveRecorder#743]
### ⚠️ 确认是否已存在类似问题

- [X] 我已经搜索过issues，没有找到类似问题

### 🔧 运行方式

直接运行的exe文件

### 🐍 如果是使用源代码运行，请选择你的Python环境版本

None

### 💻 请选择你的系统环境

Windows 11

### ⚠️ 确认是否已经重试多次

- [X] 我已经尝试过多次，仍然出现问题

### 🕹 复现步骤

1.录制地址：https://live.douyin.com/265366259141；
2.格式为默认的TS+转MP4

### 😯 问题描述

使用CTRL+C手动停止录制时，视频会保留TS格式，不会转MP4格式；
自动录制结束则会自动转MP4。

**Comment by gyc0123** [comment]
开飞行模式是不是能行，直播全部中断就能自动转了，转完再关

**Comment by ihmily** [comment]
运行StopRecording.vbs 文件就可以正常停止录制并转码。
