### ISSUE TITLE
你好，再问个问题，下下来的视频的数据速率、帧速率、总比特率是由什么决定的？

### ISSUE THREAD

**Issue by juventusforever** [ihmily/DouyinLiveRecorder#75]
我同时用软件和手机录同一段视频明显手机的数据速率和帧速率更高，更清晰，软件下下来的视频有点不如手机录的清晰，录同样的时间手机录制的大小基本上是软件的两倍，请问是什么原因，能通过手动配置ffmpeg的参数来解决吗？如何配置？毕竟手机录制只能录一个还不能干别的，很不方便，求答疑解惑，不太在乎硬盘空间，能不能提升软件录入的清晰度呢？

**Comment by ihmily** [comment]
### 视频大小计算公式：
视频文件大小=时间(s)x码率(kbps)/8

总码率（总比特率）＝音频码率＋视频码率

**上面说的码率就是你说的数据速率**

一部码率2000kbps、80分钟的电影，那么它的文件大小大概就是

80x60x2000/8＝1,200,000KB

转换单位后视频大小也就是1172兆

1,200,000KB＝1,200,000/1024≈1172M

**回到你的问题**

1、首先要确定你是眼睛看觉得更清晰还是因为那些数值就觉得更清晰呢？因为`明显手机的数据速率和帧速率更高` 并不完全意味着图像更清晰，还有就是你进行对比的时候是否在同个设备上呢，是否是在同个设备上看的视频。

2、通过视频文件大小判断视频清晰度也是不准确的。用手机录制，在设置中一般都可以选择录制视频的清晰度配置，如720P、1080P、4K等，你设置越高，录制的视频文件就越大，当然对于你手机这些清晰度来说，肯定是4K>1080P>720P，但是相对于原始直播视频清晰度其实没有什么可比性。

举个例子，你观看直播时将清晰度设置为流畅，然后你再用手机超清的画质去录制，难道录制下来的视频就是超清的了吗？再如 我把非常模糊画质的视频导入到剪辑软件，然后以蓝光画质的比特率进行导出，虽然视频文件大小翻了好几倍，但是模糊的视频难道就变成蓝光画质的了吗，其实清晰度并无提升，当达到原始视频的比特率上限就对视频清晰度无提升了。

3.同样清晰度的视频，如何编码算法不够优秀、压缩参数的影响，也可能会导致文件大小增加，而不一定提高视频质量。一些压缩视频工具就是根据这个原理，通过优化编码算法，可以在几乎不影响清晰度的情况下来减小视频文件的大小。


最后，我在代码中设置的录制MP4视频的参数就是直接**复制原始视频流**，不进行重新编码，以保持原始视频的画质。所以不出意外的话应该是原始直播什么画质，录制下来就是什么画质。如果设置比原始视频更高的码率参数来录制，是不会提升清晰度的。

**Comment by juventusforever** [comment]
感谢作者认真回复，我再观察几天，谢谢哈
