### ISSUE TITLE
❓[Question] WINKTV 突然无法录制

### ISSUE THREAD

**Issue by ben5208** [ihmily/DouyinLiveRecorder#753]
### ⚠️ 搜索是否存在类似问题

- [X] 我已经搜索过issues，没有找到相似的问题

### 🔧 运行方式

直接运行的exe文件

### 🐍 如果是使用源代码运行，请选择你的Python环境版本

Python 3.10

### 💻 请选择你的系统环境

Windows 10

### 🤔 问题详情

原本在录的还能继续录製，但是新的无法添加，
重新启动文件后出现以下问题回报
请问是怎麽回事?
![螢幕擷取畫面 2024-11-03 212814](https://github.com/user-attachments/assets/7e267376-43c5-42b6-9cf2-e23aa682349d)

**Comment by ihmily** [comment]
连接代理网络的问题
