### ISSUE TITLE
🚀[Feature] 请求添加stripchat直播的录制功能

### ISSUE THREAD

**Issue by weakeng** [ihmily/DouyinLiveRecorder#755]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues，没有发现相似issue

### 📜 功能描述

请求添加stripchat直播的录制功能

### 🌐 举例(可选)

https://zh.stripchat.com/yaya_86

### 💡 动机

想录制

**Comment by ihmily** [comment]
成人直播不会考虑
