### ISSUE TITLE
❓[Question] v3.0.9版本 无法录制

### ISSUE THREAD

**Issue by renanzaii** [ihmily/DouyinLiveRecorder#758]
### ⚠️ 搜索是否存在类似问题

- [X] 我已经搜索过issues，没有找到相似的问题

### 🔧 运行方式

直接运行的exe文件

### 🐍 如果是使用源代码运行，请选择你的Python环境版本

None

### 💻 请选择你的系统环境

Windows 11

### 🤔 问题详情

所有设定和直播间地址填写完整， 程序也能成功启动但是直播间正在直播却没有办法录制。同样的设定同样的直播间在3.0.7版本却可以录制。

**Comment by renanzaii** [comment]
![Screenshot 2024-11-06 143903](https://github.com/user-attachments/assets/390aa4d9-5546-4eea-94bd-22f8a05d8f25)
![Screenshot 2024-11-06 143825](https://github.com/user-attachments/assets/ab0ee13c-edae-422b-bd2a-112b80b1fe68)
左边是3.0.7 右边是3.0.9 (两图皆是)

**Comment by ihmily** [comment]
直播间地址发一下

**Comment by renanzaii** [comment]
https://www.twitch.tv/eul___e

**Comment by ihmily** [comment]
![image](https://github.com/user-attachments/assets/adcebb37-d385-4b52-ad1c-db7e4f6e1bc1)

![image](https://github.com/user-attachments/assets/89cda8f0-373e-4ab0-b09f-f3eace032c60)

@renanzaii  我这边是正常录制的，你只留这个直播间地址 录制试一下

**Comment by renanzaii** [comment]
还是显示没有录制，log里能找到原因吗？
[DouyinLiveRecorder.log](https://github.com/user-attachments/files/17647214/DouyinLiveRecorder.log)

**Comment by ihmily** [comment]
这个日志都是下午两点的，当时貌似是直播源获取失败了。URL_config.ini只放一个地址 ，然后重启试试，没有录制界面上也会显示报错的。确保网络能正常访问外网。

**Comment by renanzaii** [comment]
好的 感谢大哥
