### ISSUE TITLE
🐛[BUG] v3.0.9 版本win10 用作者主页链接录制小红书会自动中断

### ISSUE THREAD

**Issue by lyl980918** [ihmily/DouyinLiveRecorder#762]
### ⚠️ 确认是否已存在类似问题

- [X] 我已经搜索过issues，没有找到类似问题

### 🔧 运行方式

直接运行的exe文件

### 🐍 如果是使用源代码运行，请选择你的Python环境版本

None

### 💻 请选择你的系统环境

Windows 10

### ⚠️ 确认是否已经重试多次

- [X] 我已经尝试过多次，仍然出现问题

### 🕹 复现步骤

请问最新版里说的小红书录制直播可以采用作者主页的格式是什么样的？我用手机 app 分享的主页链接如下
https://www.xiaohongshu.com/user/profile/5a84381a4eacab36b88a8f9d

### 😯 问题描述

用 win10 系统打开 exe 录制，录制 1-2 分钟会自动结束录制，直播间链接分享的话好像每次都会变，没有固定链接，而且也会录制自动断开，并且无法再次监测到正在直播，需要再次打开软件才会识别到正在直播，🍠平台该如何填写监控链接？

**Comment by ihmily** [comment]
@lyl980918 我使用你贴出来的地址 是能正常录制的

![image](https://github.com/user-attachments/assets/98f7b29f-3913-40bc-8c29-dec46725d4eb)

![image](https://github.com/user-attachments/assets/398a58d9-1391-4ac6-ad4a-06256d0180f2)


主页地址获取步骤：
手机app端点击作者主页，右上角分享-复制链接

就是如：
https://www.xiaohongshu.com/user/profile/6330049c000000002303c7ed?xhsshare=CopyLink&appuid=5f3f478a00000000010005b3&apptime=1730973218&share_id=891077942d364335897889f18eccd391

**Comment by lyl980918** [comment]
谢谢，应该是网络波动问题，2.4g 网络换了个网卡切换成 5g 以后能录制超过 10 分钟了
