### ISSUE TITLE
🚀[Feature] 请输入标题大佬，可以支持shopee吗

### ISSUE THREAD

**Issue by knightdax** [ihmily/DouyinLiveRecorder#763]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues，没有发现相似issue

### 📜 功能描述

希望支持shopee

### 🌐 举例(可选)

https://ph.shp.ee/BicW7PB

### 💡 动机

希望支持shopee

**Comment by ihmily** [comment]
已在下个版本支持

**Comment by knightdax** [comment]
> 已在下个版本支持

太感谢！
