### ISSUE TITLE
❓[Question] 哔哩哔哩报错

### ISSUE THREAD

**Issue by ningsibuqu** [ihmily/DouyinLiveRecorder#764]
### ⚠️ 搜索是否存在类似问题

- [X] 我已经搜索过issues，没有找到相似的问题

### 🔧 运行方式

直接运行的exe文件

### 🐍 如果是使用源代码运行，请选择你的Python环境版本

None

### 💻 请选择你的系统环境

Windows 10

### 🤔 问题详情

2024-11-08 10:53:16.760 | ERROR    | douyinliverecorder.utils:wrapper:25 - 错误信息: type: KeyError, 'data' in function get_bilibili_room_info_h5 at line: 658

一直有报错这个  但好像录制是正常的

**Comment by End-Satan** [comment]
我使用录制bilibili一直都用不了，源码运行都用不了。一直都这样

**Comment by ihmily** [comment]
@ningsibuqu @End-Satan 

**随机录制了几个B站直播都是正常的，你们如果开了代理，把代理关掉再录制试一下。**

![image](https://github.com/user-attachments/assets/2ceec480-7e96-4c5e-bd8e-aa3a3fde6834)

![image](https://github.com/user-attachments/assets/00152d64-f90b-409d-afee-78ebf4d433a6)

![image](https://github.com/user-attachments/assets/1db807ca-846c-4ff4-9e76-ae2f98c343d6)


**如果遇到获取到直播源后，录制出错的情况，可以把直播间地址贴出来**

**Comment by ningsibuqu** [comment]
> @ningsibuqu @End-Satan
> 
> **随机录制了几个B站直播都是正常的，你们如果开了代理，把代理关掉再录制试一下。**
> 
> ![image](https://private-user-images.githubusercontent.com/114978440/384441975-2ceec480-7e96-4c5e-bd8e-aa3a3fde6834.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwODY5ODYsIm5iZiI6MTczMTA4NjY4NiwicGF0aCI6Ii8xMTQ5Nzg0NDAvMzg0NDQxOTc1LTJjZWVjNDgwLTdlOTYtNGM1ZS1iZDhlLWFhM2EzZmRlNjgzNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwOFQxNzI0NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZmYxZmEzYjk3MjhmMWUyOWYyYjk0NTU1NzYwYjIyZDhhOWQxZTg3MGI4NDA5MTQwM2Y1ZWVhMDFkYjY0ZWUwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.3hahljS8Cmoz6PHjUOA_tgyHYg5eLUt3czY0M0AE6FE)
> 
> ![image](https://private-user-images.githubusercontent.com/114978440/384446385-00152d64-f90b-409d-afee-78ebf4d433a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwODY5ODYsIm5iZiI6MTczMTA4NjY4NiwicGF0aCI6Ii8xMTQ5Nzg0NDAvMzg0NDQ2Mzg1LTAwMTUyZDY0LWY5MGItNDA5ZC1hZmVlLTc4ZWJmNGQ0MzNhNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwOFQxNzI0NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMjZmODE1NzRkN2Y4YzIwMDhhMGNhYzgxMGNjYjcxYWZiMDU1ZTVhZGNkNTNjZDEzODY0MTYxZTdkMDhkYzI5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.p7EoNtwSPA1aVzXdEvQ-XPnMzL7S5JiIj-prGn9C3nk)
> 
> ![image](https://private-user-images.githubusercontent.com/114978440/384446922-1db807ca-846c-4ff4-9e76-ae2f98c343d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwODY5ODYsIm5iZiI6MTczMTA4NjY4NiwicGF0aCI6Ii8xMTQ5Nzg0NDAvMzg0NDQ2OTIyLTFkYjgwN2NhLTg0NmMtNGZmNC05ZTc2LWFlMmY5OGMzNDNkNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwOFQxNzI0NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZTE2MWNiZDVlZTViZjZiNTg2NjE4YWQwM2YwMDQwNmExZjg0YWRiZTUwYzc1YjM1ZTVjMDhkOGYwN2E0ZjI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.FAaApTb864keV0W-8871jFQhNhl3IFOQiuCAoexfJp4)
> 
> **如果遇到获取到直播源后，录制出错的情况，可以把直播间地址贴出来**

可以录制 可以监测 就是莫名报错 未发现影响 没有开代理
ERROR    | douyinliverecorder.utils:wrapper:25 - 错误信息: type: KeyError, 'data' in function get_bilibili_room_info_h5 at line: 658

**Comment by ihmily** [comment]
>可以录制 可以监测 就是莫名报错 未发现影响 没有开代理
ERROR | douyinliverecorder.utils:wrapper:25 - 错误信息: type: KeyError, 'data' in function get_bilibili_room_info_h5 at line: 658

获取B站直播标题失败，所以一直报 `'data' in function get_bilibili_room_info_h5` 这个错误，但不影响录制，这个后续会修复。

**Comment by gyc0123** [comment]
你这个是有一个链接不对吧，/189那个，那个链接报错

**Comment by coldmountein** [comment]
> @ningsibuqu @End-Satan
> 
> **随机录制了几个B站直播都是正常的，你们如果开了代理，把代理关掉再录制试一下。**
> 
> ![image](https://private-user-images.githubusercontent.com/114978440/384441975-2ceec480-7e96-4c5e-bd8e-aa3a3fde6834.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzNzQ1MjYsIm5iZiI6MTczMTM3NDIyNiwicGF0aCI6Ii8xMTQ5Nzg0NDAvMzg0NDQxOTc1LTJjZWVjNDgwLTdlOTYtNGM1ZS1iZDhlLWFhM2EzZmRlNjgzNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMlQwMTE3MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YmJjZWEwN2EwOTIyMzc4ODBlMTM1YzIzNTA4ODdhMjVjZDk4NTE3YWMzZDE4Y2U1NGUyNTMwYTkyMGRhODUyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.SX-3pAAgWevv22si9z3NerWbKZ_tQz2uh1gzM8_uZVI)
> 
> ![image](https://private-user-images.githubusercontent.com/114978440/384446385-00152d64-f90b-409d-afee-78ebf4d433a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzNzQ1MjYsIm5iZiI6MTczMTM3NDIyNiwicGF0aCI6Ii8xMTQ5Nzg0NDAvMzg0NDQ2Mzg1LTAwMTUyZDY0LWY5MGItNDA5ZC1hZmVlLTc4ZWJmNGQ0MzNhNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMlQwMTE3MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNTQ5ZmRjZGU5M2YwMGQ1NzgzZWJhODU3ZTZiNDc5MDM3ZmZlZmNiYzFlZDk3ZjEwYzhhNTAzZjc4YTYzNmMwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.4V7dn-HLO7JDr14JA8up7uGuUS2VhaT0j1W4Idht2Eg)
> 
> ![image](https://private-user-images.githubusercontent.com/114978440/384446922-1db807ca-846c-4ff4-9e76-ae2f98c343d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzNzQ1MjYsIm5iZiI6MTczMTM3NDIyNiwicGF0aCI6Ii8xMTQ5Nzg0NDAvMzg0NDQ2OTIyLTFkYjgwN2NhLTg0NmMtNGZmNC05ZTc2LWFlMmY5OGMzNDNkNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMlQwMTE3MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNzRmYTlhNTczNjliYmMyZjNjNzA4MGRjMzAyMGU5ZDZhZDg5OGViZTQ5NTIyZGMzNjY1NzBjYTIwOGNiOTk4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.2fwLrAHxf7KBG12pW0HEOfha77W9NgK2crGlNy6NCuI)
> 
> **如果遇到获取到直播源后，录制出错的情况，可以把直播间地址贴出来**

可以试试看下面的地址呢，我测试了最新的版本下用docker运行还是不行，报错信息是
2024-11-12 03:45:39.198 | ERROR    | douyinliverecorder.utils:wrapper:25 - 错误信息: type: KeyError, 'data' in function get_bilibili_room_info_h5 at line: 658
链接
https://live.bilibili.com/757349
