### ISSUE TITLE
🐛[BUG] 请输入标题sooplive的cookies会乱码

### ISSUE THREAD

**Issue by ripperX309** [ihmily/DouyinLiveRecorder#766]
### ⚠️ 确认是否已存在类似问题

- [X] 我已经搜索过issues，没有找到类似问题

### 🔧 运行方式

直接运行的exe文件

### 🐍 如果是使用源代码运行，请选择你的Python环境版本

None

### 💻 请选择你的系统环境

Windows 11

### ⚠️ 确认是否已经重试多次

- [X] 我已经尝试过多次，仍然出现问题

### 🕹 复现步骤

1. 录制直播地址https://play.sooplive.co.kr/sol3712
2. 使用录制格式是录制完成后转mp4

### 😯 问题描述

将sooplive的cookies填入afreecatv那栏，前两天断网了，重新弄好网络之后cookies变成很多%乱码。在电脑重启之后也会出现这种很多%的情况

### 📜 错误信息

无，无法记录日志

**Comment by ihmily** [comment]
建议直接在配置文件中配置好afreecatv（sooplive）的账号密码，让程序自己登录获取cookie

**Comment by ripperX309** [comment]
好的好的，感谢
