### ISSUE TITLE
🐛[BUG] 发现v3.0.9版本无法对YY直播进行录制，大佬能帮忙解决一下吗？

### ISSUE THREAD

**Issue by feiepushi** [ihmily/DouyinLiveRecorder#769]
### ⚠️ 确认是否已存在类似问题

- [X] 我已经搜索过issues，没有找到类似问题

### 🔧 运行方式

直接运行的exe文件

### 🐍 如果是使用源代码运行，请选择你的Python环境版本

None

### 💻 请选择你的系统环境

Windows 10

### ⚠️ 确认是否已经重试多次

- [X] 我已经尝试过多次，仍然出现问题

### 🕹 复现步骤

https://www.yy.com/1353134967/1353134967,主播: 小艾
https://www.yy.com/22490906/22490906,主播: 燃舞蹈
https://www.yy.com/1356035086/1356035086,主播: 卡卡

### 😯 问题描述

现在无法对YY直播进行录制，不知道是为什么，希望大佬能帮忙解决一下，谢谢❤

**Comment by ihmily** [comment]
请使用最新版v4.0.1，已修复yy直播录制
