### ISSUE TITLE
请问可以录制没有粉丝灯牌效果的直播吗？

### ISSUE THREAD

**Issue by wodesenlin** [ihmily/DouyinLiveRecorder#77]
请问可以录制没有粉丝灯牌效果的直播吗？

**Comment by ihmily** [comment]
比如？这个录制的就是纯直播视频

**Comment by wodesenlin** [comment]
目前录制的视频，是带有粉丝灯牌那个标志的，抖音是否有开放视频源，是没有这个标识呢？
<img width="122" alt="1700745082892" src="https://github.com/ihmily/DouyinLiveRecorder/assets/26407724/2b025289-6d57-4255-a7cb-a4c23351cb18">
或者，如果是我自己的直播间，可以录制这种视频源吗？

**Comment by ihmily** [comment]
这个貌似嵌入到视频流中的，当抖音服务器推流到APP时的流中就包含该标志，而不是后期加入的

**Comment by yu1t** [comment]
这个粉丝灯牌。是主播自己开启的相机特效啊，类似美颜，这就是是源视频
