### ISSUE TITLE
❓[Question] bash脚本路径 = 可以是bat或者python吗?     windows环境这里具体要什么格式?

### ISSUE THREAD

**Issue by 9ihbd2DZSMjtsf7vecXjz** [ihmily/DouyinLiveRecorder#771]
### ⚠️ 搜索是否存在类似问题

- [X] 我已经搜索过issues，没有找到相似的问题

### 🔧 运行方式

直接运行的exe文件

### 🐍 如果是使用源代码运行，请选择你的Python环境版本

None

### 💻 请选择你的系统环境

Windows 10

### 🤔 问题详情

bash脚本路径 = 
windows环境如何在直播录制后执行bat或者python?  看配置文件只支持linux下执行任务后的bash, 请问win如何在录制后执行脚本? 谢谢

 感谢

**Comment by gyc0123** [comment]
这个代码是执行bash的，现在只在linux下执行，你要是用python直接执行源码的话就可以在这填想执行的东西
`main.py`
```
        if bash_file_path:
            if os_type != 'nt':
                print(f'准备执行自定义Bash脚本，请确认脚本是否有执行权限! 路径:{bash_file_path}')
                bash_command = [bash_file_path, record_name.split(' ', maxsplit=1)[-1], save_file_path, save_type,
                                split_video_by_time, ts_to_mp4]
                run_bash(bash_command)
            else:
                print('只支持在Linux环境下执行Bash脚本')
```

**Comment by 9ihbd2DZSMjtsf7vecXjz** [comment]
> 这个代码是执行bash的，现在只在linux下执行，你要是用python直接执行源码的话就可以在这填想执行的东西 `main.py`
> 
> ```
>         if bash_file_path:
>             if os_type != 'nt':
>                 print(f'准备执行自定义Bash脚本，请确认脚本是否有执行权限! 路径:{bash_file_path}')
>                 bash_command = [bash_file_path, record_name.split(' ', maxsplit=1)[-1], save_file_path, save_type,
>                                 split_video_by_time, ts_to_mp4]
>                 run_bash(bash_command)
>             else:
>                 print('只支持在Linux环境下执行Bash脚本')
> ```

感谢解答, 请问有什么办法能支持win环境下录制完成后执行bat或者python吗,感谢

**Comment by gyc0123** [comment]
你要是会python的话在这行附近加上自己的代码不就好了，bat的话就加上一行subprocess.run('C:\你的路径.bat')

**Comment by 9ihbd2DZSMjtsf7vecXjz** [comment]
> 你要是会python的话在这行附近加上自己的代码不就好了，bat的话就加上一行subprocess.run('C:\你的路径.bat')

感谢老板点播,    好人一生平安

**Comment by ihmily** [comment]
已支持python脚本，bat或者bash脚本，在config.ini中进行配置
以下是三种脚本的配置示例：

```
是否录制完成后执行自定义脚本 = 是
自定义脚本执行命令 = python test.py
```

```
是否录制完成后执行自定义脚本 = 是
自定义脚本执行命令 = test.bat
```

```
是否录制完成后执行自定义脚本 = 是
自定义脚本执行命令 = bash test.sh
```

**Comment by Etherrrr** [comment]
@ihmily 希望可以把脚本配置示例加入Readme🙇‍♂️
