### ISSUE TITLE
🐛[BUG] 3.0.9 小红书失效，录制出来仅音频，无视频画面

### ISSUE THREAD

**Issue by ningsibuqu** [ihmily/DouyinLiveRecorder#780]
### ⚠️ 确认是否已存在类似问题

- [X] 我已经搜索过issues，没有找到类似问题

### 🔧 运行方式

直接运行的exe文件

### 🐍 如果是使用源代码运行，请选择你的Python环境版本

None

### 💻 请选择你的系统环境

Windows 10

### ⚠️ 确认是否已经重试多次

- [X] 我已经尝试过多次，仍然出现问题

### 🕹 复现步骤

任意一个开播的直播间，录制格式是ts，今天录制出来的内容全是没有视频画面的
链接格式是直播间地址以及主页，都尝试过

![image](https://github.com/user-attachments/assets/aaab6e6f-a7c3-4bee-8fbb-72e209dbc4bc)
![image](https://github.com/user-attachments/assets/c0c492a9-4bd8-4e0e-a211-c63918c58c4d)

### 😯 问题描述

如图

**Comment by ihmily** [comment]
如果ts录制出错，可以尝试使用flv格式录制，小红书的是flv直播流。

**Comment by ningsibuqu** [comment]
> 如果ts录制出错，可以尝试使用flv格式录制，小红书的是flv直播流。

试了一下 flv 可以，但感觉 ts 格式挺好用的，能修复吗？或者怎么单独设置小红书 flv 录制？

**Comment by ihmily** [comment]
这两天会修复

**Comment by ningsibuqu** [comment]
遇到一次抖音游戏直播，录制中打开ts，只有音频，录制完成后转码mp4就正常了

**Comment by DouIce** [comment]
> 如果ts录制出错，可以尝试使用flv格式录制，小红书的是flv直播流。
我之前用mp4格式可以录制小红书，但是从11月15日之后mp4格式不能再录制小红书的直播了，然后又试了ts也不行，现在用flv能录制，但是播放的话显示编码错误，转码mp4也失败。有什么解决的办法吗？

**Comment by ihmily** [comment]
@DouIce 更新的还有bug，可以试试退回使用3.0.8版本录制小红书，但是只能小红书直播间地址，不支持主页。

**Comment by ihmily** [comment]
或者等4.0.1版本出来就好了

**Comment by ihmily** [comment]
最新版v4.0.1已经发布，已修复小红书直播录制

**Comment by ningsibuqu** [comment]
> 最新版v4.0.1已经发布，已修复小红书直播录制

默认录制的是flv格式 然后直播结束转mp4格式为0字节

[录制设置]
language(zh_cn/en) = zh_cn
是否跳过代理检测(是/否) = 是
直播保存路径(不填则默认) = 
保存文件夹是否以作者区分 = 是
保存文件夹是否以时间区分 = 否
保存文件夹是否以标题区分 = 否
保存文件名是否包含标题 = 否
是否去除名称中的表情符号 = 是
视频保存格式ts|mkv|flv|mp4|mp3音频|m4a音频 = ts
原画|超清|高清|标清|流畅 = 原画
是否使用代理ip(是/否) = 是
代理地址 = 
同一时间访问网络的线程数 = 3
循环时间(秒) = 300
排队读取网址时间(秒) = 0
是否显示循环秒数 = 否
是否显示直播源地址 = 否
分段录制是否开启 = 否
是否强制启用https录制 = 否
录制空间剩余阈值(gb) = 1.0
视频分段时间(秒) = 1800
录制完成后自动转为mp4格式 = 是
追加格式后删除原文件 = 是
生成时间字幕文件 = 否
是否录制完成后执行自定义脚本 = 否
自定义脚本执行命令 = 
使用代理录制的平台(逗号分隔) = tiktok, sooplive, pandalive, winktv, flextv, popkontv, twitch, liveme, showroom, chzzk, shopee, shp, youtu
额外使用代理录制的平台(逗号分隔) = 
强制启用https录制 = 否

**Comment by ihmily** [comment]
手动中断直播录制呢？我这是正常的

**Comment by ningsibuqu** [comment]
> 手动中断直播录制呢？我这是正常的

手动中断直播录制，抖音的ts格式有自动转换mp4并删除ts文件

小红书的flv格式未转换mp4文件

**Comment by ningsibuqu** [comment]
> 手动中断直播录制呢？我这是正常的

这个正常下播结束录制的 flv 可以正常播放 但没有略缩图和无法转mp4

中断直播录制的话 flv 没问题 可以正常转换

明天我再试试会不会复现吧

**Comment by ihmily** [comment]
两种录制地址：

1.使用主播主页地址录制（支持自动获取最新直播间地址），但是强制使用flv格式录制，**如果开启了自动转mp4有可能转码失败**。可以将config.ini配置文件中的 `追加格式后删除原文件 = 否` 改成否，这样即使转码失败，也会保留原始的录制文件。

2.使用主播直播间地址进行录制，大部分时候不会强制使用flv格式录制，即会跟我们配置的格式进行录制，也能正常进行转码为mp4，但是它的直播间地址是一次性的，每次开播都会变化，意味着每次都要手动更新直播间地址，无法进行监控开播。

如下：
![image](https://github.com/user-attachments/assets/5f91d1c2-8abd-4bb9-a4a3-f1fe4a160652)
![image](https://github.com/user-attachments/assets/4cdbfe62-3f4a-42dd-9865-17a64df2f32f)

**Comment by ningsibuqu** [comment]
> 两种录制地址：
> 
> 1.使用主播主页地址录制（支持自动获取最新直播间地址），但是强制使用flv格式录制，**如果开启了自动转mp4有可能转码失败**。可以将config.ini配置文件中的 `追加格式后删除原文件 = 否` 改成否，这样即使转码失败，也会保留原始的录制文件。
> 
> 2.使用主播直播间地址进行录制，大部分时候不会强制使用flv格式录制，即会跟我们配置的格式进行录制，也能正常进行转码为mp4，但是它的直播间地址是一次性的，每次开播都会变化，意味着每次都要手动更新直播间地址，无法进行监控开播。
> 
> 如下： ![image](https://private-user-images.githubusercontent.com/114978440/391256953-5f91d1c2-8abd-4bb9-a4a3-f1fe4a160652.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMwNzU2NjMsIm5iZiI6MTczMzA3NTM2MywicGF0aCI6Ii8xMTQ5Nzg0NDAvMzkxMjU2OTUzLTVmOTFkMWMyLThhYmQtNGJiOS1hNGEzLWYxZmU0YTE2MDY1Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwMVQxNzQ5MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZDU0ZmFlMjBmMDdmZTA5ODJiNmNjZGRhNDIwNjcyNGZlZGU3NTQ4ZjZmMzNkYTBmYjJmOWQ0MDJhOTA2MWYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.3Z_Z2pY0TWEuX7h8UxJlRtYTaOHuKdQLByj3mktFphg) ![image](https://private-user-images.githubusercontent.com/114978440/391257468-4cdbfe62-3f4a-42dd-9865-17a64df2f32f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMwNzU2NjMsIm5iZiI6MTczMzA3NTM2MywicGF0aCI6Ii8xMTQ5Nzg0NDAvMzkxMjU3NDY4LTRjZGJmZTYyLTNmNGEtNDJkZC05ODY1LTE3YTY0ZGYyZjMyZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwMVQxNzQ5MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mOTA5MWE2OTMxNGY5MjdmNzAzNDcwMmY5NmQwODgzYTUwOTk2MzFjZDQyM2FmMGY5MGRhODhiNDEzN2FjZTdmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.CtZgvBGiO68DJkSn3MFg90J_hmKcNaijoHaIp_83OD0)

是的，主页录制，直播结束时转码又失败了，转mkv倒是能成功，能不能单独设置小红书转码为mkv呢？
