### ISSUE TITLE
🐛[BUG] 小红书主页地址添加以后，无法录制直播

### ISSUE THREAD

**Issue by xingchen857** [ihmily/DouyinLiveRecorder#782]
### ⚠️ 确认是否已存在类似问题

- [X] 我已经搜索过issues，没有找到类似问题

### 🔧 运行方式

直接运行的exe文件

### 🐍 如果是使用源代码运行，请选择你的Python环境版本

None

### 💻 请选择你的系统环境

Windows 10

### ⚠️ 确认是否已经重试多次

- [X] 我已经尝试过多次，仍然出现问题

### 🕹 复现步骤

主页链接是这个https://www.xiaohongshu.com/user/profile/5a63188e4eacab3e44818756?xhsshare=CopyLink&appuid=5c6cca29000000001203499c&apptime=1731721824&share_id=bc237ba1073e40e788b95855512597ca
在URL添加以后，打开软件检测完代理就直接报错，
<img width="722" alt="微信图片_20241116095600" src="https://github.com/user-attachments/assets/4510085e-c12f-4ca7-b1ba-88c3bcc0708b">
<img width="672" alt="微信图片_20241116095605" src="https://github.com/user-attachments/assets/e1e96def-302c-4ca9-80a2-a45872575f9b">

### 😯 问题描述

<img width="722" alt="微信图片_20241116095600" src="https://github.com/user-attachments/assets/90bd8a05-bc40-4974-bd81-05e7a751e7ae">
<img width="672" alt="微信图片_20241116095605" src="https://github.com/user-attachments/assets/3e30bafc-3549-43cb-a586-b2346d7e8877">

**Comment by liruihaod** [comment]
同样遇到这个问题。

**Comment by Ugedainicz** [comment]
我也遇到同样的问题

**Comment by enologist** [comment]
我也遇到了同样的问题，返回码都是一样的。

**Comment by enologist** [comment]
改成flv之后就能录了，3.0.9版本只能用flv格式吗？

**Comment by Guan-jinquan** [comment]
> 改成flv之后就能录了，3.0.9版本只能用flv格式吗？
感谢，确实可以了

**Comment by enologist** [comment]
> > 改成flv之后就能录了，3.0.9版本只能用flv格式吗？
> > 感谢，确实可以了

但是录下来只有声音的

**Comment by ihmily** [comment]
https://github.com/ihmily/DouyinLiveRecorder/issues/780#issuecomment-2509021323
