### ISSUE TITLE
❓[Question]录制soop直播的视频老是一卡一卡的

### ISSUE THREAD

**Issue by wyh2077** [ihmily/DouyinLiveRecorder#785]
### ⚠️ 搜索是否存在类似问题

- [X] 我已经搜索过issues，没有找到相似的问题

### 🔧 运行方式

直接运行的exe文件

### 🐍 如果是使用源代码运行，请选择你的Python环境版本

Python 3.10

### 💻 请选择你的系统环境

Windows 11

### 🤔 问题详情

每次录制soop的视频总是一卡一卡的，录制国内直播的视频就没有这种问题

**Comment by ihmily** [comment]
网络不稳定就会这样，导致丢帧跳帧，可以降低录制画质或者换快一点的网络代理。
