### ISSUE TITLE
❓[Question] Why did the emoji between names disappear in the latest version?

### ISSUE THREAD

**Issue by chaiz64** [ihmily/DouyinLiveRecorder#789]
### ⚠️ Search for similar issues

- [X] I have searched the issues and found no similar questions

### 🔧 How did you run the program?

Executable file run directly

### 🐍 If running with source code, please select your Python environment version

Python 3.13

### 💻 Please select your system environment

Windows 11

### 🤔 Question details

How can I make the emojis display like they used to?

https://live.douyin.com/amas.,主播: 阿曼妲
﻿https://live.douyin.com/ccx614,主播: 茶茶🧸
﻿https://live.douyin.com/cczplyyy,主播: 凌小野
https://live.douyin.com/chachayuan,主播: 凛0🔔（观月苏苏）
https://live.douyin.com/chunchunchunchun,主播: 纯纯🥛
https://live.douyin.com/cs282898,主播: 小烤鱼～
https://live.douyin.com/famfam000,主播: 爱宝✈️
https://live.douyin.com/gggjjc123,主播: 兔兔💃

**Comment by ihmily** [comment]
@chaiz64 sure, in the latest version, you can set `是否去除名称中的表情符号 = 否` in config.ini.
