### ISSUE TITLE
想问问宽屏可以自己设置参数吗。就像2K和4k的分辨率。手机平板模式那种。显示宽屏。录制更多内容。

### ISSUE THREAD

**Issue by dai1400** [ihmily/DouyinLiveRecorder#79]
这个设置可以手动更改吗。

**Comment by ihmily** [comment]
这个项目并不是对屏幕录制，而是获取各平台的直播源地址，进行实时下载直播视频，请知悉。
如果要更改下载画质，可以在 config/config.ini 文件中进行配置，其中可选 直接间支持的画质
