### ISSUE TITLE
小红书虽然看着是正常录制的，但是录制异常 不管是刚开播还是开播中、还是录制结束，打开录制结果的时候都只听到声音而不显示画面

### ISSUE THREAD

**Issue by luoke123-prog** [ihmily/DouyinLiveRecorder#799]
### ⚠️ 确认是否已存在类似问题

- [X] 我已经搜索过issues，没有找到类似问题

### 🔧 运行方式

直接运行的exe文件

### 🐍 如果是使用源代码运行，请选择你的Python环境版本

Python 3.11

### 💻 请选择你的系统环境

Windows 10

### ⚠️ 确认是否已经重试多次

- [X] 我已经尝试过多次，仍然出现问题

### 🕹 复现步骤

如图所示：
![捕获12](https://github.com/user-attachments/assets/078e7c55-60c9-4e4f-878b-64d6113c4c91)
![捕获1](https://github.com/user-attachments/assets/736906d1-227e-4683-b9c2-d804f62866c5)
小红书虽然看着是正常录制的，但是录制异常 不管是刚开播还是开播中、还是录制结束，打开录制结果的时候都只听到声音而不显示画面，包括未分段和分段后也是只听到声音而不显示画面，这是怎么回事啊，需要怎么解决啊？

### 😯 问题描述

如图所示：
![捕获12](https://github.com/user-attachments/assets/078e7c55-60c9-4e4f-878b-64d6113c4c91)
![捕获1](https://github.com/user-attachments/assets/736906d1-227e-4683-b9c2-d804f62866c5)
小红书虽然看着是正常录制的，但是录制异常 不管是刚开播还是开播中、还是录制结束，打开录制结果的时候都只听到声音而不显示画面，包括未分段和分段后也是只听到声音而不显示画面，这是怎么回事啊，需要怎么解决啊？

### 📜 错误信息

如图所示：
![捕获12](https://github.com/user-attachments/assets/078e7c55-60c9-4e4f-878b-64d6113c4c91)
![捕获1](https://github.com/user-attachments/assets/736906d1-227e-4683-b9c2-d804f62866c5)
小红书虽然看着是正常录制的，但是录制异常 不管是刚开播还是开播中、还是录制结束，打开录制结果的时候都只听到声音而不显示画面，包括未分段和分段后也是只听到声音而不显示画面，这是怎么回事啊，需要怎么解决啊？

**Comment by ihmily** [comment]
https://github.com/ihmily/DouyinLiveRecorder/issues/809#issuecomment-2509018515
