### ISSUE TITLE
请求增加录制结束后执行sh脚本

### ISSUE THREAD

**Issue by coldnight9** [ihmily/DouyinLiveRecorder#8]
大佬，请问能否增加这个配置呢？后执行sh脚本，上传网盘。

**Comment by ihmily** [comment]
确定是执行sh脚本？不过上传到网盘的想法挺好，可以调用网盘上传接口进行自动上传文件。不过，上传到什么网盘呢？

百...度云？

**Comment by coldnight9** [comment]
> 

是的，上传云盘，我目前使用的bash脚本上传到阿里云盘和Dropbox云盘
