### ISSUE TITLE
🐛[BUG] YY直播彻底不能录制了，麻烦可以看一下吗？

### ISSUE THREAD

**Issue by feiepushi** [ihmily/DouyinLiveRecorder#800]
### ⚠️ 确认是否已存在类似问题

- [X] 我已经搜索过issues，没有找到类似问题

### 🔧 运行方式

直接运行的exe文件

### 🐍 如果是使用源代码运行，请选择你的Python环境版本

None

### 💻 请选择你的系统环境

Windows 10

### ⚠️ 确认是否已经重试多次

- [X] 我已经尝试过多次，仍然出现问题

### 🕹 复现步骤

https://www.yy.com/22490906/22490906

### 😯 问题描述

试过几十个主播都不能录制，可以麻烦看一下吗？

**Comment by ihmily** [comment]
最新版v4.0.1已经修复YY直播录制
