### ISSUE TITLE
🐛[BUG] 使用最新版本3.0.9录制小红书直播 显示正在录制 但实际已经停止了录制 

### ISSUE THREAD

**Issue by sylvielee0730** [ihmily/DouyinLiveRecorder#809]
### ⚠️ 确认是否已存在类似问题

- [X] 我已经搜索过issues，没有找到类似问题

### 🔧 运行方式

直接运行的exe文件

### 🐍 如果是使用源代码运行，请选择你的Python环境版本

None

### 💻 请选择你的系统环境

Windows 10

### ⚠️ 确认是否已经重试多次

- [X] 我已经尝试过多次，仍然出现问题

### 🕹 复现步骤

1.小红书主页地址https://www.xiaohongshu.com/user/profile/64e44bce00000000010070b3?xhsshare=WeixinSession&appuid=55c06ae5b7ba2205e9cb3cad&apptime=1732364052&share_id=9215d392947247faa2570f026001d371

2.采用 flv格式

### 😯 问题描述

使用最新版本3.0.9录制小红书直播 输入主页链接后 显示正在录制 但实际已经停止了录制 没有显示任何报错信息 @ihmily

**Comment by sylvielee0730** [comment]
请问这种情况是IP被封了吗？如果是的话，软件也没有报错…还在显示继续录制。而且是刚打开软件几分钟我就发现好像没录上…因为视频大小一直不在增长了。只有打开软件几分钟就会被封IP吗？

**Comment by ihmily** [comment]
最新版4.0.1已经发布 小红书录制问题已修复。
