### ISSUE TITLE
钉钉推送不能用了

### ISSUE THREAD

**Issue by netcre** [ihmily/DouyinLiveRecorder#81]
机器人下线了 望修复一下

**Comment by ihmily** [comment]
机器人下线了是什么意思？我刚测试，截止2023-12-03 是能正常使用的。

![image](https://github.com/ihmily/DouyinLiveRecorder/assets/114978440/aac8c63d-d100-4848-9886-66b53b69bc96)

**Comment by netcre** [comment]
奇葩了 我创建的怎么都收不到消息

**Comment by netcre** [comment]
![image](https://github.com/ihmily/DouyinLiveRecorder/assets/29759858/67e50d96-f223-4b8d-b285-a0c3511aac13)![image](https://github.com/ihmily/DouyinLiveRecorder/assets/29759858/4e7cbfa7-512d-46e6-85f6-a6c266b19652)这样设置那里不对 还是收不到任何提醒

**Comment by ihmily** [comment]
![image](https://github.com/ihmily/DouyinLiveRecorder/assets/114978440/2974b863-894c-4e0c-ab55-3dc32cba73b0)

这里你要填写 钉钉 才会生效哦
