### ISSUE TITLE
🐛[BUG] 录制抖音一个正在直播的房间时无法录制

### ISSUE THREAD

**Issue by 12414123123123** [ihmily/DouyinLiveRecorder#818]
### ⚠️ 确认是否已存在类似问题

- [X] 我已经搜索过issues，没有找到类似问题

### 🔧 运行方式

直接运行的exe文件

### 🐍 如果是使用源代码运行，请选择你的Python环境版本

Python 3.10

### 💻 请选择你的系统环境

Windows 10

### ⚠️ 确认是否已经重试多次

- [X] 我已经尝试过多次，仍然出现问题

### 🕹 复现步骤

1.录制的直播间地址是https://live.douyin.com/750401050942
2.使用的录制格式是ts

### 😯 问题描述

错误代码为
![498f78510bca2bf6831abb2440ba5283](https://github.com/user-attachments/assets/35ec844b-3059-46a9-927d-30dbe5e31e04)

**Comment by 12414123123123** [comment]
![image](https://github.com/user-attachments/assets/1566a61b-b2fb-48d6-b86c-7363d4d7c83b)
将录制格式更改为flv后可以正常录制

**Comment by ihmily** [comment]
@12414123123123 因为直播标题中有？问号，并且你又开启了按标题区分，所以导致录制无法解析，你把标题区分关掉就可以正常录制ts格式或者flv格式了。

**Comment by ihmily** [comment]
![image](https://github.com/user-attachments/assets/fe40acb1-3707-4f2b-b89c-08774e8c9894)
