### ISSUE TITLE
想请问能否加入一个小众软件的直播自动录制……可以付费

### ISSUE THREAD

**Issue by kunhhj13291** [ihmily/DouyinLiveRecorder#82]
代码小白实在是看不懂代码但很需要。。现在都是手动获取m3u8链接录制 但是要工作有时候录不上
可以按大佬要求给辛苦费

**Comment by ihmily** [comment]
什么平台，可以给个地址

**Comment by kunhhj13291** [comment]
> 什么平台，可以给个地址

https://app.blued.cn/live?id=8xDGXE&action=liveplay&lid=34535376&uid=8xDGXE&detail=
您好，是类似这种的……具体费用是多少就由大佬决定吧，非常感谢

**Comment by 1583298606** [comment]
afreecatv这个大平台可以加上么？因为有年龄限制直播，应该需要考虑个人cookie

**Comment by ihmily** [comment]
> afreecatv这个大平台可以加上么？因为有年龄限制直播，应该需要考虑个人cookie

最新2.0.6版本已加入afreecatv

**Comment by kunhhj13291** [comment]
不好意思这几天没有看邮件，非常感谢您的更新和维护🙏我现在就下载试试看！另外有支付宝的二维码吗？碰巧微信里没有钱了

**Comment by kunhhj13291** [comment]
![image](https://github.com/ihmily/DouyinLiveRecorder/assets/152791260/fc366c6a-3b21-45fb-bdc1-ca7db50008d9)
[错误日志文件.log](https://github.com/ihmily/DouyinLiveRecorder/files/13642579/default.log)
![image](https://github.com/ihmily/DouyinLiveRecorder/assets/152791260/edbd8158-0c75-4ad7-95b8-2a413af5041b)

试用了一下发现有以下问题……
录制时直播时间过长同时开启了分段录制的时候会出现这种分段异常的问题
以及下面有时长4秒却600mb的文件【点开查看是一个小时直播的浓缩版】以及23分钟却有

**Comment by ihmily** [comment]
好的，经测试确实是录制时间长一点会出现该问题，后续会修复

**Comment by kunhhj13291** [comment]
然后录制断线了也并不会重连or重新开一个录制，比较烦恼
麻烦您了

**Comment by kunhhj13291** [comment]
您好不好意思又出现了新问题，在录制的时候不知为何只有这个主播会报错
但之前用2.08版本录制的时候录这个主播是很正常的，不知道是我设置有问题还是其他（但只有录制这个主播的时候会出错）希望能解决。
辛苦您了
[DouyinLiveRecorder.log](https://github.com/ihmily/DouyinLiveRecorder/files/14463472/DouyinLiveRecorder.log)
![QQ截图20240301234112](https://github.com/ihmily/DouyinLiveRecorder/assets/152791260/6906f011-0788-4ac4-8729-6b27960b8aae)
主播的地址是：https://app.blued.cn/live?id=q17A7d&af_adset=wechat&action=liveplay&lid=35228031&uid=q17A7d&detail=
![image](https://github.com/ihmily/DouyinLiveRecorder/assets/152791260/39dcb777-9574-4b42-bbbb-594116bdd22f)
这个是我的设置
