### ISSUE TITLE
YY检测不到直播

### ISSUE THREAD

**Issue by xinzhihong** [ihmily/DouyinLiveRecorder#84]
YY检测不到直播 开播了还是等待直播

**Comment by xinzhihong** [comment]
4836 难道YY要CK？

**Comment by xinzhihong** [comment]
> 请给一下直播间地址，我这边测试了几个都是正常录制的。

4836 难道YY要CK？

**Comment by xinzhihong** [comment]
> 请给一下直播间地址，我这边测试了几个都是正常录制的。

4836 难道YY要CK？

**Comment by ihmily** [comment]
![image](https://github.com/ihmily/DouyinLiveRecorder/assets/114978440/843f6da2-bd03-4a56-8da4-eaeed93dd80c)

对的，这种有特定限制的，你得登录账号后获取ck

**Comment by xinzhihong** [comment]
> ![图像](https://private-user-images.githubusercontent.com/114978440/288119374-843f6da2-bd03-4a56-8da4-eaeed93dd80c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3OTMyNjgsIm5iZiI6MTcwMTc5Mjk2OCwicGF0aCI6Ii8xMTQ5Nzg0NDAvMjg4MTE5Mzc0LTg0M2Y2ZGEyLWJkMDMtNGE1Ni04ZGE0LWVhZWVkOTNkZDgwYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwNVQxNjE2MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNDA5MjM3YTgwNjVhNWQ1NDlkODAwOTA2OTBhOTM5N2M3OTIzZDExZGQzMzUyYzY2NjEyZDgzZjA2YzA2YzU0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._LEKFNdrRM3gmpoJy7AXJ7duA7NHFrbQKtgcHMHVDbw)
> 
> 对的，这种有特定限制的，你得登录账号后获取ck

取了好像也不行

**Comment by xinzhihong** [comment]
那会直播的  也是等待直播

**Comment by ihmily** [comment]
当时你是否是登录账号观看的呢？如果登录了账号，则那时一直显示等待直播，有可能是因为该直播间设置了限制匿名用户不能观看，并且 你没有添加登录后的ck，所以没有权限获取到直播流，因此会一直显示等待直播的状态。

如果当时你没有登录账号，也能看那个直播间，这个可能是程序存在bug，但目前我没有发现有其他直播间会这样。麻烦你能找出第二个这种情况的直播间吗？

**Comment by xinzhihong** [comment]
> 当时你是否是登录账号观看的呢？如果登录了账号，则那时一直显示等待直播，有可能是因为该直播间设置了限制匿名用户不能观看，并且 你没有添加登录后的ck，所以没有权限获取到直播流，因此会一直显示等待直播的状态。
> 
> 如果当时你没有登录账号，也能看那个直播间，这个可能是程序存在bug，但目前我没有发现有其他直播间会这样。麻烦你能找出第二个这种情况的直播间吗？

没登陆跟登录都试了 难道CK抓错了

**Comment by xinzhihong** [comment]
> 当前该直播间主播是未直播的状态，现在即使添加cookie也无法测试结果，或许你可以等到开启直播了以后，再次尝试添加ck之后，进行录制。

  我找一个直播的试试

**Comment by xinzhihong** [comment]
> 当前该直播间主播是未直播的状态，现在即使添加cookie也无法测试结果，或许你可以等到开启直播了以后，再次尝试添加ck之后，进行录制。

 还是不行

**Comment by ihmily** [comment]
> > 当前该直播间主播是未直播的状态，现在即使添加cookie也无法测试结果，或许你可以等到开启直播了以后，再次尝试添加ck之后，进行录制。
> 
> 现在直播了你试试

刚测试了，确实是无法检测到开播，并且问题已经查出并解决，是YY版本更新的问题。

我下个版本再更新上去吧 

![image](https://github.com/ihmily/DouyinLiveRecorder/assets/114978440/4a201557-ba7e-4ac1-81de-21873f41b5d4)
![image](https://github.com/ihmily/DouyinLiveRecorder/assets/114978440/7e27d338-e84e-491b-8b2f-0577c745184e)

**Comment by xinzhihong** [comment]
> 频繁的问题暂时无法解决。即使在官方直播页面观看，你频繁刷新网页的话，一样都会提示频繁。

好的

**Comment by ihmily** [comment]
最新2.0.5版本已发布，录制yy直播的bug已修复。

注意：如果遇到限制匿名用户无法观看的直播间，请手动获取登录账号后的Cookie，添加至配置文件，否则无法检测到。

**Comment by xinzhihong** [comment]
> 最新2.0.5版本已发布，录制yy直播的bug已修复。
> 
> 注意：如果遇到限制匿名用户无法观看的直播间，请手动获取登录账号后的Cookie，添加至配置文件，否则无法检测到。

我咋还不行呢

**Comment by ihmily** [comment]
> > > > 最新2.0.5版本已发布，录制yy直播的bug已修复。
> > > > 注意：如果遇到限制匿名用户无法观看的直播间，请手动获取登录账号后的Cookie，添加至配置文件，否则无法检测到。
> > > 
> > > 
> > > 我咋还不行呢
> > 
> > 
> > 重新下载一下最新版本试试
> 
> 就是用2.0.5 CK抓手机的还是网页的？

1、前面更新的代码还存在问题，因此我回滚了代码并重新上传了2.0.5版本，你可以等开播时再测试一下。
2、网页的ck就行。不过今晚我测试时没用CK也能正常录制，可能是因为当时房间没有设置或触发匿名用户无法观看限制。
