### ISSUE TITLE
关于ts格式分段录制的反馈

### ISSUE THREAD

**Issue by DanNianya** [ihmily/DouyinLiveRecorder#88]
在使用分段录制时发现，如果开启了ts分段录制并开启ts录制完成后自动增加生成mp4格式，好像如果保存地址不填的话，生成的mp4格式的视频，视频名永远都是 DouyinLiveRecorder.mp4，那么当第二个MP4视频保存的时候就会报错
![1702056543413](https://github.com/ihmily/DouyinLiveRecorder/assets/114657621/6313618d-9639-40d3-b034-f02cae9fda73)
当指定了保存路径后就不会再出现这个问题

但是我设置   视频分段大小(兆) = 100  时，MP4视频能够正常从ts转mp4，当设置分段大小为2000时，总会不按照这个大小来分段，有可能是不到100mb就给我转换成MP4格式了，也可能会一直以ts格式录制，根本就不转换

不知道是不是我哪里设置错了，还请大佬指点迷津
万分感谢

**Comment by ihmily** [comment]
目前最新版本已修复分段录制，支持mp4、ts、mkv等录制格式按照时间进行文件分割。

**Comment by DanNianya** [comment]
> 目前最新版本已修复分段录制，支持mp4、ts、mkv等录制格式按照时间进行文件分割。

谢谢大佬，发个码，请你喝杯蜜雪
