### ISSUE TITLE
bigo部分主播无法检测到开播

### ISSUE THREAD

**Issue by Hertz221** [ihmily/DouyinLiveRecorder#89]
1. 具体主播：https://www.bigo.tv/cn/zyt5211314，在播但是检测不到开播。
2. url_config文件设置的bigo主播名称不可用，文件名还是会变成主播默认的
----------------------------------------------------------------------------------------
2023-12-10 09:38:12,257 - 错误信息: type: AttributeError, 'NoneType' object has no attribute 'group' in function get_bigo_stream_url at line: 381
2023-12-10 09:38:12,257 - 错误信息: 'list' object has no attribute 'get' 发生错误的行数: 618

**Comment by ihmily** [comment]
1. bigo直播的bug已在最新2.0.7版本修复
2. URL_config.ini文件中本身不能配置主播名称，只能配置文件夹保存路径。不过目前最新版本我已经加上了修改主播名称的功能
3. 如要自定义主播名，修改配置文件中每条链接的 `主播：` 后面的名称即可。

**Comment by Hertz221** [comment]
> 1. bigo直播的bug已在最新2.0.7版本修复
> 2. URL_config.ini文件中本身不能配置主播名称，只能配置文件夹保存路径。不过目前最新版本我已经加上了修改主播名称的功能
> 3. 如要自定义主播名，修改配置文件中每条链接的 `主播：` 后面的名称即可。

好的谢谢大佬。是我的表达有误，我的意思是添加链接后自动获取的主播：xxx，我自己修改后文件名不遵循我修改的名称，开始录制后文件名还是主播的名称而不是我修改的。现在修好了我没问题了，谢谢

**Comment by justdoiting** [comment]
bigo网页版最高分辨率只有540*960，还时不时变成360*300，APP有高分辨率的原话，但是抓包抓不出东西，难搞
