### ISSUE TITLE
大佬你好，关于抖音cookie问题

### ISSUE THREAD

**Issue by Hertz221** [ihmily/DouyinLiveRecorder#9]
我已经填写了抖音cookie为什么还会报错呢

`2023-08-14 23:01:14,829 - 错误信息: 'NoneType' object has no attribute 'group' 发生错误的行数: 528
2023-08-14 23:01:19,863 - 错误信息: 'name' 发生错误的行数: 519
2023-08-14 23:01:25,182 - 错误信息: 'name' 发生错误的行数: 519`

虽然有这个提示但是是可以录制抖音的

不知道抖音的cookie是不是这个？
<img src="https://img1.imgtp.com/2023/08/14/zk7tV8e2.png" alt="QQ截图20230814230003.png" title="QQ截图20230814230003.png" />

求大佬解答，谢谢

**Comment by ihmily** [comment]
根据你贴的截图来看，我猜测你应该并不是在直播间页面获取的Cookie，你可以进入任意直播间页面获取，如https://live.douyin.com/745964462470 
(注意其host为 live.douyin.com )

当然，我在项目中也有上传关于selenium自动化获取cookie的代码，直接执行即可获得cookie ，具体请看https://github.com/ihmily/DouyinLiveRecorder/blob/main/cookies.py。

**Comment by Hertz221** [comment]
> 根据你贴的截图来看，我猜测你应该并不是在直播间页面获取的Cookie，你可以进入任意直播间页面获取，如 https://live.douyin.com/745964462470 （注意其host为 live.douyin.com ）
> 
> 当然，我在项目中也有上传关于Selenium自动化获取cookie的代码，直接执行即可获得cookie ，具体请看 [https://github.com/ihmily/DouyinLiveRecorder/blob/main/cookies.py。](https://github.com/ihmily/DouyinLiveRecorder/blob/main/cookies.py%E3%80%82)

谢谢，原来要到直播间获取，我一直在抖音首页找😂

**Comment by Hertz221** [comment]
> 根据你贴的截图来看，我猜测你应该并不是在直播间页面获取的Cookie，你可以进入任意直播间页面获取，如https://live.douyin.com/745964462470 (注意其host为 live.douyin.com )
> 
> 当然，我在项目中也有上传关于selenium自动化获取cookie的代码，直接执行即可获得cookie ，具体请看[https://github.com/ihmily/DouyinLiveRecorder/blob/main/cookies.py。](https://github.com/ihmily/DouyinLiveRecorder/blob/main/cookies.py%E3%80%82)

我在直播间复制了很多cookie，都是提示一样的😂抖音录不了。你那个cookie.py不太懂怎么搞，只能放弃
‘2023-08-15 09:51:11,225 - 错误信息: 'NoneType' object has no attribute 'group' 发生错误的行数: 495’
我试了很多次要么就提示👆这个，要么有提示不过可以录。
还有斗鱼好像录不了，按理说斗鱼不用cookie应该可以录，但是我检测不到开播😒

**Comment by Hertz221** [comment]
> 
> 我在直播间复制了很多cookie，都是提示一样的😂抖音录不了。你那个cookie.py不太懂怎么搞，只能放弃 ‘2023-08-15 09:51:11,225 - 错误信息: 'NoneType' object has no attribute 'group' 发生错误的行数: 495’ 我试了很多次要么就提示👆这个，要么有提示不过可以录。 还有斗鱼好像录不了，按理说斗鱼不用cookie应该可以录，但是我检测不到开播😒
最新情况就是我在网上搜了相关教程，然后成功的运行了你的cookie.py然后获取了cookie，但是问题如上，还是会提示错误，应该不是cookie的问题了

**Comment by ihmily** [comment]
> > 根据你贴的截图来看，我猜测你应该并不是在直播间页面获取的Cookie，你可以进入任意直播间页面获取，如https://live.douyin.com/745964462470 (注意其host为 live.douyin.com )
> > 当然，我在项目中也有上传关于selenium自动化获取cookie的代码，直接执行即可获得cookie ，具体请看[https://github.com/ihmily/DouyinLiveRecorder/blob/main/cookies.py。](https://github.com/ihmily/DouyinLiveRecorder/blob/main/cookies.py%E3%80%82)
> 
> 我在直播间复制了很多cookie，都是提示一样的😂抖音录不了。你那个cookie.py不太懂怎么搞，只能放弃 ‘2023-08-15 09:51:11,225 - 错误信息: 'NoneType' object has no attribute 'group' 发生错误的行数: 495’ 我试了很多次要么就提示👆这个，要么有提示不过可以录。 还有斗鱼好像录不了，按理说斗鱼不用cookie应该可以录，但是我检测不到开播😒

斗鱼的链接需要是这样的https://www.douyu.com/10657842?dyshid，链接以?dyshid结尾，否则无法正常检测和录制，是正则匹配直播间链接时出的问题，下个版本修复。

抖音的cookie，前面我已经说的很清楚了，至于你在那个页面复制的cookie为什么没用，我也不太清楚，注意在浏览器复制cookie时要点击那个（原始）然后再复制，否则可能复制不完整。项目中好像有我账号的cookie，你可以直接用我的那个也行。

**Comment by Hertz221** [comment]
> 
> 斗鱼的链接需要是这样的[https://www.douyu.com/10657842?dyshid，链接以?dyshid结尾，否则无法正常检测和录制，是正则匹配直播间链接时出的问题，下个版本修复。](https://www.douyu.com/10657842?dyshid%EF%BC%8C%E9%93%BE%E6%8E%A5%E4%BB%A5?dyshid%E7%BB%93%E5%B0%BE%EF%BC%8C%E5%90%A6%E5%88%99%E6%97%A0%E6%B3%95%E6%AD%A3%E5%B8%B8%E6%A3%80%E6%B5%8B%E5%92%8C%E5%BD%95%E5%88%B6%EF%BC%8C%E6%98%AF%E6%AD%A3%E5%88%99%E5%8C%B9%E9%85%8D%E7%9B%B4%E6%92%AD%E9%97%B4%E9%93%BE%E6%8E%A5%E6%97%B6%E5%87%BA%E7%9A%84%E9%97%AE%E9%A2%98%EF%BC%8C%E4%B8%8B%E4%B8%AA%E7%89%88%E6%9C%AC%E4%BF%AE%E5%A4%8D%E3%80%82)
> 
> 抖音的cookie，前面我已经说的很清楚了，至于你在那个页面复制的cookie为什么没用，我也不太清楚，注意在浏览器复制cookie时要点击那个（原始）然后再复制，否则可能复制不完整。项目中好像有我账号的cookie，你可以直接用我的那个也行。

感谢，我点了那个原始复制的cookie没报错了。我的问题解决了，再次感谢😄
