### ISSUE TITLE
您好，能否在下一个新版本中加入一个小功能

### ISSUE THREAD

**Issue by ajiu1998** [ihmily/DouyinLiveRecorder#91]
做 main.py 动态（30秒？）的监控 URL_config.ini 文件，比如我在运行了main.py 后 不想对某个正在直播的链接停止录制，那么我就会在URL_config.ini 将其注释掉，但是注释之后我发现它还在录制该条链接。谢谢，望回复~

**Comment by 18202821297** [comment]
你去杀进程呗，找到你在录的ffmpeg的进程，kill -15 进程id，就终止了
