### ISSUE TITLE
请增加两项平台 twitch 和 chaturbate

### ISSUE THREAD

**Issue by lbcake** [ihmily/DouyinLiveRecorder#92]
请增加两项平台 twitch 和 chaturbate

**Comment by DanNianya** [comment]
好生硬的态度

**Comment by 18202821297** [comment]
cb我自己已实现，但是肯定不能给你源码哟，这东西自己有本事就自己弄，弄不来就没办法了，不可能把这种给你拿来开源

**Comment by RiverChu0** [comment]
我也有在录cb，都录了一年多了

**Comment by lbcake** [comment]
> 我也有在录cb，都录了一年多了
哦  你用的什么软件？

**Comment by 18202821297** [comment]
自己写的哪有什么软件，而且还得代理，还有cf检测，你还得有硬盘存

**Comment by lbcake** [comment]
> 自己写的哪有什么软件，而且还得代理，还有cf检测，你还得有硬盘存

软件作者都没回复呢。 你就别再这里多嘴了。 好好的自己用你自己的就好

**Comment by 18202821297** [comment]
不是你再问我吗？
