### ISSUE TITLE
请问为什么添加cookie后仍然无法录制Afreecatv

### ISSUE THREAD

**Issue by pinkzhang** [ihmily/DouyinLiveRecorder#94]
录制的是一个有年龄限制的直播间，把网页上的cookie的全部内容都复制上了，仍然显示错误，无法录制，请问具体要复制哪段内容呢？

![屏幕截图 2023-12-14 030504](https://github.com/ihmily/DouyinLiveRecorder/assets/121802598/b521b832-d9cf-4a59-8f22-b7e8aa3627cb)

**Comment by ihmily** [comment]
请给我相关直播间地址
